### ISSUE TITLE
Window resizes out of bounds when many tabs open in OS X

### ISSUE THREAD

**Issue by Crowbeak** [mapeditor/tiled#1047]
![screen shot 2015-07-29 at 11 09 54 am](https://cloud.githubusercontent.com/assets/3011907/8948525/366412bc-35e3-11e5-872b-4ff53563a4f8.png)
I opened a lot of files, and since there were too many tabs to fit on the screen... the window just got wider and wider until it was too wide to fit on the screen.

EDIT: Closing tabs and restarting the program returned it to a reasonable size.

**Comment by bjorn** [comment]
Does the issue still happen when using the latest Tiled daily build for OS X, which is based on Qt 5.5 instead of Qt 5.4? You can find the daily builds at http://tilemapkit.com/tiled/?C=N;O=D

**Comment by Crowbeak** [comment]
I had not tried that because I'm a goof. Sorry.

The latest daily build (7-27) gives me the following error when I try to open the .dmg file:
![screen shot 2015-07-29 at 7 06 08 pm](https://cloud.githubusercontent.com/assets/3011907/8955093/f1b07614-3624-11e5-9fce-c81c781cba47.png)

I downloaded it multiple times and got the same error every time. The previous build (7-26) opened and installed fine, but has the same issue. As before, closing tabs alone is not enough; the tabs must be closed and the program restarted.
![screen shot 2015-07-29 at 7 08 58 pm](https://cloud.githubusercontent.com/assets/3011907/8955188/83be63fe-3625-11e5-914d-a3e475c4ae40.png)

One detail I forgot to mention the first time is that upon restart with fewer tabs open, The sidebar is back to default window/panel sizes with my custom tweaks discarded. I'm on the newest version of OS X.

**Comment by bjorn** [comment]
Ah, that's too bad. I think I'll need to report this as a Qt bug, but I'll make a small testing application first to see if I can reproduce it there. Thanks for trying!

**Comment by bjorn** [comment]
> As before, closing tabs alone is not enough; the tabs must be closed and the program restarted.

While it's true that closing tabs will not automatically reduce the size of the window again, I did find that you can manually resize the window to be smaller again after closing some tabs. Anyway, of course the tab bar should be scrolling instead...
