### ISSUE TITLE
Reconsider website layout

### ISSUE THREAD

**Issue by bjorn** [mapeditor/tiled#1228]
Goals:
- [ ] <s>Add link to https://www.livecoding.tv/bjorn</s>
- [x] Add link to https://twitter.com/TiledApp
- [x] For downloading, link directly to https://thorbjorn.itch.io/tiled (remove Downloads page)
- [x] Have recent blog posts on the main page (see #1194)

All while hopefully also improving the layout for the main Tiled features and the sponsors.

**Comment by ketanhwr** [comment]
I've worked with web design and jekyll a lot so I can do this one and #1194 quickly. Is the source code of the website in this repository only? And I don't think a repository for blog exists as of now?

**Comment by bjorn** [comment]
@ketanhwr The Tiled website lives in [bjorn/tiled-website](https://github.com/bjorn/tiled-website) and I've got a little WIP on adding the blog on the `blog` branch. What still needs to be done for that part is to improve the layout of individual blog posts and to provide a better general "blog index" page, which should ideally be paginated, show only snippets and have a "history" sidebar. I personally still know very little about how to use Jekyll so I'll greatly appreciate any help in this area.

The first two items, adding links to LiveEdu and my Twitter profile, are not so much technical as they are about finding a nice place for them on the site, possibly adapting the layout for it. It could be better to first work on a mockup for that rather than jumping into the HTML directly.

Thanks for offering your help here as well!

**Comment by ketanhwr** [comment]
I'm working on another branch now which is `blog-patch` on `[ketanhwr/tiled-website](https://github.com/ketanhwr/tiled-website)`. Since you're already working on a separate branch, would it be okay if you give me push access to the `blog` branch of your repo?

**Comment by bjorn** [comment]
It makes no difference whether you're working on a branch in my repository or a branch in your fork of it, apart from needing to set up access permissions, so please just work on `blog-patch` in your repository and open a pull request once you feel it's ready for that.

**Comment by ketanhwr** [comment]
Alright, I'll keep working on that :+1:

**Comment by bjorn** [comment]
Download link was changed in 686de39d402635a385f8d1fab9e78f5a5d6decbf and recent blog posts had been done in ec323e03261d9f409920d26442b511af6dc1002b. The Twitter link has been added in the new design launched earlier this year... lots of words about closing an outdated issue! :-)
