### ISSUE TITLE
Using the X key shortcut to flip an object horizontally is flipping vertically

### ISSUE THREAD

**Issue by ArmagonNo1** [mapeditor/tiled#1704]
It has come to my attention that using the X key to flip an object horizontally is not working correctly. It visibly flips it horizontally as you'd expect, but it's actually setting a vertical flip in the object parameters. The only way I can presently get the horizontal flip I want is to use the checkbox. The Y key for vertical flipping appears to work perfectly fine.

![flippingincorrectly](https://user-images.githubusercontent.com/2118291/29663335-7121ebac-88c2-11e7-94b9-c9db3061f699.gif)

**Comment by bjorn** [comment]
It looks visually alright because it also changes the rotation by 180 degrees and adjusts the position accordingly. This is the result of fixing the flipping of rotated objects and groups of objects, but I agree it leads to unexpected results in this case.

**Comment by huwpascoe** [comment]
Is there any way to map the 'X' key to just the horizontal checkbox?

**Comment by bjorn** [comment]
> Is there any way to map the 'X' key to just the horizontal checkbox?

No. I'll try to fix up this action, thanks for the reminder!

**Comment by finscn** [comment]
@bjorn , this issue is still existing in 1.8.1

**Comment by bjorn** [comment]
> this issue is still existing in 1.8.1

Yeah, sorry about that. It was one of the last issues remaining that I had scheduled for Tiled 1.8, but this release was already taking way too long so in the end I decided to drop it from the plan. And then 1.8.1 was really about getting a few serious regressions fixed.

Anyway, it's on the list of bugs to look into soon.

**Comment by finscn** [comment]
One thing I'm curious about this issue. 
 In my opinion , this issue is very easy to fix .
Why is it existing from 2017 to 2022 ?

**Comment by bjorn** [comment]
> In my opinion , this issue is very easy to fix . Why is it existing from 2017 to 2022 ?
> 
> Because it is hard to fix in fact ? or it's not a serious bug ?

@finscn Yes, it existed because it was in fact a very hard issue to solve, due to the different behavior for the various object types (tiles / rectangles / polygons) and on map orientations (orthogonal / isometric). But, I've spent about 1.5 days now on this, just for you! :wink: So, the behavior should be much better in Tiled 1.8.3.

If you can, please give it a round of testing based on the builds coming up at https://github.com/mapeditor/tiled/actions/runs/2065871063. Thanks!

**Comment by finscn** [comment]
I sorry ,  I haven't used tiledmap & github  for the past few months .  because my new project have to use ldTK.io.

Now,  I've tried 1.8.4   . It's very very wonderful.  Thanks &  I love you.
