### ISSUE TITLE
Shortcuts no longer visible in context menus since Qt 5.10

### ISSUE THREAD

**Issue by bjorn** [mapeditor/tiled#1978]
In Qt 5.10, shortcuts are no longer shown by default in context menus. However, I'd generally prefer them to be there to make them discoverable. Several actions that are only available from context menus have shortcuts that are now completely hidden.

It seems the only way to fix this is to manually specify that the shortcut should be visible for each affected action. Setting `setAttribute(Qt::AA_DontShowShortcutsInContextMenus, false)` has no effect, since `QAction` is doing:

```c++
bool QAction::isShortcutVisibleInContextMenu() const
{
    Q_D(const QAction);
    if (d->shortcutVisibleInContextMenu == -1) {
        return !QCoreApplication::testAttribute(Qt::AA_DontShowShortcutsInContextMenus)
            && QGuiApplication::styleHints()->showShortcutsInContextMenus();
    }
    return d->shortcutVisibleInContextMenu;
}
```
And the style hints say they should not be visible.

**Comment by mitchcurtis** [comment]
Just saw this on IRC, and thought I'd share https://bugreports.qt.io/browse/QTBUG-69452 with you in case you weren't aware of it.

**Comment by bjorn** [comment]
@mitchcurtis Ah, thanks for the reference! It didn't occur to me to look for an issue because the change in behavior was clearly intensional, but I think it is a little misguided and I hope they will reconsider, or at least provide an API for enabling the showing of shortcuts in all context menus.

**Comment by bjorn** [comment]
Unfortunately this issue persists in Qt 5.11 and Qt 5.12 (LTS). This means for now I'm going to stick to releasing against Qt 5.9, which may be a better choice in regards to stability anyway.

**Comment by bjorn** [comment]
Since Qt 5.13.1, shortcuts are again visible by default in context menus, except on macOS, where they are deemed too out-of-place. I'll make it so that they're always shown when the "Tiled Fusion" style is selected, which is now possible using `QGuiApplication::styleHints()->setShowShortcutsInContextMenus(true)`.
