### ISSUE TITLE
Stardew Valley maps unknown format

### ISSUE THREAD

**Issue by Makein** [mapeditor/tiled#2073]
In many sites I read that it should open maps and then we can edit them, but it doesn't work for me.
What I done:
Install the latest version of Tiled.
Once installed, at the top left, go to Edit > Preferences > Plugins and enable the tbin.dll plugin.
Extract .xnb files in maps folder
Try load with Tiled .json/.tbin/.png nothing work.
It always say unknown format
Admin rights does nothing...

**Comment by bjorn** [comment]
Hmm, normally this plugin works fine. Please try to write exactly how to reproduce the problem. "Unknown format" usually means you're trying to open a non-map file (like an image) as a map.

Just to make sure the tBIN plugin loaded successfully, can you also make sure that when you open a map file, the file type combo box includes a "Tbin map files" entry?

**Comment by bjorn** [comment]
Closing due to no answer forthcoming and also no other such reports.
