### ISSUE TITLE
Automapping creates too many undo events

### ISSUE THREAD

**Issue by JoeCreates** [mapeditor/tiled#2166]
It seems impractical that auto mapping creates undo events as if tiles were individually placed. Applying rules should create a single event.

**Comment by bjorn** [comment]
Applying the rules does create a single event, but when interleaved with the events you create while editing they do not merge and hence you get a lot of undo steps.

The challenge is to somehow allow the automapping steps to merge with the undo commands created by the tile layer editing tools.

If you find this disrupts your flow, currently the only option is to disable "Map > Automap While Drawing" and to trigger the applying of the rules manually from time to time instead.

**Comment by JoeCreates** [comment]
Ah thanks for the workaround!

**Comment by bjorn** [comment]
Finally, in the upcoming Tiled 1.9, AutoMapping will no longer create additional undo commands! :-)

Only remaining exception is when it creates or deletes objects. It's a rare case, but maybe that could be resolved later as well.
