### ISSUE TITLE
Rectangle tool

### ISSUE THREAD

**Issue by mutantleg** [mapeditor/tiled#268]
I feel a tool that let's you draw the selected tile pattern in a rectangle shape would be useful (either stretch it or mosaic it)
As tiled already has a line tool and circle tool i'm confused why the rectangle tool is missing?
I guess you could argue that the line tool is enough for most cases, but i used Tilestudio before and have been missing the rectangle tool ever since as it really helps to quickly flesh out a map base (that i can add details later to).

**Comment by zanval** [comment]
I would really love to see this feature implemented, so I am bumping it now.
A rectangular tool would save me a LOT of time while working with TILED.

**Comment by bjorn** [comment]
As of dcacd23bb1d7b55c1a5a6a32a7636b536bf64aaa there is now a shape fill tool that can fill either rectangles or circles by repeating the current stamp.

For rectangles I'd still like to add the option to "stretch" the stamp instead of repeating it.

**Comment by bjorn** [comment]
> For rectangles I'd still like to add the option to "stretch" the stamp instead of repeating it.

This is now covered by #3025, so closing this.
