### ISSUE TITLE
Command-line output not visible on Windows

### ISSUE THREAD

**Issue by bjorn** [mapeditor/tiled#2688]
The old issue #953 has resurfaced in Tiled 1.3, with no output visible anymore on Windows.

Needs to investigate if this regression is due to newer Windows version, newer Qt version or some change in Tiled.

**Comment by powertomato** [comment]
So I just wanted to try to fix this issue and found that I cannot replicate the problem when I build locally.
Both debug and release builds output to the cmd as expected. x86 or AMD64 makes no difference either.

I used the precompiled Qt5.12.9 MSVC2017 (resp. MSVC2017_64) of the Qt libraries and Qt Creator version 4.12.2 to build.
The build tools I was using were msvc2019_pe_32bit (resp. msvc2019_pe_64bit)
My Windows version is Windows 10 Pro 1903

While without beeing able to reproduce it I probabbly can't fix it, I could help you narrow down the problem. If you have any ideas I'd be glad to help

**Comment by bjorn** [comment]
@powertomato Thank you for looking into this problem! Since you can't reproduce this with a Visual Studio based build, maybe it is related to building with MinGW? The release is built with MinGW.

**Comment by Eggbertx** [comment]
Have there been any updates on this? I'm unable to get any command line output in windows, using the official release (1.7.2)

**Comment by idbrii** [comment]
For anyone stuck, try [this search](https://github.com/mapeditor/tiled/search?q=public+Tiled%3A%3AWritableMapFormat) to get a hint for the supported formats (plus any plugins you've installed).
