### ISSUE TITLE
Scripting: Error: Qt.include(): Can only be called from JavaScript files

### ISSUE THREAD

**Issue by RainingChain** [mapeditor/tiled#2749]
From a JavaScript file in the extension directory, I am trying to import another JavaScript file.

In my JS file, I tried using `Qt.include('file:/MyFile.js');` but it displays the error `Qt.include(): Can only be called from JavaScript files,` 

How can I import a JS file from a script?

**Comment by bjorn** [comment]
Hmm, I can't get this to work either. None of the [methods documented here](https://doc.qt.io/qt-5/qtqml-javascript-imports.html) appear to work. Maybe this only works as part of QML and not when using a `QQmlEngine` to execute some JavaScript code directly. Will need further investigation.

**Comment by bjorn** [comment]
Alright, `Qt.include` should not be used, but it will now be possible to use JavaScript's import/export when you write your extensions in .mjs files. :-)
