### ISSUE TITLE
More Status Bar info for Shape Fill Tool

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#2808]
**Current behavior:**
When using the Rectangular Select tool, the "drawn" actual size is shown in the status bar below. Like "Rectangle (23 x 19)". 

**Suggested additional behavior:**
When using the Shape Fill Tool, the "drawn" actual size is shown in the status bar with the same format. This could also work either for circle and rectangular shapes.

**Comment:**
I use this tool a lot and that would be very handy if also the size shows up there.

**Comment by bjorn** [comment]
This seemed like a small and useful thing to add, though as usual it was a bit more work than expected. :-)

Anyway, implemented now for the upcoming Tiled 1.5 release along with two other small improvements. Thanks for bringing it up!
