### ISSUE TITLE
Allow toggling visibility of other maps in the World

### ISSUE THREAD

**Issue by bjorn** [mapeditor/tiled#2859]
To quote eishiya from the [Tiled forum](https://discourse.mapeditor.org/t/quality-of-life-feature-suggestions/4619):

> Allow toggling visibility of other maps in the World. The dozens of other maps on the screen can be a distraction, especially when maps overlap. I’d like to add new maps to the World as soon as possible, but as it is, I have to leave it until I’ve mostly finished working on the map. When world visibility is Off, then the other maps should only be visible while using the World tool.

The other maps should still be loaded, just set to invisible. This is to make sure that toggling the visibility is a fast operation.

I like the idea to automatically make the other maps visible when selecting the World tool.

**Comment by BVS3** [comment]
This would be a very welcome feature.  Huge quality of life improvement
