### ISSUE TITLE
Make the background fade color customizable

### ISSUE THREAD

**Issue by bjorn** [mapeditor/tiled#2862]
To quote eishiya from the [Tiled forum](https://discourse.mapeditor.org/t/quality-of-life-feature-suggestions/4619):

> When highlighting a layer, have an option for a light colour as the fade colour. The dark default doesn’t work well with dark tiles, as they blend in.

Could probably be added alongside the grid color configuration.

**Comment by SchmidtWC** [comment]
Hello. I am a student who has been assigned with finding an open source project to contribute to. I was wondering if this issue was still open and if there was a chance I could try to contribute. Thank you!

**Comment by bjorn** [comment]
@SchmidtWC Yes, this could definitely be a good issue to look into. As mentioned, there is already an option in the preferences for setting the grid color, and an option to set the color of the dark rectangle could be added alongside. This color is should then be used here:

https://github.com/mapeditor/tiled/blob/27a04bd389986990e4a041186115b4e4c95637a6/src/tiled/mapitem.cpp#L172-L173

And of course it needs to be updated accordingly, when the color is changed in the preferences.

It might make sense to use the alpha value of the color as the "darkening factor", to make that also customizable. Though I'm not entirely sure about this due to the potential for users to get confused when they pick a color and leave alpha on 255 and then the "highlight current layer" seems entirely broken.

Let me know if you have any questions!

**Comment by SchmidtWC** [comment]
Sorry for not replying for a few days, but I will definitely take a look at this issue. Thank you for the quick response!

**Comment by SchmidtWC** [comment]
I have created a few functions in preferences.h to handle changing the background fade color, but I'm not quite sure how to connect it with the UI. I'm new to Qt and I'm having some difficulties searching through the large code base. I imagine I would need to alter preferencesDialogue.cpp in some way and preferencesDialogue.ui as well. ColorButton is obviously involved but I'm not sure if I need to do something to it or just connect it to the background fade color using Qt. I appreciate any help you can provide in this.

**Comment by bjorn** [comment]
@SchmidtWC Right, you'd edit `preferencesdialog.ui` in the "Design" mode in Qt Creator, where you can insert a Label and a Tool Button for this option, below the grid color related widgets. Then you'd need to right-click the new Tool Button and choose "Promote to > Tiled::ColorButton", so make it instantiate a ColorButton in its place. Then you can name this button something like "fadeColor" (right-click and "Change objectName..."). Then build Tiled and you'll see the "mUi->fadeColor" member being available in the `preferencesdialog.cpp`.

From there I think you can follow the existing code, let me know if you have further questions!

**Comment by SchmidtWC** [comment]
I have made a pull request for resolving this issue. I can't get the build to run on my PC though.

**Comment by bjorn** [comment]
@SchmidtWC Thanks! What problem are you encountering with getting the build to run?

**Comment by SchmidtWC** [comment]
Apparently I'm missing a file, QPlatformHeaders/QWindowsWindowFunction. The call is in mainwindow.cpp but it can't find the necessary file.

**Comment by bjorn** [comment]
@SchmidtWC Ah, are you compiling against Qt 6 on Windows? I'd suggest to either use Qt 5.15 for now, or to try commenting out these lines from `main.cpp`. I'm not sure what happened to this API in Qt 6.

**Comment by SchmidtWC** [comment]
Ah, that would likely be the reason. I'll see if I can get that fixed sometime this week.
