### ISSUE TITLE
Pasted tiles are inconstented with previously copied

### ISSUE THREAD

**Issue by gmorning** [mapeditor/tiled#2874]
When I copy-paste area on a hexagonal map, pasted area shape is different from original one. Please see attached level for reproducing issue

![how to reproduce](https://user-images.githubusercontent.com/681180/88377664-3ecc5600-cda8-11ea-9753-bfd495abb777.gif)

[copypaste.zip](https://github.com/bjorn/tiled/files/4971130/copypaste.zip)

**Comment by bjorn** [comment]
This issue is not fixed yet (as pointed out in https://github.com/mapeditor/tiled/pull/3105#issuecomment-884303903), so reopening for now.
