### ISSUE TITLE
Locked Layer setting not getting saved to JSON

### ISSUE THREAD

**Issue by phanxgames** [mapeditor/tiled#2877]
Hello there! 

I started using the JSON file format recently and noticed that the layers being locked is not being saved to the JSON data, so it is not persisting between opening the map files.
I realize this may not be intended behavior because the TMX file format did save the locked property per layer to the file data.

Keep up the awesome work. As you know, I love Tiled!

Thank you,
Phanx

**Comment by bjorn** [comment]
I waited way too long to get this fixed, but now your locked layers will finally persist! :-)
