### ISSUE TITLE
Bucket fill shift behaviour doesn't behave as documented

### ISSUE THREAD

**Issue by mitchcurtis** [mapeditor/tiled#2883]
https://doc.mapeditor.org/en/stable/manual/editing-tile-layers/#bucket-fill-tool says:

> When holding Shift, the tool fills the currently selected area regardless of its contents.

But when I tried this out, it doesn't behave as documented. Pressing and holding shift does nothing; it's the release that turns it into a "greedy" fill. Once the fill type changes, pressing and holding shift reverts it back to the original type of fill, while releasing switches it to the other type again.

Version 1.4.2 on a MacBook Pro.

**Comment by bjorn** [comment]
This is quite strange behavior. Must be some regression. Thanks for reporting it!

**Comment by bjorn** [comment]
Thanks for creating this issue, now I finally remembered to look into this!

**Comment by mitchcurtis** [comment]
Oh, modifiers in Qt... it's always difficult for me, especially auto-testing it.
