### ISSUE TITLE
When creating a new stamp based on tile selection, only the current layer is captured

### ISSUE THREAD

**Issue by bjorn** [mapeditor/tiled#2899]
It should capture all selected layers.

As seen on [phanxgames' stream](https://www.twitch.tv/phanxgames).

**Comment by seanmorris** [comment]
I'm seeing this issue too. Spent an hour checking the docs to see if I was doing something wrong.

**Comment by seanmorris** [comment]
I would have labeled this a bug, since the docs say:

> Ctrl + 1-9 - Store current tile stamp (similar to Ctrl + C)

**Comment by bjorn** [comment]
> I would have labeled this a bug

I can imagine it feels more like a bug, though from a programmer's perspective it was a missing feature. The code in question dated back to Tiled 0.13 and older, but multi-layer selection has only been supported since Tiled 1.2. But now it's finally updated! :-)

I've clarified the documentation a little.
