### ISSUE TITLE
Clicking "Flip Horizontally" sets "Vertical" property instead of "Horizontal"

### ISSUE THREAD

**Issue by aganm** [mapeditor/tiled#2943]
If I select a tile object and then click `Flip Horizontally`,

![image](https://user-images.githubusercontent.com/20380758/101267244-98646a00-3724-11eb-923c-55fab53686ad.png)

the `Vertical` property is set

![image](https://user-images.githubusercontent.com/20380758/101267204-415e9500-3724-11eb-867a-ba9ce88fee3d.png)

**Comment by aganm** [comment]
I was informed this isn't a bug. Vertical + 180 degrees

**Comment by bjorn** [comment]
While the behavior makes sense in some way, I guess it's pretty much a bug. But there's issue #1704 open about this.
