### ISSUE TITLE
Object references don't disappear when selected object is deleted

### ISSUE THREAD

**Issue by squishyu** [mapeditor/tiled#2944]
#### Steps to reproduce

- Add an "object" type property to another object
- Delete the referenced object

#### Expected behavior

- The reference arrow should disappear

#### What actually happened

- Arrow is still stuck there, even though the object no longer exists

#### Info

- Tiled version: 2020.11.25
- OS: Windows 10 Home 1803
![ezgif-5-10ebbd497793](https://user-images.githubusercontent.com/28161629/101267850-c7e39880-375d-11eb-884b-9bd171a57af3.gif)

**Comment by bjorn** [comment]
Thanks for the report! While I was fixing it I noticed another visibility updating issue that is now fixed as well (01247a85a24017e625231b1b4daf66bc2c9b7f77).
