### ISSUE TITLE
Allow for portable config file

### ISSUE THREAD

**Issue by anaanook** [mapeditor/tiled#2945]
This is more of a suggestion, I think it'd be useful to have tiled check for a portable/in folder config file. Asesprite has this solution, which is handy!  

> The program works in both [Portable and Not], depending if the configurations file aseprite.ini exists in the same folder where aseprite.exe is located.

> From Aseprite v1.0.2 the configuration is saved in the current user settings folder by default (i.e. %AppData%/Aseprite/aseprite.ini). Anyway, if you copy your aseprite.ini in the aseprite.exe folder, Aseprite detects that you want to carry your configuration with you, so the program acts like a portable app.

Seems like a simple enough change!

**Comment by bjorn** [comment]
Hmm, yeah that's definitely something worth supporting!

At least with the introduction of projects & sessions, a lot of options already moved to the session, but there's still some stuff stored in the registry and indeed if Tiled is on a USB stick it would be nice if you could carry those settings along with it as well.
