### ISSUE TITLE
Allow for extra extension directories

### ISSUE THREAD

**Issue by anaanook** [mapeditor/tiled#2946]
It'd be great to allow for secondary extension directories, as I'd like to keep those scripts managed with the rest of my project without having to copy them around.

**Comment by bjorn** [comment]
If you set up a Tiled project, you can place your project-specific extensions in an "extensions" directory alongside the `.tiled-project` file. If you want to place them somewhere else in your project, you can configure this directory via "Project > Project Properties...".

This project property is mentioned in the [documentation about projects](https://doc.mapeditor.org/en/stable/manual/projects/), but it would be good to also add it to the [scripting page](https://doc.mapeditor.org/en/stable/reference/scripting/).

**Comment by anaanook** [comment]
Ahh this is excellent, thank you!

**Comment by bjorn** [comment]
> This project property is mentioned in the [documentation about projects](https://doc.mapeditor.org/en/stable/manual/projects/), but it would be good to also add it to the [scripting page](https://doc.mapeditor.org/en/stable/reference/scripting/).

Seems I addressed this as part of 5298ebf5f43947a0b84a60c0798b9829579c3d3b, so closing this now. :-)
