### ISSUE TITLE
Option to remove whitespace from exports

### ISSUE THREAD

**Issue by KelvinShadewing** [mapeditor/tiled#2955]
I think it would really help out with large maps if exporting came with an option to remove whitespace (spaces and newlines) from exported files. I've found that doing so can reduce exported file size down to about 40%, depending on complexity, which would be a massive space saver for very large maps or ones with lots of layers and special objects put in that tend to be deeply nested. This issue is compounded by the fact that Tiled seems to be adding an inconsistent number of spaces per indent.

Some of the lines in my test files had multiple dozen spaces per line, particularly on lines where I was adding special properties to shape objects. not to mention polygon coordinates, which would end up with over 100 spaces just to put a coordinate pair and its respective braces on separate lines (four lines per coord, at least 25 spaces per line). This just seems really inefficient and wasteful, and the more complex a map gets, the more this issue snowballs. That's why I think an option should appear when exporting to include or exclude whitespace.

**Comment by bjorn** [comment]
Hey @KelvinShadewing, this option exists since Tiled 1.3:

![image](https://user-images.githubusercontent.com/531764/101880483-46dc3500-3b93-11eb-80f3-f0fb94565ff0.png)
