### ISSUE TITLE
Move tool crashes Tiled

### ISSUE THREAD

**Issue by squishyu** [mapeditor/tiled#2967]
#### Steps to reproduce

- Press [M] or select the Move tool in the top bar
- Since move tool gets selected when creating a new image layer, that causes the crash too

#### Expected behavior

- Being able to use the move tool

#### What actually happened

- Tiled crashes

#### Info

- Tiled version: 2020.12.17
- OS: Windows 10 Home 1803
![image](https://user-images.githubusercontent.com/28161629/102592257-81098180-4113-11eb-832c-43dd937b6295.png)

**Comment by bjorn** [comment]
Forgot to mention it in the submit message, but this bug was fixed by e45af88fdf02842ef5325d4e9cc08f290921c52b. Thanks for the quick report, @squishyu!
