### ISSUE TITLE
Save All isn't affected by "Repeat last export on save"

### ISSUE THREAD

**Issue by squishyu** [mapeditor/tiled#2969]
Since the project I'm currently working on requires me to sometimes modify several maps at once, I'd like to be able to use the "Save All" feature [CTRL+SHIFT+S]. It does not, however, export the maps when I have the "Repeat last export on save" option checked in my preferences. That makes me have to click through all of the modified maps while spamming CTRL+S.

I'd like "Save All" to also export the maps, if possible.

#### Info

- Tiled version: 2020.12.18
- OS: Windows 10 Home 1803

**Comment by bjorn** [comment]
Finally got around to this, thanks for the report! The fix will be released with Tiled 1.5.
