### ISSUE TITLE
Property format changed for exported JSON tilemaps

### ISSUE THREAD

**Issue by veleek** [mapeditor/tiled#2984]
I'm working with the Phaser game engine, and it currently has an issue loading tile properties because it's expecting the `properties`  object to be an object:

```
'properties': {
  'collides' : true
}
```

But the current version I'm using returns an array with extra type info:

```
'properties': [
  { 'name': 'collides', 'type': 'bool', value: true }
]
```

I've opened a bug to fix this in Phaser but I'm trying to determine whether this should be a hard switch to the new format, or whether we should use the map data version to decide which way to parse it.

I'm having a hard time determining which version of Tiled this change to the properties format was implemented.  Does anyone happen to know, or should I just use `version >= '1.4'` and call it good?

**Comment by veleek** [comment]
Phaser issue is here: https://github.com/photonstorm/phaser/pull/5523

**Comment by EJlol** [comment]
There is a TMX Changelog:
https://doc.mapeditor.org/en/stable/reference/tmx-changelog/

Tiled 0.16:
The <property> element gained a type attribute, storing the type of the value. Currently supported types are string (the default), int, float and bool.

Tiled 0.17:
Added color and file as possible values for the property.type attribute.
Added support for editing multi-line string properties, which are written out differently.

**Comment by bjorn** [comment]
Tiled provides an alternative "json1" plugin that can be enabled instead of the "json" plugin to still store JSON files in the pre-1.2 format. However, I'd really recommend moving on to the new format. If desired, or just for compatibility, it can be transformed to the old format after loading the JSON file.

See also #2148.

**Comment by veleek** [comment]
@bjorn - Yup, my request was just for information so that I can make the proper fix in phaser while still being backwards compatible with older Tiled versions.  Thanks for the reference!
