### ISSUE TITLE
WebP image support

### ISSUE THREAD

**Issue by gogoprog** [mapeditor/tiled#2986]
When adding tiles to a tileset, it seems there is no .webp support.

Tested in 1.4.3.

Could this be added?

**Comment by bjorn** [comment]
Which operating system? This could be a packaging issue.

**Comment by gogoprog** [comment]
ArchLinux  5.10.5-arch1-1

**Comment by bjorn** [comment]
Are you using the [`tiled` community package](https://archlinux.org/packages/community/x86_64/tiled/)? If so you can add .webp support to Tiled by installing `qt5-imageformats`, which is the package providing the necessary Qt plugin.

**Comment by gogoprog** [comment]
Yes I was using that one.

Thanks for the info, I'll take a look

**Comment by svenstaro** [comment]
I added the necessary optdepends.

**Comment by bjorn** [comment]
Thanks a lot, @svenstaro!
