### ISSUE TITLE
Tiled crashes if scripts are reloaded while a script modal window is open

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#2991]
If Tiled tries to reload scripts while a script modal window (`tiled.alert()`, `tiled.prompt()`, `tiled.confirm()`) is open, Tiled will crash as soon as that window is closed (via OK or the close button).

I am using Tiled version 1.4.3 on Windows 10 x64.

Steps to reproduce:
1. Load a script that opens a window with `tiled.alert()`, `tiled.prompt()`, or `tiled.confirm()` Here's a small example of such a script, it puts a "Show an Alert" action at the bottom of the Edit menu.
```javascript
var action = tiled.registerAction("showAlert", function(action) {
	tiled.alert("Here's an alert! If you modify any script and tab back to Tiled (causing it to reload scripts) while this alert is up, Tiled will crash.");
	
});

action.text = "Show an Alert";
tiled.extendMenu("Edit", [
    { action: "showAlert" }
]);
```
2. Run the script and wait until a modal window pops up. Do not close the window yet.
3. Modify *any* script in any way. It can be this script, or any other script you have.
4. Go back into Tiled, and close the modal window by clicking OK, Yes/No, or closing it with the close button.
5. Tiled will not respond for a bit, and then crash.

Expected behaviour: The script should finish normally after the modal window is closed, and *then* reload the scripts.

I'm guessing it's something to do with the JavaScript context being recreated or reinitialized when scripts are reloaded, but the modal window tries to return to the old, now-destroyed context.
Modal windows opened by Tiled itself (e.g. the Preferences window, New Map window) do not cause any such crashes.

I did some additional testing using variants of this script, which prints 20000 numbers to the console (something that generally takes a while):
```javascript
var action = tiled.registerAction("showAlert", function(action) {
	for(var i = 0; i < 20000; i++)
		console.log(i);
});

action.text = "Show an Alert";
tiled.extendMenu("Edit", [
    { action: "showAlert" }
]);
```
The script above will cause no issues, even if it or another script is modified mid-execution.
Adding an `tile.alert("Done!")` after the loop seems to be a crapshoot. Reloading scripts during the printing but before the alert popped up caused it to crash most but not all of the time - the script finished fine *once*.

**Comment by eishiya** [comment]
Ran into this bug again today, in a slightly different way: trying to access an invalid tile ID in a tileset from a script pops up an error modal even if the script doesn't, and that modal will *also* cause a similar crash if scripts reload while it's open. Seems like this bug might affect all modals that pop up during a script's execution, not just ones called directly by the script.

**Comment by bjorn** [comment]
> Seems like this bug might affect all modals that pop up during a script's execution, not just ones called directly by the script.

Indeed it would, however I'm not sure what you mean by "trying to access an invalid tile ID in a tileset from a script pops up an error modal". At least when calling `Tileset.tile`, the error should just get written to the Console and appears in the Issues view, not a modal dialog.

The fix I pushed only covers `tiled.alert`, `tiled.prompt` and `tiled.confirm` for now, because I couldn't find a more generic approach to finding out whether there is a script currently executing (which is quite annoying, I think `QJSEngine` could have a method for this...). I also couldn't find a way to find out whether the currently active event loop is the one from the `QCoreApplication`, which would be another option.

**Comment by eishiya** [comment]
> I'm not sure what you mean by "trying to access an invalid tile ID in a tileset from a script pops up an error modal".

This may have been a mistake/poor memory on my part as I also couldn't reproduce it afterwards.

Thanks for this fix! I use a lot of alerts and prompts in my scripts, so accidental crashes were pretty common when debugging. Hopefully not anymore :D!
