### ISSUE TITLE
'Save as Image size is wrong

### ISSUE THREAD

**Issue by legendJD** [mapeditor/tiled#2992]
I make my map size 20 tiles high and 18 tiles wide with 8x8 tile size which says its 160 X 144 pixels. But when i save as an image the images size is like 900x800

**Comment by legendJD** [comment]
Figured it out it's cause when you chose 'Export as Image' 'use current zoom level' was checked

**Comment by bjorn** [comment]
> Figured it out it's cause when you chose 'Export as Image' 'use current zoom level' was checked

This will default to off starting with Tiled 1.5. :-)
