### ISSUE TITLE
Documentation is out of date compared to master?

### ISSUE THREAD

**Issue by sausagejohnson** [mapeditor/tiled#2995]
https://github.com/mapeditor/tiled/blob/master/docs/reference/support-for-tmx-maps.rst

Noticing the Orx reference is correct but it is the old one  in the online documentation at:

https://doc.mapeditor.org/en/stable/reference/support-for-tmx-maps/

Clicking the "Edit on Github" button take me to this old commit/branch: https://github.com/mapeditor/tiled/blob/55175d1930b98087672a2f83ac9f30ddb8fed2c4/docs/reference/support-for-tmx-maps.rst

**Comment by bjorn** [comment]
Thanks for reporting this! So actually, the `stable` docs refer to the latest tagged release, whereas master branch is hosted as `latest`:

https://doc.mapeditor.org/en/latest/reference/support-for-tmx-maps/

This page probably shouldn't be in the manual. The long-term plan is to move it to https://www.mapeditor.org/libraries. For now, the fixed link will be on `stable` as soon as I tag Tiled 1.5, which should not be far off.
