### ISSUE TITLE
Selection tool selects objects that are out of the selection rectangle

### ISSUE THREAD

**Issue by thomasgoldstein** [mapeditor/tiled#2999]
Screenshot:

![image](https://user-images.githubusercontent.com/531764/111073733-0ff22400-84e0-11eb-8922-f3df86c2e5d5.png)

Let me know if you need more details. Thank you.

**Comment by bjorn** [comment]
This was related to the 550% zoom, which also applied to a margin that is only there to avoid rendering artifacts. Now the interaction shape no longer has this margin. Thanks for the report!
