### ISSUE TITLE
Write --export-formats to stdout instead of stdin

### ISSUE THREAD

**Issue by ISSOtm** [mapeditor/tiled#3002]
From a Makefile, I want to check if a custom export format was provided (via a custom plugin, so this checks that the plugin is installed and functions correctly).

To do this, I wrote `if ! tiled --export-formats | grep -q gb-open-world; then echo "Export format not supported, is the plugin installed?"; exit 1; fi`. However, `tiled` prints to `stderr`, not `stdout`, so this doesn't work. (Rationale for this check: `tiled` will simply print "Format not recognized (see --export-formats)", but I want to additionally hint as to what the solution likely is.)

One may suggest `tiled --export formats 2>&1 | grep (...)` instead, but this causes several problems:
- Other information gets written to `stderr`; case in point, I get the following:
  ```console
  % tiled--export-formats >/dev/null
  QApplication: invalid style override 'gtk' passed, ignoring it.
  	Available styles: Windows, Fusion
  Map export formats:
   csv
   gmx
   js
   json
   lua
   tmx
  Tileset export formats:
   json
   lua
   tsx
  ```
  If a warning or error containing the string `gb-open-world` (e.g. because it's the project's name, so it's likely to be a component of the CWD), then the `grep` would incorrectly pass, and the user would be puzzled as to why they get a different error.
- This swallows error output, so if `tiled` encounters an error for whatever reason, the user won't see it.

I agree it may be a bad idea to rely on `grep`ping the output of `tiled --export-formats`, and switching to `stdout` would break any workflows currently doing `2>&1` (if there are any). Thus, I'm open to suggestions of alternative ways to check if a given output format is supported.

**Comment by bjorn** [comment]
Good idea! I think the only reason I hadn't done it before is because Qt does not provide a really convenient way to write to stdout by default, even `qInfo` still prints to stderr since it's meant for debugging. But it turned out to be quite trivial to do anyway.
