### ISSUE TITLE
GlazeJS Typescript game engine supports TMX format

### ISSUE THREAD

**Issue by rjewson** [mapeditor/tiled#3012]
Hi,

I recently restarted https://github.com/rjewson/glazejs

It supports the TMX format, rendering tile layers on the GPU via WebGL - its fast!, the demo (https://rjewson.github.io/glazejs/) has 3 tile layers.  

It supports flipping/rotation, you can have 64 tile sheets of 256*256 pixels attached to each layer.
It even supports multiple realtime lights.  
I will be working to update to the new 1.5 features, then adding some pre-processing tools to quickly add the right assets.

Please add to the wiki!

Regards
Richard

**Comment by DrSensor** [comment]
That's quite interesting engine!
May I know under what license the glazeJS is?

**Comment by bjorn** [comment]
I'm also interested to know which license this falls under. The demo looks great!

The HTML5 section could probably use some cleanup, but for now I've just added glazeJS to the list. Thanks!

**Comment by rjewson** [comment]
Thanks, I need to choose one will let you know, there is still some work to be done to make it usable.
