### ISSUE TITLE
[query] Examples location on Debian/Ubuntu?

### ISSUE THREAD

**Issue by lofidevops** [mapeditor/tiled#3013]
I'm following along with https://doc.mapeditor.org/en/stable/manual/introduction/ and got to the hint to try the `tmw_desert_spacing.png` tileset from the examples shipping with Tiled. If I've installed from apt on a Debian/Ubuntu system, where should I find these?

**Comment by bjorn** [comment]
According to https://packages.ubuntu.com/groovy/amd64/tiled/filelist they are at `/usr/share/doc/tiled/examples`.
