### ISSUE TITLE
New behavior: Rectangle selects only Objects which are fully "encased" by Rectangle.

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#3023]
**As Is:**

![image](https://user-images.githubusercontent.com/531764/113692110-7c220b00-96cd-11eb-9fef-b9d0992af231.png)
 
See screenshot above: When selecting with the Rectangle tool, not only the Objects within the Rectangle are selected, but also all other Objects are selected which are touched by the Rectangle by only a tiny bit (e.g. those chairs around the table in this top-down screenshot). 

This behavior is (in my opinion) very counter-intuitive because major software like PowerPoint and other image software work differently, like described below.

**To Be:**
When selecting with Rectangle tool, only Objects which are completely WITHIN the Rectangle are selected. Objects touched but not "encased" by the selection will be ignored.

**Suggestions:**
I would recommend this new behavior as default. Maybe this can be changed in the Options back to the old behavior? Alternatively, a hotkey could be held to activate the old behavior while selecting. But I think that's not worth occupying a hotkey. I'm looking forward for feedback who would be interested in this new (or old) behavior.

**Comment by bjorn** [comment]
@UliAbo Thanks for the detailed issue! Indeed I've just tested with Inkscape and it also selects only objects within the selection box, though it provides a "touch" mode when pressing Alt, though not with a rectangle but based on a freehand line.

While doing "touch" based selection with a freehand line would be a great feature to also have in Tiled, a first improvement we could try is to make Alt toggle to the current behavior, while making the "drag around" behavior the default as you suggested.

**Comment by UliAbo** [comment]
Thanks Bjorn for the quick reply. 

That sounds like a great idea for implementation. So we would have both benefits.

This feature would greatly improve my productivity as I'm selecting a lot of stuff (although I'm "only" making a hobby game project).

**Comment by eishiya** [comment]
As a counterpoint: While Inkscape might have "contains" as the default mode, in Adobe Illustrator, "touch" is not only the default mode, but appears to be the *only* mode. I also think "touch" is more intuitive in general, and makes it easier to make precise selections.

I vote to add the new "contains" mode, but keep "touch" as the default. As a bonus, it avoids changing default behaviour, which means people don't have to get used to a new thing. (Still glaring at the new Terrain brush default size xP)

**Comment by bjorn** [comment]
So, a WIP change for this was pushed to `wip/selection-behavior` and builds with this change can be downloaded at https://github.com/mapeditor/tiled/actions/runs/756062082.

Currently it switches with Alt modifier, but this is likely going to be replaced by buttons on the tool bar.

**Comment by bjorn** [comment]
This is now a toggle on the tool bar for the Object Selection Tool:

![image](https://user-images.githubusercontent.com/531764/115368858-ca540580-a1c7-11eb-9c8e-5313f20e8bb4.png)

The Alt key can be used to temporarily switch between these modes, whereas clicking either button on the tool bar will persistently make the respective mode the default.

The initial default remains selecting by intersection.

**Comment by UliAbo** [comment]
Great, thanks for the implementation, @bjorn ! I am looking forward to trying it out, soon.

**Comment by eishiya** [comment]
Best of both worlds :D Thank you!
