### ISSUE TITLE
JSON format – version exported as float

### ISSUE THREAD

**Issue by Natureshadow** [mapeditor/tiled#3033]
In the JSON format, Tiled stores the `version` key as a float (`1.4` in my case). Normally, version numbers, let alone semantic versions, are not regular floats, so storing as string seems more appropriate.

I stumbled over this in a scenario where float values in JSON data are not allowed.

If the flaot type is intentional, I will work around it, but I am quite convinced it is an accident.

**Comment by bjorn** [comment]
I don't remember if it was an accident or simply a bad idea, but changing it could break compatibility for any existing code. On the other hand, you're right that with this number being a float, we'll get into trouble once the format reaches version "1.10", so we need to change it anyway.

> I stumbled over this in a scenario where float values in JSON data are not allowed.

I'm curious, what kind of scenario is that? Is there an integer-only JSON for embedded use?

**Comment by bjorn** [comment]
> I am developing a widget ("add-on") for Matrix/Element that allows playing tile map games in Matrix chat rooms: https://edugit.org/auglement/augmentile

Woah, that sounds amazing! I'm interested to hear when I can try it out somewhere. :-)

> In any case, thanks for considering this so quickly!

No problem! Let me know when there's anything else I can do to help.
