### ISSUE TITLE
Files added to newly created projects don't show in project folders until restart/reload.

### ISSUE THREAD

**Issue by fmoo** [mapeditor/tiled#3035]
Tiled Version: 1.6.0

When creating a new project in some ways, new files will not get added to the project without a manual refresh or restart of Tiled.

Steps to Reproduce:
1. Project > Close Project
2. Project > Save Project As ...
3. Project > Add folder to Project ...
4. File > New > ....  (save it inside the added folder)

Upon saving the new tileset or map, the new file will not appear in the project folder, unless manually selecting Project > Refresh Folders.

Auto-refresh is fixable by either a restart of tiled or going through Project > Recents > (the current project).

**Comment by bjorn** [comment]
A bit of a silly mistake, this one. Thanks for reporting it!
