### ISSUE TITLE
Build failure with 1.6.0

### ISSUE THREAD

**Issue by jubalh** [mapeditor/tiled#3037]
With gcc10 I get for tiled 1.6.0:
`main.cpp:334:33: error no match for 'operator<<' (operand types are 'QTextStream' and '<unresolved overloaded function type>'`.F

full build log: https://paste.opensuse.org/view/raw/93048173

**Comment by bjorn** [comment]
Which Qt version are you using? This seems to be a problem with the `endl`, but I've got this code earlier in the file:
```c++
#if QT_VERSION >= QT_VERSION_CHECK(5,14,0)
using Qt::endl;
#endif
```
I've pushed a potential fix as 7059846dc551a5d6b3cda8c78aa990aff8a4861f, but will have to see how the CI builds like that. If it works I can remove the `using` directive.

**Comment by jubalh** [comment]
Qt 5.15.2.
With the commit you mentioned it builds fine! Thanks!

**Comment by bjorn** [comment]
Unfortunately the Qt 5.6 and 5.12 builds don't like this change, so it'll need to look a bit different. I'll figure something out. :-)

**Comment by jubalh** [comment]
Works! Thank you!
