### ISSUE TITLE
Parallax view / start position

### ISSUE THREAD

**Issue by SasikaAT** [mapeditor/tiled#3043]
First of all, I love the new parallax feature. Not even the two game engines that I use have this integrated into the level editor. The problem I have is that you can't really see which section of the picture the player will see later. Just estimate. So a "ingame view" would be helpful here.

The second problem I see is that my own parallax formula works differently than Tiled's. Since the game engine that I use does not have a parallax preview, I place the individual layers (endlessly horizontal loopable images) in the level so that they look good at floor height. For the parallax shift, I then use the camera position relative to its starting position (which is at floor height, but the floor height can be different in each level) multiplied with the parallax factor.

I could now adapt the formula so that it uses the same as Tiled, but that means that I would then have to place the individual layers with the parallax view activated pixel-precisely. For this I would again need the ingame view that I would move to the start position and place the layers at that place.

When I design the parallax layers, I do it in the painting program in such a way that I draw them with the camera at floor level so that I can then simply place them on top of each other at exactly the same coordinate later. This saves a lot of time compared to manual pixel-perfect placement in each level. But for that I would have to be able to define the starting position of the camera in Tiled so I can continue placing the layer simply on top of each other.

Hope it was understandable :)

**Comment by bjorn** [comment]
> So a "ingame view" would be helpful here.

Definitely! This is covered by #2962.

Regarding the floor height, you're right, I think we need a "Parallax Origin" property, which currently essentially defaults to "0, 0" but which you could put at "view width / 2, view height / 2" or whatever makes it match your floor height. Does that sound like what you're after and do you think it's a intuitive name?

Apart from the parallax origin, there's the reference point in the view, which is currently always the center of the view. When the parallax origin (currently 0,0) matches up with the center of the view, the parallax offset of all layers is 0. Do you think there's a reason to also make the reference point in the view configurable?

**Comment by SasikaAT** [comment]
> Does that sound like what you're after and do you think it's a intuitive name?
Not sure if we understand the same under parallax origin but I think it would help. If I understand it correctly, you could use this origin to compensate for both the reference point within the view (in my case it is top-left) and the starting position of the camera. As far as an intuitive name is concerned, I can't think of a better name. 

> Do you think there's a reason to also make the reference point in the view configurable?
I suspect you can also use the "Parallax Origin" mentioned above for this. But if you have the extra ingame view, I think it would be nice to also make its origin point adaptable so that it matches the reference point in the engine. Then you only need to type in the start coordinate of the camera for the parallax origin and do not have to subtract half the width and height of the view to calculate the parallax origin.
