### ISSUE TITLE
Custom Tool Icon not working

### ISSUE THREAD

**Issue by MrMasterplan** [mapeditor/tiled#3048]
Let's track this a its own issue.
Using the `tiled.registerTool()` with a custom icon does not show the icon. There is an effect of setting the value: The text label is replaced by a blank gray button. If the image file does not exist, the text label reappears.

**Comment by MrMasterplan** [comment]
Complete test case just to make it super clear what I mean: https://github.com/MrMasterplan/TestCaseForTiledIssue3048

**Comment by bjorn** [comment]
Problem was caused by explicitly using the "ext:" prefix.

I realize it might be intuitive to do so, but the code was already adding it automatically. Now it only does that when the prefix isn't already there, so both cases work.
