### ISSUE TITLE
Feature request: Scripting support for embedded tilesets

### ISSUE THREAD

**Issue by mrmasterplan** [mapeditor/tiled#3055]
I would like to embed tilesets in a level from a scripted map format. Today I see nothing about embedding in the scripting documentation.

Currently, to unpack a binary level with reference to my tilesets, I have to open the tilesets in the background before I can open a level. The Tilesets have to remain open as long as I am working with the level. If I could embed the tilesets on opening the level, these background tabs could be closed.

In my case the tileset will never change since it comes from a published game. Right now, all the tilesets have to be opened in the background whenever working with my custom map format.
Also, since I open the backgound tabs using an `ext:` path, Tiled cannot find that path when it tries to re-open the tilesets next time I start the program.

**Comment by bjorn** [comment]
> Currently, to unpack a binary level with reference to my tilesets, I have to open the tilesets in the background before I can open a level. The Tilesets have to remain open as long as I am working with the level. If I could embed the tilesets on opening the level, these background tabs could be closed.

Hmm, if you add the tilesets to the loaded map using [`TileMap.addTileset`](https://www.mapeditor.org/docs/scripting/classes/tilemap.html#addtileset) then you should not need to keep them open as tabs. Is that an option?

That said, for each map in your custom format that you open, you'll want to reuse the same tileset instance and currently the API support for this is missing. Could it be an option in you case, to use shared global variable that keeps references to the loaded tilesets, such that when loading a map the tileset reference can be taken from there and added to the map?

> Also, since I open the backgound tabs using an `ext:` path, Tiled cannot find that path when it tries to re-open the tilesets next time I start the program.

Hmm, the scripts are initialized before the previously open files are loaded, so why would this not work? Though I guess this would be solved anyway if you don't need the tilesets to be open in background tabs.

**Comment by MrMasterplan** [comment]
> Hmm, if you add the tilesets to the loaded map using TileMap.addTileset then you should not need to keep them open as tabs. Is that an option?

That works much better!! I had to get the tileset handle back from the TileMap.tilesets after I closed it with tiled.close() but that's ok. This completely solves this use-case for me.

Thank you so much for your continued feedback and support!!

**Comment by mrmasterplan** [comment]
From my point of view you can close this issue. Your suggestion fully solved my use case.

**Comment by bjorn** [comment]
Yeah, let's close this then. We'll should come back later to an alternative to `tiled.open` that doesn't actually open the file in a tab, though.
