### ISSUE TITLE
Tile class in scripting is missing access to flipping information

### ISSUE THREAD

**Issue by mrmasterplan** [mapeditor/tiled#3063]
As it says in the title.

The Tile class in the js scripting interface defines the flags that will be available for the different flipping operations, but flags active on the current tile are not exposed.

It would be nice to be able to both set and read the flipping flags.

Definition of Tile class:
https://github.com/mapeditor/tiled/blob/6ad9e7136fedc80940819ab44a7b55bffa6b8beb/docs/scripting-doc/index.d.ts#L1332

**Comment by bjorn** [comment]
The `Tile` class actually doesn't store flipping information, given that a single tile can be flipped various ways in different places where it is used. Maybe it's confusing that it does still hold the definitions of the flags, but I'm not sure what would be a better place.

There's two ways to get at the flipping flags in the JS API:

* `TileLayer.cellAt`, which returns `cell` object which has boolean properties for each flag.
* `TileLayer.flagsAt`, which returns a number that can be used with the flags defined on the `Tile` object to extract flag information.

**Comment by mrmasterplan** [comment]
That makes sense actually. Thank you for the clarification. And sorry for the Issue, I could have found that myself.
