### ISSUE TITLE
add scaling image option to an image layer

### ISSUE THREAD

**Issue by mokalux** [mapeditor/tiled#3065]
Proposal: as per the title, the option to scale an image in an image layer would be quite handy in some cases.

Thank you :-)

**Comment by bjorn** [comment]
I'd suggest to use a tile object instead in this case. Just put your image in an image collection tileset (should be easier than setting up an image-based tileset with a single tile, and allows easily adding more images). Then you can place the image as an object and scale it as needed.

**Comment by mokalux** [comment]
thank you very much, that did the trick :-)

I am closing the issue.
