### ISSUE TITLE
Letter 'l' not rendering in Tiled in Windows 10

### ISSUE THREAD

**Issue by Larkenx** [mapeditor/tiled#3066]
![image](https://user-images.githubusercontent.com/12945799/118600310-d3140900-b77e-11eb-9edc-50a11689af2d.png)

I'm guessing this is a QT framework issue?

**Comment by bjorn** [comment]
> I'm guessing this is a QT framework issue?

Well, I'm at least pretty sure this is not an issue in Tiled, but beyond that it could be an issue at any level. I guess you've only seen this problem in Tiled so far? Did you try any other Qt-based applications, for example Krita?

**Comment by Larkenx** [comment]
![image](https://user-images.githubusercontent.com/12945799/119409851-ef033780-bcb5-11eb-9dbd-2dbdc4fbb59e.png)

Looks like Krita doesn't have the same issue

**Comment by bjorn** [comment]
Hmm, could you look at the shipped Qt DLLs to see if it might be a different version than Tiled uses? Tiled releases are currently based on Qt 5.15.2.

**Comment by bjorn** [comment]
Another thing that would be interesting to know, if you're still running into this issue, is whether it helps to switch to the "Native" style in the Preferences (under "Theme"), instead of "Tiled Fusion".
