### ISSUE TITLE
how to open

### ISSUE THREAD

**Issue by 24wuw** [mapeditor/tiled#3072]
can someone tell me exactly how to install tile from this repo? (windows 10) 
im big computer nub, dont understand directions in readme.md

**Comment by bjorn** [comment]
> can someone tell me exactly how to install tile from this repo? (windows 10)
> im big computer nub, dont understand directions in readme.md

Those directions are meant for people who want to compile Tiled themselves. To download Tiled for Windows 10, go to either https://thorbjorn.itch.io/tiled or https://github.com/mapeditor/tiled/releases.
