### ISSUE TITLE
Rearrange Tiles tool causes tiles to be arranged in a single row

### ISSUE THREAD

**Issue by Lobachevskiy** [mapeditor/tiled#3076]
Steps to reproduce:
1. Select Rearrange Tiles tool
2. Enable Dynamically Wrapped Tiles
2. Create a new tileset (mine was from a collection of images)
3. Add enough tiles so that their combined width exceeds screen width

Expected: tiles are wrapped into multiple rows, fitting nicely on the screen
Actual: tiles are in a single row with horizontal scrolling being necessary to view them all

When switching to another tool (like Terrain Sets), the issue is fixed, and remains that way even when switching back to Rearrange Tiles.

**Comment by bjorn** [comment]
Doesn't look like this bug had anything to do with the rearrange tool, but it would mostly show up when adding tiles to an empty collection. Should be fixed now in any case, thanks for the report!
