### ISSUE TITLE
JSON export does not use parallax offsets

### ISSUE THREAD

**Issue by miss-programgamer** [mapeditor/tiled#3077]
When exporting a map to JSON format, the parallax offsets are not written to the file, making it impossible to retrieve them.

Steps to reproduce:
- Create a map and save it somewhere
- Add a tile layer (possibly any kind of layer?) and change its parallax offsets to something other than 1
- Export the map as a JSON file
- Examine the exported file, parallaxx and parallaxy will be missing from that layer

Expected:
Parallax offsets would be present in the exported file's layers, as long as they are set to a value other than 1

Actual:
Parallax offsets are always missing, even when they are set to a value other than 1

My Tiled version is 1.7, although this issue was present in 1.6 as well. I'm using the Windows build of Tiled on Windows 10.

**Comment by bjorn** [comment]
Forgotten to add the parallax offset to `Layer::initializeClone`. :-(

Thanks for the report!

**Comment by bjorn** [comment]
As a workaround, you can disable all export options, or if that's not an option, you can download a build from https://github.com/mapeditor/tiled/actions/runs/918612477 when they're done, which will contain the above fix.

**Comment by miss-programgamer** [comment]
Wow, that was fast! Thanks a bunch for so quickly addressing the issue!

**Comment by mold-boy** [comment]
3 years later the bug still exists. :( tmj/tsj files do not have the x/y offsets.
