### ISSUE TITLE
Snap object to tile

### ISSUE THREAD

**Issue by HoraK-FDF** [mapeditor/tiled#3087]
I had to correct many maps were the object was dragged by hand and had fractional numbers in it like 800.33 that caused the map converting script to break with an error and i had to hover every object look at its tile and calculate tile_x*32 and tile_y*32 and change them in the object properties at the end that was around 100 objects that i had to correct. Then i thought a checkbox in the properties dialog would be nice that snaps the objects upper left to the tile upper left that is nearest.

**Comment by bjorn** [comment]
> Then i thought a checkbox in the properties dialog would be nice that snaps the objects upper left to the tile upper left that is nearest.

It's not in the Properties dialog, but there's an option to snap objects to the tile grid or to pixels in the View menu:

![image](https://user-images.githubusercontent.com/531764/123636832-9cb9b700-d81d-11eb-89a9-021754b4a2ef.png)

> i had to hover every object look at its tile and calculate tile_x_32 and tile_y_32 and change them in the object properties at the end that was around 100 objects that i had to correct

If you need to round the position of many existing objects, you could use the [scripting API](https://www.mapeditor.org/docs/scripting/) to iterate over them. Of course the question is whether writing the script would have been faster than manually adjusting 100 objects, but it would pay off if you ever needed to do it again.

> had fractional numbers in it like 800.33 that caused the map converting script to break with an error

Which map converting script is this about, btw? Potentially it would also be an option to improve the script to do the snapping?

**Comment by HoraK-FDF** [comment]
https://github.com/themanaworld/tmw-tools/blob/a5d6818c8e4f68d9b7dd6272754a781c90be3f8a/tmx_converter.py

i think its hard to know for the script what to do, for warps it would be ok if it does it by its own since they are always centered on a tile but for some other particle effects objects that need pixel based positioning it would not, that must be done in the editor by hand (or script must round if its under .50 cut off fractional part if its greater or equal add 1 and cut off fraction). thank for showing me this the snap to grid/pixel helps me to fix that fast.

**Comment by bjorn** [comment]
Right, so in this case, I think the problem is that the script fails on floating point numbers for object position and size, which is wrong because the TMX format defines all these values to be float. It just so happens that when it's a round number, the exporter will not write a fractional part.

So I think the fix is to do either `float(attr[u'x'])` in case you can just make it work with floating point, or `int(round(float(attr[u'x'])))` (where the `int(...)` part is only required when using Python 2) in case you really need whole numbers.
