### ISSUE TITLE
Opacity not saved in .json

### ISSUE THREAD

**Issue by willianholtz** [mapeditor/tiled#3093]
When exporting to .json file, map opacity is not saved.

![01](https://user-images.githubusercontent.com/23488207/124212311-24751f00-dac5-11eb-88ea-668a9386b42b.png)
![02](https://user-images.githubusercontent.com/23488207/124212314-25a64c00-dac5-11eb-8f57-b65e20b9152c.png)

OS: Arch Linux
gdevelop + tiled (latest version of both)

**Comment by bjorn** [comment]
Hmm, opacity seems to get saved fine when I export to JSON. Could it be that GDevelop does not support this property yet? I think @blurymind is working on that.

**Comment by willianholtz** [comment]
hmm, that could be it, he even said he was having problems with some situations. I didn't know it could be something related to gDevelop!

**Comment by blurymind** [comment]
Pixi-tilemap didn't support layer opacity at all. I only recently added.
Unfortunately gdevelop is still using the older version. I am trying to
upgrade it now

**Comment by bjorn** [comment]
That's great, @blurymind! I'll close this issue since it is outside the scope of Tiled.
