### ISSUE TITLE
Bug (?) in v1.7: Selecting several Tiles in Tileset gets in conflict with picking multiple placed Tiles. 

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#3095]
## Reproducing Bug:

1. Select several Tiles in the Tileset with (important!) selecting some of them by dragging and then additionally some with CTRL. Here in this example the Tiles Red, Blue and Yellow have been selected with holding down LMB in the Tileset. The Tiles Green and White have been added (!) by holding down CTRL and selecting then Green and White.

![image](https://user-images.githubusercontent.com/1249266/124365869-3f719b80-dc4b-11eb-889e-f148235c7d84.png)

2. Hover now with this selection over your Map with the Stamp Brush tool and then RMB for picking some already placed Tiles. 

3. Bug: Instead of switching to only the picked Tiles, they are added to the selection. This is not the case when you avoid adding Tiles to the selection in the Tileset with CTRL.

**Comment by bjorn** [comment]
Hadn't noticed this before since indeed it seems the bug is only triggered after using Ctrl to select a few more tiles. I hope the change doesn't introduce another issue, but it seemed to work. Thanks for the report! :-)

**Comment by UliAbo** [comment]
Thanks for the quick fix, Bjorn!
