### ISSUE TITLE
Access Wang Colors from scripts

### ISSUE THREAD

**Issue by bendmorris** [mapeditor/tiled#3110]
I'm using a custom JS map exporter which infers map attributes from each tile's terrain information. Currently I can access the wang ID for a given tile as color indices, but can't look up the name, properties, or color value of the wang color at that index. It looks like the WangSet type is exposed to JS but the WangColor type is not.

Edit to add: just want to give a shoutout - I've been using the scripting features of Tiled since the Python days, and holy cow have they come a long way. The experience developing plugins in Typescript now is fantastic. Thanks for all the great work!

**Comment by bjorn** [comment]
First of all, it's great to hear you appreciate the scripting features!

Regarding the missing API for Wang colors, it's something I was aware of but I didn't want it to hold up the 1.5 release. There is issue #2663 open about it, but so far nobody had missed it. I'll make sure to have a look at adding this soon.
