### ISSUE TITLE
Incorrect preview position with inhereted parallax values

### ISSUE THREAD

**Issue by LilithSilver** [mapeditor/tiled#3124]
## Summary

* The parallax preview doesn't produce the correct "effective" parallax factor when group parallax inheritance is involved.
* The UI selection box and object name is, however, in the proper position.
* Tiled 1.7.2, Windows 10 x64

## Overview

The docs state:
> When the parallax scrolling factor is set on a group layer, it applies to all its child layers. The effective parallax scrolling factor of a layer is determined by multiplying the parallax scrolling factor by the scrolling factors of all parent layers.

However, I'm getting incorrect preview behavior, as demonstrated in this screenshot:

![image](https://user-images.githubusercontent.com/84940819/131325320-e6dfbfde-9950-4d3e-86a3-f82241ba0b1d.png)

_Camera at X = 0_

![image](https://user-images.githubusercontent.com/84940819/131324681-eb9d5254-ab8c-4386-be0d-a5ea50fbea41.png)

_Camera at X = 4_

The camera is translated to the right by four tiles, so the 1 tile moves 4 tiles, the 0.5 tile moves 2 tiles, and the 0.25 tile moves 3 tiles. However, I would expect the 0.5*0.5 tile (a group set to 0.5, with an image layer within set to 0.5) to look like the 0.25 tile, but it actually looks like the -0.25 tile!

It seems, however, that the hover UI selection and name behaves correctly, and is offset from the real thing:
![image](https://user-images.githubusercontent.com/84940819/131325575-dc434b36-0139-41cd-bf15-3f869d82a4f3.png)

## Reproduction

Here is a file containing the screenshotted test, as well as several other tests (demonstrating the incorrect behavior with parallax values above 1, in 0 to 1, in -1 to 0, and below -1):

[test_parallax.zip](https://github.com/mapeditor/tiled/files/7075996/test_parallax.zip)

This file _doesn't_ test mismatched group/layer parallax values (one at 0.8 and another at 0.5, for example), or the behavior of more than one level of inheritance.

**Comment by bjorn** [comment]
Thanks for the detailed report, attaching a testing map and the help with fixing this!
