### ISSUE TITLE
Change tilesets visibility based on selected layer

### ISSUE THREAD

**Issue by Luis-Tavares** [mapeditor/tiled#3127]
I'm missing a feature of changing the visibility of tilesets based on the selected layer. It would be a lot helpful to avoid adding assets on the wrong layers.
For example, the "furniture" tileset becomes visible when I select an "objects" layer and hidden when I select the "floor" layer.

**Comment by bjorn** [comment]
I'll consider this a duplicate of #153. I realize it's an old issue, but there are multiple reasons for implementing this (framework limitations, performance and convenience) so it would be good to have a look into this. Feel free to add to the discussion there if you have any thoughts on how this could be implemented.
