### ISSUE TITLE
Ukrainian language not showing up in the list of languages

### ISSUE THREAD

**Issue by Leonidius20** [mapeditor/tiled#3132]
Hello!
I have noticed that there is a file with Ukrainain strings in the translations folder, and it doesn't seem to be in the list of excluded translations, but it still isn't showing up as an option to select in Tiled 1.7.2 on Windows 10.

![image](https://user-images.githubusercontent.com/25536411/133944553-54982757-44b8-40df-ba23-9e6fac12212d.png)

**Comment by bjorn** [comment]
Right, currently the translations need to be manually listed in the .wxs file to ship with the Windows installer, and it seems I've forgotten to add this one. Thanks for bringing it up!

It is only 62% complete though. If you or somebody you know might be interested in helping to update this translation, you can do this at https://hosted.weblate.org/projects/tiled/translations/uk/.

I'll add the Ukrainian translation to the installer for the next release, in any case.
