### ISSUE TITLE
Collision object render data offset on the X axis for isometric maps

### ISSUE THREAD

**Issue by maximveligan** [mapeditor/tiled#3138]
Rendering the collision objects for tiles doesn't seem to be working for isometric maps. They're offset in the negative X direction by what looks like is half the tile width. The collision objects also don't appear to be rendering correctly themselves, with parts of them being cut off when I scroll the map back into view.

![collision_rendering_bug](https://user-images.githubusercontent.com/7033024/135125410-f167a66b-fee7-438d-94b2-f08cba674447.PNG)

Mousing over the mis-rendered tile fixes the missing collision rendering, but the X offset issue remains the same.

Here's what the collision object for the tile looks like:
![object_collision_settings](https://user-images.githubusercontent.com/7033024/135125541-6838164b-40d6-4504-932e-d4f0236914da.PNG)

Tiled version: 1.7.2, Windows 10

**Comment by bjorn** [comment]
Finally got around to looking into this. Turned out it was a silly regression in Tiled 1.7.2. :-/

Will be fixed in Tiled 1.8.3.
