### ISSUE TITLE
File extension case sensitivity problem for custom map formats

### ISSUE THREAD

**Issue by sdsnatcher** [mapeditor/tiled#3141]
As I mentioned on #3139, I'm working on an extension to load/save binary maps for an 8bit game.

Being from an 8bit machine, the filenames there use the old MS-DOS 8.3 uppercase-only filenames.  When they're copied to/from the floppies to a modern PC/Mac then there's a mess: depending on the tool you use, the names will be preserved as all uppercase, or converted to lowercase.

But when a script is registered to deal with a file extension, Tiled treats it as case-sensitive. This causes maps with lowercase extensions not to be recognized, i.e.

So, either script should be able to register a list of extensions instead of a single one (then I would register both upper and lowecase), or Tiled must ignore the case when dealing with extensions.

**Comment by bjorn** [comment]
Appears to have been an oversight. Thanks for bringing this up!
