### ISSUE TITLE
Request: enum type  custom property & select property name

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#3158]
I hope there is  a new type  : enum.
User could select value.

And when create a new property,  user cloud select a  existing property name in current file.

And  I also hope supply a feature like  `Type` for Custom Property ,  User can export custom-property define to a json file.

**Comment by bjorn** [comment]
@finscn I've moved your issue to the Tiled repository. Please don't open feature requests for Tiled on the `tiled-extensions` repository.

> I hope there is a new type : enum.
> User could select value.

Is this request covered by issue #1211? This feature has recently been implemented and will be released with Tiled 1.8.

> And when create a new property, user cloud select a existing property name in current file.

I can see the convenience here, but I'm unsure about scanning the entire asset for previously used property names. It could be done only once and a list of "seen" names could be cached somewhere for auto-completion purposes. Personally I'm more in favour of adding the option to pre-define custom properties, such that manually adding them is in most cases not necessary.

> And I also hope supply a feature like `Type` for Custom Property , User can export custom-property define to a json file.

Can you elaborate on this request?

**Comment by eishiya** [comment]
> e.g. A custom property named "gender" , the valid values are `male , female , other, unknown` I hope I could create a list for these values, user could select the value , not type the letter one by one.

This is possible with the enums feature that's coming with 1.8. In this example, the custom property type is "gender", and the specific property on this object is called "NPCGender".
![image](https://user-images.githubusercontent.com/70545646/137414329-6bea68e6-35fe-42b4-8118-a0a944711ffa.png)

**Comment by bjorn** [comment]
> e.g.
> A custom property named "gender" , the valid values are `male , female , other, unknown`
> I hope I could create a list for these values, user could select the value , not type the letter one by one.

Ah, I thought you were talking about something else there. Then I think your request is entirely covered by #1211 and already implemented, so I'll close this issue.
