### ISSUE TITLE
[REQUEST]  Let   API `TextFile` support encoding

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#3171]
When I  set a custom property with Chinese  on windows , it doesn't use unicode/utf8,  so , the char is wrong.

I hope the API about TextFile could support set encoding

**Comment by bjorn** [comment]
> I hope the API about TextFile could support set encoding

There is https://www.mapeditor.org/docs/scripting/classes/textfile.html#codec, does that help?

**Comment by finscn** [comment]
how to set  codec ? 

"utf8" , "utf-8" , "UTF8" "UTF-8"  ....

I think there should be more examples and informations .

**Comment by bjorn** [comment]
> I think there should be more examples and informations .

I agree. For now, you can find a list of supported encodings here: https://doc.qt.io/qt-5/qtextcodec.html#details

But, it will change once Tiled is built against Qt 6, then only these will be supported: https://doc.qt.io/qt-6/qstringconverter.html#Encoding-enum
