### ISSUE TITLE
Group Layer Parallax parameter change does not update the RenderView

### ISSUE THREAD

**Issue by NworbLegin** [mapeditor/tiled#3175]
When a group has a number of sub-objects and the group's parallax parameters are changed in the Property editor the change is not immediatly reflected in the viewport. Only when the viewport is scrolled slightly will the change to the parallax factor show.

Expected behaviour: The viewport should update to reflect the parallax parameter change immedialty after it has changed (after enter has been pressed).

This bug has been found in the windows version of the intermediate build 2021.11.02

**Comment by bjorn** [comment]
Thanks for reporting the issue, should be fixed in Tiled 1.8.2!
