### ISSUE TITLE
Project automapping rules file is not updated until maps are reopened

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3176]
(Using Tiled 2021.11.12, was testing the recent changes to make automapping work with grouped layers. I don't recall whether this issue occurred in earlier versions.)

When changing the automapping rules file for the project, the new file is not used until the map or project is reopened. The previously set file will keep being used if there was one, and the default rules.txt will be used if there wasn't a project rules file set before, in which case, Tiled will show the "No rules file found at 'rules.txt'" error message if that file doesn't exist.

This means that to make sure the new rules file is used, the project should be reopened.

I suspect the issue is that `AutomappingManager::refreshRulesFile()` is called when the map document is updated, but not when the project settings are updated.

**Comment by bjorn** [comment]
> I suspect the issue is that `AutomappingManager::refreshRulesFile()` is called when the map document is updated, but not when the project settings are updated.

That was exactly right, thanks!
