### ISSUE TITLE
Can't re-export tilesets. File > Export always grayed out for tilesets.

### ISSUE THREAD

**Issue by rgrams** [mapeditor/tiled#3177]
_Using Tiled 1.7.2, Linux_

For some reason I can never re-export tilesets. File > Export is always grayed when the active asset is a tileset. The export target and format are set in the .tsx file.

It works just fine for maps, but not for tilesets.

[Edit] Manually triggering the "Export" action from a script works just fine, so the issue is only that it's disabled in the menu when it should be enabled.

**Comment by bjorn** [comment]
Thanks for the report!

**Comment by rgrams** [comment]
Awesome, thanks for the quick fix!
