### ISSUE TITLE
How to parse reflected tiles data? 

### ISSUE THREAD

**Issue by KyleKun** [mapeditor/tiled#3183]
Hi there, I am having a hard time trying to understand what each number represents in a tile that was reflected (and rotated). I didn't find anything about it in the docs and couldn't find where this data is processed in the source code. 

For example in this last tile: [0, 0, 0, 32, 2147483680], what is each number representing?

Thanks in advance!

**Comment by eishiya** [comment]
The global tile IDs and how to parse them are explained in the documentation: https://doc.mapeditor.org/en/latest/reference/global-tile-ids.html

**Comment by KyleKun** [comment]
Hi @eishiya, that's it, thank you!
Can you help me to know if I got it right?

1) Convert from string to 32-bit;

2) Search flip flags (29, 30, 31, 32) and remove them from the tile GID after that;

3) Look for first gids in all tilesets that are <= the value left in the tile GID and pick the closest one to find what tileset the tile is stored by doing: tile GID - first gid (from the tileset).

**Comment by eishiya** [comment]
Looks correct to me. Get the list of tile IDs as unsigned 32-bit integers, and for each tile, read its flags, clear them, and then get the appropriate tile based on the remaining GID and the `firstgid`s of the tilesets in the map.

Of course, the best way to check is to implement it and see :D

**Comment by KyleKun** [comment]
Thanks a lot, I was able to achieve it! 
Closing this issue.
