### ISSUE TITLE
Tiled replaces ext:myTileSet.tsx with ../../../../../../../ext:myTileSet.tsx when saving a tmx file

### ISSUE THREAD

**Issue by sdsnatcher** [mapeditor/tiled#3185]
Tiled allows resources like the tileset to be placed on the extensions folder by using the ext: keyword before the resource file name.

It works like a charm when loading a tmx file. But when the same tmx file is saved, Tiled adds ../../../../../../../ before the ext: keyword inside the tileset tag, like this:

` <tileset firstgid="1" source="../../../../../../../ext:myTileSet.tsx"/>
`

This way the tmx file show up broken when it's loaded later.

**Comment by bjorn** [comment]
Hmm, looks like some special handling will be needed for those, yeah.

**Comment by bjorn** [comment]
Should now be handled correctly in the upcoming Tiled 1.8 release.
