### ISSUE TITLE
combine map and tileset JSON

### ISSUE THREAD

**Issue by CKT90** [mapeditor/tiled#3191]
hi, 

created an animation in the tile-set, the map JSON only reflect a single ID without the animation tile information (tile ID and frame-speed) which need to refer in a separate JSON file exported from the tile-set. 

is it possible to export a single file that contains the map layer data JSON, together with the animation tiles JSON data?
don't mind a very long JSON file.

thanks.

**Comment by bjorn** [comment]
Yes, you can either permanently embed the tileset in the map using the "Embed Tileset" below the tileset view (not recommended) or export the map for this purpose, while enabling the following export option (recommended):

![image](https://user-images.githubusercontent.com/531764/144073251-12e713e3-37dd-4b0f-8bf8-ab2b3a09f247.png)
