### ISSUE TITLE
Support by Language (Rust Tiled Crate)

### ISSUE THREAD

**Issue by JasonHise** [mapeditor/tiled#3195]
For [this documentation](https://doc.mapeditor.org/en/stable/reference/support-for-tmx-maps/#support-by-language), request to add [this tiled crate](https://crates.io/crates/tiled) as a Rust library.

**Comment by jestarray** [comment]
I would also recommend just exporting a JSON and parsing it as such because that crate is kinda slow when it comes to being caught up with the latest tiled spec

**Comment by bjorn** [comment]
@jestarray Could you provide some more details about what is slow about it? And is this something that can be fixed, or would you say JSON parsing is always preferred? Finally, if loading a Tiled JSON map, would you suggest using one of [`tiled-json-rs`](https://crates.io/crates/tiled-json-rs) or [`rs-tiled_json`](https://crates.io/crates/rs-tiled_json)? Though I see for `tiled-json-rs` the repository link appears dead...

**Comment by bjorn** [comment]
> Though I see for `tiled-json-rs` the repository link appears dead...

This seems to just have been a rename of the GitLab user, so I've just [opened an issue](https://gitlab.com/flukejones/tiled-json-rs/-/issues/3) regarding this broken link.
