### ISSUE TITLE
Deleting layers inside of regionEdited signal handler crashes Tiled

### ISSUE THREAD

**Issue by user72356** [mapeditor/tiled#3199]
This is a sneaky one... 

Let's say we have a map with 2 layers, and a tile at 0, 0 in each one of these layers. Now say we listen for map changes with the regionEdited signal. When we receive a signal, we remove the other layer from the map (sounds weird I know, but this is a simplified example just to illustrate the problem). 

So far so good, it works when we add a tile to one of the layer, our callback removes the other layer just fine. 

Now let's say that instead of adding a tile, we remove the tiles at 0, 0 across all layers using the SHIFT+Eraser tool. It crashes Tiled, because 2 signals are emitted (one for each layer), and when the first callback runs, we remove the other layer, causing the second signal to no longer have a reference to the deleted layer. It causes a crash because, I'm guessing, there is no last-minute check on the layer variable right before the emission.

**Comment by bjorn** [comment]
> It crashes Tiled, because 2 signals are emitted (one for each layer), and when the first callback runs, we remove the other layer, causing the second signal to no longer have a reference to the deleted layer. It causes a crash because, I'm guessing, there is no last-minute check on the layer variable right before the emission.

This is exactly right. I've tried to add some safety checks in 8af9d0d7262b0eaa91bdb4d115aad5071b615fd4. Let me know if you can still crash it or cause wrong behavior! New builds should be available soon at https://github.com/mapeditor/tiled/actions/runs/1751555034.

**Comment by bjorn** [comment]
@user72356 Btw, this change is not included yet in the Tiled 1.8 RC that I'm publishing today. However, if it seems stable enough now I will include it in the final release, which I hope to make next week. I don't want to take on new major patches for 1.8 though, so the solution to #3193 will have to come in 1.9.

**Comment by nbarraud** [comment]
> > It crashes Tiled, because 2 signals are emitted (one for each layer), and when the first callback runs, we remove the other layer, causing the second signal to no longer have a reference to the deleted layer. It causes a crash because, I'm guessing, there is no last-minute check on the layer variable right before the emission.
> 
> This is exactly right. I've tried to add some safety checks in [8af9d0d](https://github.com/mapeditor/tiled/commit/8af9d0d7262b0eaa91bdb4d115aad5071b615fd4). Let me know if you can still crash it or cause wrong behavior! New builds should be available soon at https://github.com/mapeditor/tiled/actions/runs/1751555034.
> 
> I've also removed the `TiledMap.regionChanged` signal I had added, because this provided many more ways to screw things up given that it is even triggered from inside an undo command.

@bjorn Sorry for taking a while to get back to you, I was tied up somewhere else. Something is wrong with this new version, it doesn't work at all for me. I haven't had time to analyze the situation in more details, but it's definitely acting very weird now. I will do some more testing now and report back.

**Comment by user72356** [comment]
> > It crashes Tiled, because 2 signals are emitted (one for each layer), and when the first callback runs, we remove the other layer, causing the second signal to no longer have a reference to the deleted layer. It causes a crash because, I'm guessing, there is no last-minute check on the layer variable right before the emission.
> 
> This is exactly right. I've tried to add some safety checks in [8af9d0d](https://github.com/mapeditor/tiled/commit/8af9d0d7262b0eaa91bdb4d115aad5071b615fd4). Let me know if you can still crash it or cause wrong behavior! New builds should be available soon at https://github.com/mapeditor/tiled/actions/runs/1751555034.
> 
> I've also removed the `TiledMap.regionChanged` signal I had added, because this provided many more ways to screw things up given that it is even triggered from inside an undo command.

@bjorn Sorry for taking a while to get back to you, I was tied up somewhere else. Something is wrong with this new version, it doesn't work at all for me. I haven't had time to analyze the situation in more details, but it's definitely acting very weird now. I will do some more testing now and report back.

**Comment by user72356** [comment]
@bjorn I've spent time troubleshooting and I can't reproduce the problem I have reported in my previous message. I feel that this may have been due to me reusing an old map that was written by the previous test version of Tiled. When starting fresh I can't seem to see the issue again.

Basically I think the crash is fixed and you can definitely include it in 1.8.

Thank you!
