### ISSUE TITLE
Scripting: Allow Tools to keep focus when tiles are selected

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3201]
When using a scripted Tool, selecting a tile from the Tilesets Panel changes the active tool to the Stamp Brush. This makes using scripted tools for painting quite annoying. I've been working around this by adding a "right click to sample tile" behaviour to most of my tools, but that is often not enough.

Tools should be able to set a boolean property on the tool object that will allow them to keep focus when the user picks a new tile.

If the ability to see what Terrain the user has selected in the GUI is added to the scripting API, another property to keep focus when the current terrain is changed would also be useful.

**Comment by bjorn** [comment]
Adding `usesSelectedTiles: true` to your custom tool does the trick now. :-)
