### ISSUE TITLE
Terrain support for hexagonal grids

### ISSUE THREAD

**Issue by iconmaster5326** [mapeditor/tiled#3206]
Currently, the only options for terrain maps (4 and 8 sides) aren't usable for hexagonal grids (which have 6 edges). When you try to use terrain maps with a hex grid with the 8-sided option, the terrain placing tool will attempt to places tiles to the two nonexistent "sides", causing placement issues and rending the terrainmap tool generally unusable.

**Comment by bjorn** [comment]
Duplicate of issue #2824, please see the discussion there.
