### ISSUE TITLE
Non-square major grid size

### ISSUE THREAD

**Issue by Osmose** [mapeditor/tiled#3208]
Hi, thanks for making Tiled! It's wonderful.

The major grid feature is very useful for tilemaps that are sectioned out into regularly-sized cells, but my particular game uses cells that aren't square: they're 16 tiles wide and 15 tiles tall. It'd be great if we could set the width and height of the major grid lines separately instead of the single input that's there now: 

![image](https://user-images.githubusercontent.com/193106/145931787-23c9f206-c05c-4679-a356-fb1f0265e2da.png)

**Comment by bjorn** [comment]
For the upcoming Tiled 1.8, it's been split up now:

![image](https://user-images.githubusercontent.com/531764/150352000-53f51ec7-6b5e-4303-ae89-1cb8c9fb2c35.png)

**Comment by Osmose** [comment]
Awesome, thank you so much!
