### ISSUE TITLE
Use tmxrasterizer from script

### ISSUE THREAD

**Issue by captain-porkins** [mapeditor/tiled#3219]
Hey,

I'm trying to write a [script](https://doc.mapeditor.org/en/stable/reference/scripting/) that will export each layer of a map as an individual image. I found the `tmxrasterizer` binary which isolates the image exporting functionality and of course I can just shell out from the script to this binary, but i'd like the script to be re-usable and to work regardless of how or where Tiled is installed. 

So i guess my question is:
- is there a direct bit of the tiled api which exposes the image export functionality (couldn't find it in the [docs](https://www.mapeditor.org/docs/scripting/modules/tiled.html))
- if not, is there a way to access the `tmxrasterizer` using the `tiled` api - or at least a way to get the path to this binary?

Thanks! :)

**Comment by bjorn** [comment]
> * is there a direct bit of the tiled api which exposes the image export functionality

Unfortunately not. I'd like to expose this functionality, but there are a lot of potential options to support, so it's not immediately obvious what this API should look like.

> * if not, is there a way to access the `tmxrasterizer` using the `tiled` api - or at least a way to get the path to this binary?

There wasn't, but in Tiled 1.8 there will be a `tiled.applicationDirPath` property (see #3139), which can be used for this purpose.

**Comment by captain-porkins** [comment]
Thanks for getting back to me. I shall keep an eye out for that release :)

**Comment by bjorn** [comment]
> Thanks for getting back to me. I shall keep an eye out for that release :)

In case you wanted to use / test it now, note that you can download a build for your OS from https://github.com/mapeditor/tiled/actions/workflows/packages.yml?query=branch%3Amaster, if you click on the last successful build and then scroll down to Artifacts. :-)

**Comment by captain-porkins** [comment]
Nice, thanks!
