### ISSUE TITLE
Allow setting Automapping rule map as Project rules file

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3221]
For projects that only have a single automapping rules map file, creating a rules.txt that just lists that one map file feels like an unnecessary inconvenience, especially since rules list files can't be edited within Tiled.

Please allow setting a map file as the Automapping rules file for a Project directly. This should take the form of an alternate file type selectable in the browser, e.g. "Automapping Rule Maps (*.tmx, *.tmj, *.json)", so that the default option still only looks for TXT files.

On a related note, what's the proper terminology for these files? It seems to be the TXT files are "automapping rule**s** files", while the maps are "automapping rule files", which is confusing.

**Comment by bjorn** [comment]
Now you can set a map file directly, and not only that, but the Automapping feature should now work with any map format, rather than being hardcoded to only supporting ".tmx" files. :-)

And, it works with a plain map file as well when using the `TileMap.autoMap` scripting function!

**Comment by eishiya** [comment]
Oh, I had no idea only TMX was allowed. Good fix!

`TileMap.autoMap(mapFile)` could be useful for scripting conditional automapping, that could be interesting 👀 I could use that to implement #3014 as a script, since it sounds like the consensus there is leaning away from the approach that I would find useful.
