### ISSUE TITLE
Highlight Current Layer sometimes highlights unselected layers

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3223]
When the bottom-most layer in a map is deleted, Highlight Current Layer feature gets confused and starts also highlighting the layer below the currently selected layer. I've noticed it most when the top layer is selected, but I've also seen it happen with other layers in addition to the top layer.
![tiled_highlightlayer](https://user-images.githubusercontent.com/70545646/147376586-4151ec7c-489d-4d24-80d7-61ff062602f7.gif)

Steps to reproduce:
1. Create a new map file with 3 or more layers.
2. Verify that Highlight Current Layer works as expected.
3. Delete bottom layer.
4. The top two layers will now be highlighted when the top layer is selected.

I'm not sure, but I think every new deletion of the bottom-most layer causes a another layer to be affected. It affects non-tile layers too.

Reopening the map or Undoing/Redoing the deletion(s) will fix the highlighting.

In addition, deleting a layer and then Undoing the deletion will cause multiple layers to be highlighted, but this is only temporary and will resolve itself once some other layer is selected.

I am using Tiled 2021.12.22 multi-layer pasting test build, but this issue occurred on earlier builds as well.

**Comment by bjorn** [comment]
Well, I hope that I managed to fix this reliably. The code is a bit fragile since it depends on updating the Z value of the layer items and the dark rectangle, as well as the parent item of the dark rectangle.

**Comment by eishiya** [comment]
Deleting layers seems to not mess up highlighting anymore, but Undoing a layer deletion still does ;D

Here, I undid deleting the Bot layer:
![image](https://user-images.githubusercontent.com/70545646/150382356-40d0a7f4-8ad0-4ead-8d11-443ea01d1a89.png)
