### ISSUE TITLE
crash with custom map format and tilesets

### ISSUE THREAD

**Issue by eladyn** [mapeditor/tiled#3229]
First of all, thanks for this great project!

I'm currently trying to implement a custom map format (import + export) using the JS Scripting API and I ran into some issues, where Tiled crashes after the file has been saved. I managed to narrow the problem down to a quite small code snippet. I am able to reproduce the same error in two different ways, so there might be more than one bug. In that case, I can of course create separate reports for the two.

The crash does only ever happen, if I try to access the `Tile`s of a `Tileset` within the `write` method. [From what I found](https://github.com/mapeditor/tiled/issues/2696#issuecomment-565177785), I assume that this should generally be "allowed" and possible.

# Problem 1: accessing `Tile`s in the `write` method

<summary>Custom Map Format: reproducer.js</summary>
<details>

```js
const ReproducerMapFormat = {
    name: "Reproducer Map Format",
    extension: "rpr",

    read: function(fileName) {
        let map = new TileMap();

        let tileset = new Tileset("Tileset");
        tileset.setTileSize(32, 32);
        
        let image = new Image();

        image.load("reproducer_tileset.png");
        tileset.loadFromImage(image, "reproducer_tileset.png");

        tileset.tile(0);
        tileset.tile(1);

        map.addTileset(tileset);

        return map;
    },

    write: function(map, fileName) {
        let tileset = map.tilesets[0];

        console.log("tile_count: ", tileset.tileCount); // 4
        tileset.tile(0);
        tileset.tile(1);

        // uncommenting this produces the crash
        // tileset.tile(2);

        return "";
    },
}

tiled.registerMapFormat("reproducer", ReproducerMapFormat);
```
</details>

Executing the following command leads to the crash:
```console
# tiled --export-map reproducer test.rpr test.rpr
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Qt: Session management error: Could not open network socket
qml: tile_count:  4
ASSERT: "editable->tileset() == this" in file /build/tiled/src/tiled-1.7.2/src/tiled/editabletileset.cpp, line 339
zsh: abort (core dumped)  tiled --export-map reproducer test.rpr test.rpr
```

This error happens, if the `write` method tries to use a `Tile` (either through `tileset.tile()` or with the `tileset.tiles` array), which hasn't been accessed by the `read` method before. Inserting something like this in the read method prevents the crash from happening:

```js
for (const tile of tileset.tiles) continue;
```

# Problem 2: using `Tileset.tile(id)` too many times in `read` method

Using the previously described workaround for the first problem did not solve the problem in my specific case. This other situation could be broken down into the following:

<summary>Custom Map Format: reproducer.js</summary>
<details>

```js
var reproducerMapFormat = {
    name: "Reproducer Map Format",
    extension: "rpr",

    read: function(fileName) {
        let map = new TileMap();

        let tileset = new Tileset("Tileset");
        tileset.setTileSize(32, 32)

        let img = new Image();
        img.load("reproducer_tileset.png");
        tileset.loadFromImage(img, "reproducer_tileset.png");

        map.addTileset(tileset);

        // this line prevents problem 1
        for (const tile in tileset.tiles) continue;

        // without this for loop, the error is not reproducible (even with extremely high numbers in the for loop below)
        for (const _ of []) {
            continue;
        }

        // for (let x = 0; x < 6043; x++) tileset.tile(0);
        // works

        // for (let x = 0; x < 6044; x++) tileset.tile(0);
        // ASSERT: "mTilesets.isEmpty()" in file /build/tiled/src/tiled-1.7.2/src/libtiled/tilesetmanager.cpp, line 62

        // for (let x = 0; x < 6048; x++) tileset.tile(0);
        // ASSERT: "mTilesets.isEmpty()" in file /build/tiled/src/tiled-1.7.2/src/libtiled/tilesetmanager.cpp, line 62

        // for (let x = 0; x < 6049; x++) tileset.tile(0);
        // ASSERT: "editable->tileset() == this" in file /build/tiled/src/tiled-1.7.2/src/tiled/editabletileset.cpp, line 339

        return map;
    },

    write: function(map, fileName) {
        let tileset = map.tilesets[0];

        for (const tile of tileset.tiles) continue;
        return "";
    },
}

tiled.registerMapFormat("reproducer", reproducerMapFormat)
```
</details>

Again, running this with `tiled --export-map reproducer test.rpr test.rpr` produces the crash, after commenting out one of the marked lines.

This appears to be a really strange error:

- Removing the for loop that iterates over the empty array makes the error go away.
- The error starts to appear after a specific number of `tileset.tile(0)` calls.
- After increasing the number a bit further, the crash comes from a different source.

# About the minimal reproducers

I am aware that the two code examples don't make much sense (no actual file io, empty for loops, repeated access to one Tile). However, breaking the real code down to this allowed to eliminate most other possible problem sources and minimizes the area where the problem may come from. If you need more context, to solve this, I'll be happy to post a real example

# Notes

This may very well be me, using the API in a wrong way. But I repeatedly ran into this issue and couldn't get any further, so I thought it would be best to report it.

# System Information

- OS: Arch Linux
- Tiled: `Tiled 1.7.2`

# Additional Files

- [reproducer_tileset.png](https://user-images.githubusercontent.com/59307989/148470811-9aa018c1-c232-47a4-ae61-32c18a429bc3.png)
- [core_dump](https://github.com/mapeditor/tiled/files/7825568/core.txt)

**Comment by bjorn** [comment]
Thanks a lot for the detailed report and providing the files to reproduce this issue! It was indeed a bit of a tricky one, and I hope I managed to fix it reliably.

I'm unsure btw, if these were actual crashes or just assertion failures. I think potentially the assertion is wrong, but there was anyway an issue in the `EditableTileset` constructor causing the assert to happen in this case. But it could be you only detected this problem because you were using a build with assertions enabled.

**Comment by eladyn** [comment]
As far as I'm concerned, everything is working fine now with the AppImage from the CI. Thank you for looking into this!
