### ISSUE TITLE
More detailed documentation for scripting API

### ISSUE THREAD

**Issue by BlaXun** [mapeditor/tiled#3239]
The documentation located at https://www.mapeditor.org/docs/scripting/ is kinda barebones right now.

For example many classes there don't have a description and its really hard to figure out how to do stuff.
I am struggling with showing a preview for placing custom objects (is there any guide on how to do this?)

Thanks in advance

**Comment by bjorn** [comment]
> For example many classes there don't have a description and its really hard to figure out how to do stuff.

There have been some additions that are not online yet, but in general this is indeed an area where the documentation needs to be improved.

> I am struggling with showing a preview for placing custom objects (is there any guide on how to do this?)

Unfortunately, at the moment this is simply impossible. Only a tile layer preview is supported at the moment. The built-in object creation tools show a preview by creating an object item for an object that is not actually part of the map. This is a little hacky, so creating an object preview controllable from the scripting API will need to be done with care. It's something that should be added though.
