### ISSUE TITLE
Scripting: Allow opening a Map created via script in the editor

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3252]
There is currently no way to display a map created via script to the user, except by saving it and opening it from file, which is usually not desirable. `tiled.activeAsset` only accepts assets opened from file.

Since Tiled can now work with unsaved maps, maps created in a script should also be possible to open in the editor for the user to deal with as they wish.

I think the easiest way to do this would be to allow assigning such a map to `tiled.activeAsset`, so that dealing with read and created maps is identical. Opening several maps in the editor could be done by repeatedly assigning to it.

**Comment by bjorn** [comment]
Sorry, turned out there was an issue about this already after all: #3160. Well, at least this issue is on my list for Tiled 1.8 now!
