### ISSUE TITLE
Tile identifier counts from 0 in GUI, 1 in XML

### ISSUE THREAD

**Issue by differenceclouds** [mapeditor/tiled#3255]
It's a small thing, but when mousing over a tile in the application, the first tile in a set will show as [0] in the status bar, but in the XML, will output as "1".

**Comment by alexdevteam** [comment]
That is probably because you are confusing local tile IDs (the ones shown in the editor) with global tile IDs (GIDs). You can read more about them here: https://doc.mapeditor.org/en/latest/reference/global-tile-ids/

**Comment by differenceclouds** [comment]
Ah, that makes sense. if multiple tilesets are used, you need to count from 1 with the GID so that subtraction thing works for the local IDs... right?

**Comment by alexdevteam** [comment]
You shouldn't rely on starting from one. If I remember correctly, all map tilesets have a `firstgid` attribute on them which you can use as a starting point for the GID of the tiles on that specific tileset.

**Comment by bjorn** [comment]
Right, please see the linked page in the manual for the details, but the important bit here is that in a tileset, the first tile has ID 0, but in a saved map, 0 means "no tile" and the first tile in the first tileset hence gets the global ID 1.

In the UI, only the local ID of the tile is shown. The global ID of the tile doesn't actually exist until the file is saved, and can be different depending on which other tilesets are referenced by the map and in which order.
