### ISSUE TITLE
JSON-formatted object templates not working in Tiled 1.8 RC

### ISSUE THREAD

**Issue by geoffb** [mapeditor/tiled#3257]
The Tiled 1.8.0 RC (1.7.91) cannot load object template files which were saved in JSON format. XML formatted object templates file can be loaded as expected.

Tiled 1.7.91, macOS Monterey 12.2

To reproduce:
1. Create a new map and save in XML or JSON format
2. Create an object layer
3. Create a rectangle object of any size
4. Right click on rectangle object and select "Save As Template"
5. Save the template in JSON format
6. Close the map and/or Tiled application
7. Reopen map/Tiled
8. Tiled displays a message that the JSON formatted template file could not be found
9. Attempting to "Locate" the missing file by selecting the same file results in an empty error dialog

**Comment by bjorn** [comment]
That was an embarrassing regression. Thank you so much for catching and reporting it!
