### ISSUE TITLE
Image layer base position drifts when using a parallax factor

### ISSUE THREAD

**Issue by jvisser** [mapeditor/tiled#3259]
When using a parallax factor for an image layer, the base position of the parallax image layer also changes.

Tested in both 1.7.2 and the latest 1.8.0 release candidate.

For example:

Not scaled: image layer is based at the same position as the map (0, 0) (as expected!)
![image](https://user-images.githubusercontent.com/946768/152332349-b94508b7-a686-4869-9ac9-c2229ca04e02.png)

Change the scaling to (.25, .50), same scene:
![image](https://user-images.githubusercontent.com/946768/152332507-47da6731-e546-4c2c-acfb-5b84b8e603d4.png)

This also causes the background position to change when zooming in/out which imo should not happen.

Change zoom in editor:
![image](https://user-images.githubusercontent.com/946768/152333017-a408fb58-ca31-4e1c-9881-dc99d72e3580.png)

I don't know what the fix would be exactly. Maybe base the parallax layer position on the difference between viewport position top left and the map base position (0, 0) scaled by the parallax factor. And only then apply the editor zoom factor on the layers.

**Comment by bjorn** [comment]
> Maybe base the parallax layer position on the difference between viewport position top left and the map base position (0, 0) scaled by the parallax factor. And only then apply the editor zoom factor on the layers.

The parallax offset is currently based on the difference between the origin of the map (0,0) and the center of the screen. In the upcoming Tiled 1.8 release, there is an additional "Parallax Origin" property on the map, which you can set to define a different origin point. I think that should help you get better results, for example by setting it to half of your target viewport size. I'd suggest you try it out by installing the [Tiled 1.8 RC](https://github.com/mapeditor/tiled/releases/tag/v1.7.91) (just note that it has [one critical issue](https://github.com/mapeditor/tiled/issues/3257)).

See https://doc.mapeditor.org/en/stable/manual/layers/#parallax-scrolling-factor for the details on the parallax scrolling factor and the parallax origin.

**Comment by jvisser** [comment]
Hi @bjorn, I don't see the options in 1.7.91. Was testing it out yesterday to check out the repeatx/y options. I tried adding the options to the map file directly for the image layer `parallaxoriginx="160" parallaxoriginy="114"` based on this pull request https://github.com/mapeditor/tiled/pull/3209/files but it doesn't seem to have any effect. Everything still works the same as in the OP.

**Comment by jvisser** [comment]
Ah yes, you are right, thanks. 

Still can't get it to replicate my in game situation. Which is very simpel, something like:
- parallax factors: background map size / foreground map size
- origin for both maps is 0,0 (in map space)
 
When scrolling to the beginning or end of the map either horizontal/vertical the edges of that side of both maps align.

Repositioning of the parallax map when zooming in/out also causes the view to not match anymore. 

It's not a huge deal btw as I'm only using the image layer for presentation in the editor atm. But was thinking of using it for in game values so you could preview directly in Tiled.

**Comment by eishiya** [comment]
Your in-game situation also includes a viewport, which is what's missing in Tiled. If you set your parallax origin point to half your viewport size and give yoursself a frame of reference (such as a literal frame the size of your viewport, with parallax factor set to 0), the map as seen through this reference frame should match what's in your game.

The zooming changes what's in the middle of the screen, which is why there's an apparent mismatch. Having a reference viewport should make it much easier to see what's going on.

**Comment by jvisser** [comment]
Ok thanks for the explanation @eishiya.
