### ISSUE TITLE
Automapping causes Tiled to crash

### ISSUE THREAD

**Issue by barodapride** [mapeditor/tiled#3269]
In Tiled 1.8.0, if a rule tile map contains an input layer that does not exist in the tile map when AutoMap is executed, it causes the program to close. After adding the layer to the tile map, everything seems to work fine and the program no longer crashes on AutoMap.

**Comment by eishiya** [comment]
I was able to reproduce this issue by adding `input_Nonexistent` to one of my automapping rule maps.

However, I also already have a rule file with `input_wallpaper` in it and it runs just fine (doing nothing) even though the target map does not have a layer called `wallpaper`. Adding `input_Nonexistent` to this map caused no problems, though Tiled did crash when I tried to remove that input layer after running AutoMap.

Sounds like there's a dereferencing of an un-found layer happening *somewhere*, but not always.
