### ISSUE TITLE
Example of this being used?

### ISSUE THREAD

**Issue by independence106** [mapeditor/tiled#3276]
Is there a project out there that features just how to load in a single Map? (In JAVA) 

Please link below or refer me to someone who might know. Thanks!

**Comment by bjorn** [comment]
I think most projects using Tiled and Java are based on [libGDX](https://libgdx.com/), which has [support for loading Tiled maps](https://libgdx.com/wiki/graphics/2d/tile-maps) built-in.

If you want to try using `libtiled-java` instead, there's an example map viewer here: https://github.com/mapeditor/tiled/tree/master/util/java/tmxviewer-java
