### ISSUE TITLE
Enums are not usable although saving them to the Project file.

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#3295]
**Describe the bug**
I try to use Enums after saving them, but they don't show up in the CustomProperties of an selected Object, like I would expect it. I have also made sure to save the Enums in the Project file.

**Expected behavior**
Enums work :)

**Media**
![image](https://user-images.githubusercontent.com/1249266/157097307-3f541433-0536-4ac0-bf46-1a2e66abcbcd.png)

**Specifications:**
 - OS: Windows 10
 - Tiled Version: v1.82

**Comment by UliAbo** [comment]
I made sure that it's inside the *.tiled-project file:

![image](https://user-images.githubusercontent.com/1249266/157100507-3928ae9f-e7e8-4446-bae2-857e160a73e3.png)

**Comment by bjorn** [comment]
@UliAbo Would it be possible for you to share a minimal zipped up project directory with which you can reproduce this issue?

**Comment by UliAbo** [comment]
![image](https://user-images.githubusercontent.com/1249266/157238762-f144e30f-6a2c-4146-a774-36f6cdffea23.png)

I just opened the project from yesterday and now it's there...
It seems like the project needed a restart of Tiled itself? 

So this is no real bug from my side, I guess. Just the restart is necessary...

@bjorn Yesterday in the chat you mentioned problems other Users have - do they have the very same issue I described in my initial post?

**Comment by bjorn** [comment]
> Yesterday in the chat you mentioned problems other Users have - do they have the very same issue I described in my initial post?

I think there was at least one other person who also needed to restart Tiled to see the types. However, that should not be necessary, so there's still a bug somewhere. Do additional enums you're adding at least show up without requiring a restart?

**Comment by UliAbo** [comment]
Yes adding further ones works instantly.

**Comment by bjorn** [comment]
Alright, I was able to reproduce the problem. It appears to me, that this only happens when you did not initially had a project set up. So when you do things in this order:

* Launch Tiled without a project loaded
* Open Property Types Editor, add some types
* Save the Project

Then, even though the types will be saved to the project, they do not show up in the Add Property dialog. For that to work, you'll need to have a project loaded either at startup or through opening it after startup.

**Comment by UliAbo** [comment]
Okay! I definitely can confirm that. I did the same, I created the project and the enums all in one go.

**Comment by UliAbo** [comment]
I think with the new Custom Types, this problem is gone? This can be closed? Or do I overlook something?

**Comment by bjorn** [comment]
@UliAbo I think you overlooked that this issue is already closed since a few months. :-)

**Comment by UliAbo** [comment]
Oh yes you are right of course^^° 
I just overlooked it above as I was somehow always looking at the bottom to see if something has been closed.
![image](https://user-images.githubusercontent.com/1249266/183254357-14b67905-044e-462a-b2d1-cdf95ecfd629.png)

I now learned it!

**Comment by eishiya** [comment]
@UliAbo You should be able to see the status of an issue at the top of the page no matter how far down you scroll, that's the place to look. You don't have to hunt for the status in the timeline of the issue :]
![image](https://user-images.githubusercontent.com/70545646/183258476-c8037a1b-7e74-4fb0-a35d-863bb05fecc2.png)

**Comment by UliAbo** [comment]
Okay thanks :D
