### ISSUE TITLE
Improving UX of Object and Property Types with larger text fields.

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#3302]
Currently, when using long names for Property Types, the according text field is very short - it would be great to have wider text fields:
![image](https://user-images.githubusercontent.com/1249266/158360583-02b8e6cf-2704-4e1a-9c84-2832a2f7c1bd.png)

**Comment by bjorn** [comment]
Maybe they should just be placed above each other rather than next to each other. Alternatively, the type could be already selected as sub-menu for "Add Property", then the dialog would just need to ask for the name.

**Comment by UliAbo** [comment]
Yes, even better! That would be good.

**Comment by bjorn** [comment]
For Tiled 1.8 I've pushed a small change that just changes the layout:

![image](https://user-images.githubusercontent.com/531764/166903334-e008bdac-5b96-4367-b0d5-14ed89bad97f.png)

For 1.9 we can explore using a menu to select the type of property to add.
