### ISSUE TITLE
Bug: Connecting Objects through Classes doesn't render connection arrow.

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#3306]
**Describe the bug**
 Connecting Objects through Classes doesn't render connection arrow.

**To Reproduce**
1. Create Class with Property with "Object" as variable type.
2. Assign Object with Class.
3. Connect Object through Class property with other Object.
4. As far as I see this, it works technically, but not visually.

**Expected behavior**
Connection arrow is shown like usual (double-checked, this already works for me with not using Classes).

**Media**
Missing arrow:
![image](https://user-images.githubusercontent.com/1249266/159150773-b51ee247-c48b-4ba1-9bd8-8a6e42491abd.png)

**Specifications:**
 - Win10 64bit
 - Tiled Version: v1.82

**Comment by bjorn** [comment]
Thanks for opening an issue about it! I had this on my mind while adding support for custom classes, but forgot about it in the end.  Fixed for Tiled 1.8.3.
