### ISSUE TITLE
The properties `repeatx` and `repeaty` are missing when exporting json map.

### ISSUE THREAD

**Issue by SSBMTonberry** [mapeditor/tiled#3307]
**Describe the bug**
The properties `repeatx` and `repeaty` are missing when exporting a json map. To be clear: These properties are fine when doing a regular save, but when

**To Reproduce**
1. Create a map with a image layer.
2. Check repeatx and repeaty.
3. `Save As...` .json, and notice the properties `repeatx` and `repeaty` are there.
4. `Export As...` .json, and notice the properties `repeatx` and `repeaty` are missing.

**Expected behavior**
I expect these properties to exist when exporting a json.

**Media**
![image](https://user-images.githubusercontent.com/26206421/159156155-0bd461cf-6e06-45e5-894a-9b4ec15b7670.png)

**Specifications:**
 - OS: Manjaro Linux
 - Tiled Version: 1.8.2

**Comment by bjorn** [comment]
Whoops, sorry about that! Will be fixed in Tiled 1.8.3, and if you need the fix now you can get a build soon at https://github.com/mapeditor/tiled/actions/runs/2015066847.

**Comment by SSBMTonberry** [comment]
No worries! Thanks for the fix btw :smile:
