### ISSUE TITLE
[Scripting] Unexpected behavior of region().rects

### ISSUE THREAD

**Issue by user72356** [mapeditor/tiled#3308]
I don't know if I should call this a bug, inconsistent behavior, or mismatched expectations. I'm thrown off by the way Tiled lists the rects present in a tile layer (new feature in 1.8). I could not find a precise documentation to explain how the rects are calculated, so I made some assumptions.

My expectation: rectangular groups of tiles found in a tile layer, no empty tiles are included. A rect contains as many neighboring tiles as possible while remaining rectangular-shaped.

The reality: rectangular groups of tiles found in a tile layer, no empty tiles are included. Neighboring tiles may or may not be part of the same rect.

It's a little hard to explain this with words but here is the behavior I've encountered that threw me off:

```
[DEBUG] T
[DEBUG] T
[DEBUG] 
[DEBUG] Rects:
[DEBUG]   Rect 1 = x: 17, y: 20, right: 18, front: 22
```

Above we can see that the tile layer contains 2 tiles on top of each other. The rect is calculated to include these 2 tiles.

```
[DEBUG] T-T
[DEBUG] T--
[DEBUG] 
[DEBUG] Rects:
[DEBUG]   Rect 1 = x: 17, y: 20, right: 18, front: 21
[DEBUG]   Rect 2 = x: 19, y: 20, right: 20, front: 21
[DEBUG]   Rect 3 = x: 17, y: 21, right: 18, front: 22
```

Now we've added a separate tile to the right of the first one, separated by a space. I would have expected 2 rects to come out of this. The same rect as the first example, and another rect with just the new tile. Instead we get 3 rects with one tile each.

At the end of the day it's not a big deal and I will go back to using the layer BoundingRect and dealing with spaces myself. But I'm submitting this issue in case this is actually a bug.

**Comment by bjorn** [comment]
I guess it would get rather expensive if adding some rect to a region would always result in the minimum number of rects to make the region. Instead, some faster algorithm is used, which does not guarantee a minimum number of rects, while still making sure that none of the rectangles overlap nor do they cover any location that isn't within the region. The order in which you add tiles might also matter here.

I'm wondering though, why do you care? What is the use-case you have for this?

**Comment by user72356** [comment]
To be honest I don't have a good use case for this. I'm extracting rows and columns of tiles (they represent walls) and for some reason I thought rects would preserve the rows and columns as long as those were separated by empty spaces. But it's still not a good way of doing it anyway. I was just experimenting with how using rects could speed up my algo vs iterating through everything like I was doing. Then I stumbled across this and I thought it was interesting that an entire column could be cut in half due to the mere presence of a tile somewhere else. If one were to use rects just to iterate through all tiles minus empty tiles (as I assume it's intended for), none of this would matter.
