### ISSUE TITLE
Automapping: Keep something like `StrictEmpty`

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3314]
**Background**
Currently, to specify that a cell should be Empty in an automapping rule, you have to include it in the region, leave it empty, and set `StrictEmpty` on that input layer. With the new automapping system coming in 1.9 (#3100), there will be explicit "Empty" tiles you use to specify when a cell should match empty, which is great in most cases. Since explicit Empty tiles will be available, `StrictEmpty`, the current way to specify empty tiles in input layers, will be deprecated.

**Problem**
When there are several input layers that need to be Empty in most of their cells, *requiring* the "Empty" tile to be used clutters up the rules and makes them harder to read. Here, for example, I'm looking for door tiles on `input_Main` (the dark purple tiles) and for a loose arrangement of light tiles on `input_light` (the faded yellow tiles) in its bottom left corner. The cells that can be Empty are marked with the Empty tile (orange dotted line tile).
![image](https://user-images.githubusercontent.com/70545646/160262006-4fc56c33-bea2-4b6a-9704-db9beb5e7e4d.png)
The door itself (actually the output, in this case) is hard to see, whereas with the old style, this rule was clearer, with a door and some light visible:
![image](https://user-images.githubusercontent.com/70545646/160262011-2f06f94d-5858-4533-a365-b5b0bdcdbbbd.png)

It's also just more work to have to paint these Empty tiles, particularly in a rule like this where it's not immediately clear which cells can have Empty or not when all the layers are stacked up like this.

**Proposed solution**
Allow setting a bool on input layers that works similarly to how `StrictEmpty` works now: any empty cells in that layer that are non-Ignored in any other input layers (i.e. are part of the automatically-defined region) should be treated as Empty rather than ignored.
This would mean that when compiling the rules, the empty cells on these layers should be handled last, to allow all other layers to define the region.

This would make rules with a lot of overlapping layers with Empty easier to read, since it would allow the really important tiles to remain visible.

**Alternatives considered**
Using a custom tileset that has a less intrusive "Empty" tile could keep rules like these easy to read, but then the empty cells are harder to see in rules where highlighting them is important. I think my dotted-line tile on low-opacity layers is an unobtrusive as I can get while still being easy to see where I need it, but it's still distracting in rules like this, especially when the underlying tiles are low-contrast.

For this specific rule, I can hide the layer with the Empty tiles or lower its opacity even more, but that is not a good option where there are a lot of different input layers with different names, each of which need their own Empties.

**Comment by bjorn** [comment]
Hmm, I think this is already exact how `StrictEmpty` behaves in the case of automatically determined input region. So potentially I could close this issue, and just not deprecate this option?

**Comment by eishiya** [comment]
Indeed, it does already seem to work correctly so just not deprecating it is all that's needed.

It might be good to add an alias of it called something like `AutoEmpty`, as `StrictEmpty` doesn't communicate what it does as clearly in the context of the new system.
