### ISSUE TITLE
import in monogame

### ISSUE THREAD

**Issue by lonely-unicorn** [mapeditor/tiled#3321]
Hi

Is there an easy way to import a map in monogame or is this engine not really supported?

**Comment by bjorn** [comment]
According to [the documentation](https://doc.mapeditor.org/en/stable/reference/support-for-tmx-maps/#c-net):

> [MonoGame.Extended](https://github.com/craftworkgames/MonoGame.Extended) has a Tiled map loader and renderer that works with MonoGame on all platforms that support portable class libraries.

[TiledCS](https://github.com/TheBoneJarmer/TiledCS) also mentions MonoGame in its readme, so it's likely also an option. Note that they are looking for an additional maintainer, so if you know your way around C# this good be a good opportunity. :-)

Good luck and please do let us know how it goes!

**Comment by lonely-unicorn** [comment]
Great! I used monogame extended and I got the map loaded in 5 minutes.
Very cool to see how open source projects blend together like magic!
