### ISSUE TITLE
collision editor button?

### ISSUE THREAD

**Issue by lonely-unicorn** [mapeditor/tiled#3324]
Hi

For some reason I can't find the collision editor button as written here https://doc.mapeditor.org/en/stable/manual/editing-tilesets/#tile-collision-editor

button: 
![afbeelding](https://user-images.githubusercontent.com/101529915/162246094-7276c65d-bd80-4516-8d85-e0a004f016da.png)

**Comment by eishiya** [comment]
It is in the toolbar when you're in the Tileset Editor (i.e. have a tileset open for editing). It does *not* appear in the tilesets panel.

**Comment by bjorn** [comment]
The button is visible in the screenshot in the manual, on the tool bar. Are you editing the tileset? If not, first click the small "Edit Tileset" button below the tileset view.

**Comment by bjorn** [comment]
@lonely-unicorn Btw, we have a [Discord server for Tiled](https://discord.gg/39wbTv7), which is probably a better place for getting help with such questions. :-)
