### ISSUE TITLE
scripting "print" function doesn't log to the console anymore #1

### ISSUE THREAD

**Issue by meniku** [mapeditor/tiled#3325]
**Describe the bug**
hey. With Tiled 1.7.something I could use print to output strings to the console when working on scripts, it helped quite a lot with debugging things.
I updated to tiled 1.8.4 and it doesn't seem to print anything to the console anymore.

Maybe I'm missing something?

**To Reproduce**
1. Go to console
2. type print("blubb");
2. See nothing

**Expected behavior**
"blubb" appearing as output on the console

**Specifications:**
 - OS: Mac Os
 - Tiled Version: 1.8.4

**Comment by eishiya** [comment]
You should use `tiled.log` instead of `console.log` and `print`.

**Comment by bjorn** [comment]
Unfortunately, I could not find a way to direct the `console.log`and `print` functions to the Tiled Console view without also directing all other stderr output to the Console, which was causing undesired messages to end up in the Console and Issues views. To see the output of these functions, you'll need to launch Tiled from a terminal, in which case the output will show up there.

However, there has always been a [`tiled.log`](https://www.mapeditor.org/docs/scripting/modules/tiled.html#log) function specifically for writing to the Console view, and a [`tiled.warn`](https://www.mapeditor.org/docs/scripting/modules/tiled.html#warn) and [`tiled.error`](https://www.mapeditor.org/docs/scripting/modules/tiled.html#error) for writing warnings/errors to the Console and Issues views.

**Comment by meniku** [comment]
thanks that helps
