### ISSUE TITLE
UX improvement: I wish to lock single Objects inside ObjectLayer.

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#3332]
**Is your feature request related to a problem? Please describe.**
To prevent mis-clicking and accidentally moving Objects which should not be moved.

**Describe the solution you'd like**
Similar to locking ObjectLayers, I would like to toggle a bool for "Locked" per Object.

**Describe alternatives you've considered**
Currently, I need to make a separate ObjectLayer and lock this one where I put in the (few) sensitive Objects which should not be moved accidentally. More layers, more trouble!

**Comment by bjorn** [comment]
Ah, there was already an issue open about this: #828.
