### ISSUE TITLE
feature: full screen mode

### ISSUE THREAD

**Issue by ghost** [mapeditor/tiled#3334]
**Is your feature request related to a problem? Please describe.**
To'focus on the map without any distractions of widgets or toolbars, in full screen

**Describe the solution you'd like**
A button or key to click centers the map in fullscreen while all other widgets are hidden. Zooming should be done using mouse wheel.
The last selected tool is active in full screen (e.g. draw tiles)

**Comment by eishiya** [comment]
Clear View (default shortcut: `Tab`) hides the tool bars and panels. Full Screen view (default shortcut: `F11`) also gets rid of the title bar.

With these two modes, only the document tab bar and the menu bar remain on screen, taking up very little space. The tab bar makes it easier to switch documents without leaving Clear View, and the menu bar similarly gives you quick access to tools, as well as a way out of Clear View in case you forget the shortcut.

**Comment by bjorn** [comment]
Considering the reporting account was deleted, I'll close this since I think the existing "full screen" options usually suffice. Thanks for summarizing them, @eishiya!
