### ISSUE TITLE
TMX Rasterizer - disable objectgroup rendering

### ISSUE THREAD

**Issue by pazkero** [mapeditor/tiled#3343]
Up to and including Tiled 1.2.5, tmxrasterizer would not render object groups.
For those of us whom use tmxrasterizer to generate minimaps, objects aren't useful in the render.

Ideally, tmxrastrizer should have a command-line option to disable this new behavior.
`--hide-image-layers` and `--hide-object-layers`, perhaps?

This was also discussed [on Discord](https://discord.com/channels/524610627545595904/524610627545595906/969209781493587968).

----
PS. Until Ubuntu 18.04 LTS, Tiled 1.2 would be provided. Ubuntu has a lifetime of 5 years per release, so you can skip a LTS release at the cost of doing a full reinstall instead of dist-upgrade (which never worked for me, anyway).
Now I upgraded to Ubuntu 22.04, which comes with Tiled 1.8 by default, so I'm noticing the differences, and while most of them are good, this one is not :)

**Comment by bjorn** [comment]
I've added the additional options for the upcoming Tiled 1.9. So I guess, they'll be available for you when Ubuntu 26.04 LTS is out? ;-)

Or, use the AppImage that is soon [available here](https://github.com/mapeditor/tiled/actions/runs/2239914699) (at least, I think it includes the `tmxrasterizer` tool, but the AppImage will first need to be extracted using `--squashfs-extract`). Or, the snap package on the edge channel should soon get updated (`snap install tiled --edge`).
