### ISSUE TITLE
Issues with "Pick color from image" with small images

### ISSUE THREAD

**Issue by SpiderDave** [mapeditor/tiled#3348]
1. In the "New Tileset" window, when using the "Pick color from image" button with small images, the image is centered.  The color picker acts as if it's on the left, picking colors as if the image was there.  When trying to pick them from the image directly, it uses some kind of default background color that isn't showing instead `#003039`.

2. (possibly related)
When hovering over a color, the size of the color picker window changes based on the proportional width of the color text (most noticeable with `#ffffff`), which jitters the window.  This is also an issue with smaller images only.

<img src="https://i.imgur.com/VTyeu2N.png">

Steps to reproduce:
1. Create a new tileset
2. Select a small image
3. Use the "Pick color from image" button
4. Mouse over the image and over the area to the left of the image.

 - OS: Windows 7 Pro
 - Tiled Version: 1.8.4

**Comment by eishiya** [comment]
This isn't strictly a small image issue, as it also affects large images, if they're tall enough that they won't fill the entire width of the window when scaled to fit the maximum height of the window..

**Comment by bjorn** [comment]
Thanks for reporting these issues @SpiderDave and @eishiya! I think I fixed all of them in the above change.
