### ISSUE TITLE
Zoom independent point object size

### ISSUE THREAD

**Issue by natebot13** [mapeditor/tiled#3356]
**Is your feature request related to a problem? Please describe.**
Point objects are quite large for low res tile maps. I'm working with an 8x8 tilemap, and the point object covers nearly 6 tiles.

**Describe the solution you'd like**
It would be nice if the point object scaled with the zoom so it stays a consistent size no matter the zoom, much like google maps pins. This way, in order to access an object under the point, I can simply zoom in and it will "shrink" out of the way. This solution does mean that point objects will look a lot bigger when you zoom out, so either a maximum size or some nonlinear scaling could be applied such that points don't cover maps when zoomed way out.

**Describe alternatives you've considered**
An alternative could be to have the point object have a configurable size in the settings, or perhaps just a size relative to the current map's tilesize.

**Comment by bjorn** [comment]
First of all I've taken the simplest route, which is just to ignore viewport transformations for these objects. That will indeed make them stick out a lot when zooming out far. Please let me know whether that's a problem or not. Builds with this change can soon be found at https://github.com/mapeditor/tiled/actions/runs/2421132404.

**Comment by bjorn** [comment]
> In this build I did get a drawing bug after placing a point

Ah, thanks for catching that! Should be easy to fix.
