### ISSUE TITLE
Custom property of type object references the original object, but should not if the reference is also copied.

### ISSUE THREAD

**Issue by smjnab** [mapeditor/tiled#3361]
**Is your feature request related to a problem? Please describe.**
You have an object that is using a custom property of object type and it is referencing another object. If you copy the object, the copy will reference the same object as the original. This works fine and is the expected behaviour.

However, if you at the same time also copy the referenced object, the new copy with the reference keeps referencing the original reference. But, I believe that in this situation you would (almost) always want the reference to be updated to reference the copy of the referenced object.

**Describe the solution you'd like**
Unsure what is best: That it assumes to do the different behaviour by default, when doing a copy of objects with references to other objects ask the user what to do or a setting to toggle it. I believe option 1 is preferable as if you do copy of objects with references to objects that are also copied, the intention is to reference the new objects.

**Describe alternatives you've considered**
None except updating the references manually, which is what I am doing at the moment :) 

Thanks!

**Comment by bjorn** [comment]
Thanks for bringing this up! I had heard this mentioned before but forgot about it again. It's implemented for the next patch release now. :-)

If you'd like a build earlier, you should soon be able to get it from https://github.com/mapeditor/tiled/actions/runs/2344266176 (scroll down to Artifacts).

**Comment by smjnab** [comment]
Works nicely to copy and paste. Tested in map edit, object edit and by copying from one map to another. 

As a note: Using duplicate on objects, or using duplicate on a layer, will not work. It creates a copy that references the old objects.

**Comment by bjorn** [comment]
> As a note: Using duplicate on objects, or using duplicate on a layer, will not work. It creates a copy that references the old objects.

Hmm, yeah I should definitely look into applying the same logic to these actions.
