### ISSUE TITLE
"Groups" of tiles in Tile Objects

### ISSUE THREAD

**Issue by NyakoFox** [mapeditor/tiled#3363]
The Tile Object feature is great for a visual representation of an object, or easy non-grid aligned tile placement. However, it seems to fall short when you want to place down a group of tiles. In the normal stamp mode, you can select a region of tiles in the tile picker and place them all at once, but that isn't the case for Tile Objects, despite still being able to select a region of tiles -- only one gets placed, and it's the last tile in the selection.

While a solution could simply be placing down multiple tile objects at once, I think a much more elegant solution might be allowing a single Tile Object to contain a group of tiles. So when they're placed as a group, they act like a group. Rotated, scaled, stretched, etc. All like a group. This would make using Tile Objects as "decals" much, much easier.

The current workaround I'm using is creating a new tile layer and offsetting it, which leads to A LOT of tile layers which I really don't need. Another idea I had was creating a Tileset specifically for objects like these, so the tile size can fit the size of the group -- however, all of these tiles are different sizes and I'd rather not have to either:
- Make a tileset for each "decal"
- Make the tileset size the size of the biggest "decal" and let the rest have a lot of empty space

I do believe a Tile Object "group" feature could be the most elegant solution. As I mentioned earlier, an alternative implementation would simply be creating multiple Tile Objects when you try to place both at once, however that would be much harder for the user to scale/rotate/transform them all at once.

**Comment by eishiya** [comment]
A planned feature is Tile Atlases (#2863), which will let you define tiles of different sizes within a single tileset image. I think that would be a more elegant solution to this problem. Something similar can already be done by using an Image Collection tileset, but that would require having each object as a separate image.

Once that's implemented, multi-tile objects would only be needed for those cases where the constituent tiles are not contiguous in a single tileset image, in which case Tile Objects would probably need to support arbitrary stamps as their contents, and that's rather out of scope for Tile Objects, I think.

**Comment by pixelart-girl** [comment]
SUCK MY MOTHERFUCKING CLIT

**Comment by bjorn** [comment]
Indeed, multi-tile objects are not currently planned and I think there are better ways of handling that, like tile atlas (#2863) or maybe eventually compound objects (#572). I'll hence close this issue.
