### ISSUE TITLE
Different Problems with imported Keybindings and default ones.

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#3367]
**Describe the bug**
- Empty keybindings get re-assigned after importing (other) keybindings.
- Default keybinding "CTRL+W" can't be used anymore after importig (other) custom keybindings.

**To Reproduce**
1. Reset all Keybindings (CreateTemplateTool is now on "V")
2. Delete Keybinding for (CreateTemplateTool is empty now)
3. Set ObjectSelectionTool to "V".
4. Export Keybindings
5. Reset Keybindings
6. Import Keybindings
7: Bug: CreateTemplateTool is back on "V" (and blocks my ObjectSelectionTool)

**Specifications:**
 - OS: Windows 10 64bit
 - Tiled Version: 1.8.5

**Comment by bjorn** [comment]
I've pushed a fix for the importing of "unset" shortcuts.

> Default keybinding "CTRL+W" can't be used anymore after importig (other) custom keybindings.

Will still need to look into this one. Just to be sure, it would be great if you could test the builds that will become available at https://github.com/mapeditor/tiled/actions/runs/2370558348, so see if that issue persists.

**Comment by bjorn** [comment]
The new builds at https://github.com/mapeditor/tiled/actions/runs/2371784032 should fix the Ctrl+W issue as well. Thanks for reporting these!
