### ISSUE TITLE
Property Types Editor form not saving to disk newly added properties

### ISSUE THREAD

**Issue by ChuckDHead** [mapeditor/tiled#3374]
My OS is Ubuntu 20.04.2 LTS. I'm using v1.8.5 from the snap package at snapcraft.io with full permissions granted. 
The enums and classes added to the menu "View" -> "Property Types Editor" (while a tsx file is open and selected) do not get saved after the app is closed. After restarting Tiled, the previously added properties do not get restored. The "Import" and "Export" buttons works as expected. Object types (from "Object Types Editor" form) do get restored after each restart, but object properties of type "property type" (enums and classes from "Property Types Editor") are casted to other types due to the missing property types.

Steps to reproduce the error:
1. Open Tiled.
2. Open tsx file and select a tsx file tab.
3. Open "View" -> "Property Types Editor".
4. Add an enum and a class.
5. Click on "File" -> "Save"
6. Click on "File" -> "Save all"
7. Close Tiled
8. Reopen Tiled
9. At the tab from the same tsx file, click on "View" -> "Property Types Editor". Last changes are missing.

**Comment by bjorn** [comment]
Yes, this is essentially fixed by 3ac1ca2, which forces you to create a project before using this feature. That'll be included in 1.9, which I hope to release later this month.

**Comment by ChuckDHead** [comment]
If I create a project and save it to a file, then property types do persist. Thanks for the solution. It seems that if I edit manually tmx and tsx files, only object types do persist between restarts but properties not. That behaviour confused me.
Investigating a little bit it seems that object types are stored in the file (~/snap/tiled/current/),local/share/tiled/objecttypes.xml. Every tmx or tsx file without project, or any project opened on Tiled shares the same object types but property types do not get shared. If I edit, add or remove an object from some project, it will affect the rest of the projects opened later: Would be this, then, an expected behaviour? At "objecttypeseditor.cpp" -> "void ObjectTypesEditor::applyObjectTypes()", and "propertytypeseditor.cpp" -> "void PropertyTypesEditor::applyPropertyTypes()", looks like the way objects are managed are different from properties.

**Comment by bjorn** [comment]
@ChuckDHead Yes, that's exactly it. The difference is due to the history, with "object types" being supported for many years already (long before projects were added) and "property types" having just been added in Tiled 1.8 and using the project as the natural storage location.

What I'm aiming for is to remove the "object types" entirely, merging them into the "property types". Then a project will be required to use this feature, but I think that's better than storing them in a hidden global file (which could optionally be changed in the project, but that's quite clumsy).
