### ISSUE TITLE
When Resize Map , the objects in the object-layer will be removed

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#3377]
**Describe the bug**
When Resize Map , the objects in the object-layer will be removed

**To Reproduce**
1. create 2 tile-layers , and 1 object-layer
2. put some objets in  object-layer, and move them to the outside of tiled-area, like image: 
 (see the image-1
3. resize the map
4. the objets will be removed

**Expected behavior**
tile-layer will be resized,  but the objects in the object-layer won't.

**Media**
<img width="153" alt="image" src="https://user-images.githubusercontent.com/288367/171551595-34cb48ef-6fa3-499b-965b-067fa5800228.png">
image-1

**Specifications:**
 - OS: maxOS
 - Tiled Version: 1.8.5

**Comment by bjorn** [comment]
This behavior can be turned on/off using the "Remove objects outside of the map" option at the bottom of the resize dialog:

![image](https://user-images.githubusercontent.com/531764/171574111-66e69383-9c09-4fda-86d9-de1f76486b4c.png)

Or are you resizing the map through "Crop to Selection" or "Autocrop" actions? In that case objects are always removed. Maybe this behavior could be tweaked such that only those objects will be removed, which were not previously outside of the map?

In general I think removing these objects is helpful, but I understand it's not always desired.
