### ISSUE TITLE
Placing new random Terrains Tiles without moving Mouse Cursor

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#3381]
AsIs: 
When placing a TerrainSet, I need to move the MouseCursor out of the desired Tile and back in again to place another random Tile of the same type at the same spot, like shown in the GIF animation below.

![RandomTiles](https://user-images.githubusercontent.com/1249266/172349675-3773bcc2-63b4-44b1-b7f0-10b332d42e17.gif)

ToBe: 
I don't need to move my MouseCursor at all, just clicking on the same spot places another random tile (which fits of course)

// This would be quite helpful to optimize terrain after it has been placed. So when I created a grass landscape I can later improve it by changing here and there some Tiles to other random elements just by clicking on the same spot several times to randomly cycle through different tiles until I like it best.

**Comment by bjorn** [comment]
@UliAbo This turned out to be an easy change, a 1.8 build with this change should be available soon at https://github.com/mapeditor/tiled/actions/runs/2453860763.

**Comment by UliAbo** [comment]
@bjorn Thanks for the lightning fast implementation. Just tested it, works like a charm! 
Actually really nice addon. I keep on clicking until I like the random result.
