### ISSUE TITLE
Several Image Layer and Offset related frustrations

### ISSUE THREAD

**Issue by gvivster** [mapeditor/tiled#3386]
1) My original problem: I need to be able to combine multiple tilesets into one tileset (such as RPGMaker B,C,D,E tilesets). I need to do this for 80+ separate tilesets with similar layouts.

2) My original solution: make tilesets out of every individual B,C,D,E image, add them all to a TMX, and make a metatileset from the TMX.
❌ Result: Bad solution. Lots of extra files, work, and time.

3) My next solution: use Image Layers to add all the PNG images to a single TMX, use the Offset functionality to correctly arrange them so they don't overlap, and make that TMX into a metatileset.
❌ Result: Better workflow, but the resulting .tsx is lengthened by the same amount as the offset, meaning a huge amount of extra blank tiles exist that aren't in the .tmx and I don't want. 

4) Eishiya's proposed solution: "If you size your map to the size of one tileset, the offset image layers shouldn't add any empty space to the map, and it should be the size of just your N tileset images when made into a tileset. You could even make the map 1x1 tiny tile, with image layers it doesn't matter what the map's size is."
❌ Result: a 1x1 map resulted in my tileset being the proper length but only one tile wide. (This makes sense given what I know now.)
❌ Result 2: a map 1 tile high and as many tiles wide as my tileset seemed to work, and I used that going forward. Everything seemed to be fine, but recently I've noticed that now all of my TSX's made that way cut off all but the top row of tiles on the last tileset. I have no idea if a recent update did this.
✔ Result 3: Making the TMX **exactly** the size of **one** of the PNGs resulted in a TSX that has everything rendered correctly with no extraneous tiles.

❌ Although I got to a solution, it was VERY unintuitive, frustrating and time-consuming.

**I wouldn't have had to do any of this if we simply had the option to have an exported image or TSX read only what is within the bounds of the TMX**. I have never done anything in Tiled that would require anything different. I need to able to rely on having the sizes of my exported images and tilesets be what I have set instead of having Tiled decide otherwise.

(This would also solve the problem of having our exported PNGs' 0,0 point changed if we have a negative offset anywhere in our map, a common pitfall where learners get frustrated and stuck.)

[BCDE - Image Layer Metatileset Example Files.zip](https://github.com/mapeditor/tiled/files/8952778/BCDE.-.Image.Layer.Metatileset.Example.Files.zip)

**Comment by bjorn** [comment]
Should be all good now! Let me know if you're still running into problems. :-)
