### ISSUE TITLE
Ignore transparent  pixels when select Image Object 

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#3388]
**Is your feature request related to a problem? Please describe.**
When I select an image object in the object-layer , the transparent pixels will make that too hard to select an image behind the  transparent pixels .

**Describe the solution you'd like**
support an option to enable that "Ignore  transparent pixels when select an image"

**Comment by bjorn** [comment]
It has already been added. Please try the recently released 1.9 Release Candidate. :)

**Comment by bjorn** [comment]
Closing as duplicate of #1477. It was implemented for the next release in 033fdea03e8a17ee38447c249a4ce9214d324c88.
