### ISSUE TITLE
Objects in object layer are positioned differently depending on type (Tile object vs any other)

### ISSUE THREAD

**Issue by ajuc** [mapeditor/tiled#3392]
**Describe the bug**
See the image.

**To Reproduce**
1. Create object layer
2. Add Rectangle object for example at position 0, 0 size 64, 64 and rotation 45 degree
3. Add Tile object at the same position, size and rotation
4. See that they aren't at the same position (see the image for example)

**Expected behavior**
The Tile object should be positioned the same as any other object.

**Example**
![bug_in_tiled_positioning_of_objects](https://user-images.githubusercontent.com/70748/175787343-6cad38ef-3f57-4b2e-8687-38701f8382f5.png)

**Comment by bjorn** [comment]
This difference is historical and for compatibility reasons can't just be fixed as a "bug". However, in [Tiled 1.4](https://www.mapeditor.org/2020/06/20/tiled-1-4-0-released.html) an "Object Alignment" setting was introduced on the Tileset, which can be used to specify top-left alignment for your tile objects, making them consistent with the plain rectangle objects.

**Comment by ajuc** [comment]
Thanks.
