### ISSUE TITLE
Custom Types Editor: Changing "Class of..." is not updated until restarting Tiled.

### ISSUE THREAD

**Issue by UliAbo** [mapeditor/tiled#3398]
I need to restart Tiled when I change entries in "Class of..." within Custom Types Editor. Otherwise the entries don't get updated in lists:
![image](https://user-images.githubusercontent.com/1249266/176215571-2cbadd09-52da-4e0e-8795-4493fa02e3f9.png)

**Specifications:**
 - OS: Win10 64bit
 - Tiled Version: 1.9

**Comment by bjorn** [comment]
> I need to restart Tiled when I change entries in "Class of..." within Custom Types Editor. Otherwise the entries don't get updated in lists.

Ah, I will check the updating of this list, but rather than restarting Tiled, I think it should at least suffice to select a different object.

**Comment by eishiya** [comment]
I ran into this issue recently as well. It's actually enough to just switch the properties view to something else temporarily and then go back to your thing - it's just not updated while it's already open on that object type, it only gets updated when the properties panel is reloaded.
