### ISSUE TITLE
Name label for point object is not aligned properly

### ISSUE THREAD

**Issue by smjnab** [mapeditor/tiled#3400]
**Describe the bug**
Since 1.9, and the change to the size of the point object, the name label is positioned at the top of the old point object size and not at the top of the new smaller point object.

**To Reproduce**
Create a new pointer object, shortcut I.
Give it a name. 
See how the label is not positioned as they are for other objects with name labels.

**Media**
![pointer](https://user-images.githubusercontent.com/17771475/176396342-05733d31-6bff-4aba-8e56-ae5f2bfb8fd1.png)

**Specifications:**
 - OS: KDE Neon (Ubuntu 20.04)
 - Tiled Version: 1.9.0

**Comment by bjorn** [comment]
Ah, I forgot about the label positioning. Thanks for opening an issue about it! Shouldn't be too hard to fix, but may have to wait until when I'm back from holiday.
