### ISSUE TITLE
Can't open TGA file as tileset

### ISSUE THREAD

**Issue by tryphon77** [mapeditor/tiled#3401]
**Describe the bug**
When I open a TGA file produced by pygame, it won't load and I get a "impossible to load" error.
Bug similar to https://github.com/mapeditor/tiled/issues/2013
I have qtga.dll in my plugins directory.
Pygame doesn't write TGA footer at the end of the file, so I added it by hand.

**To Reproduce**
1. Go to 'new tileset'
2. Select tiles-1.tga as source file
3. See error

**Expected behavior**
The tileset should be loaded.

**Media**
[tiles-1.zip](https://github.com/mapeditor/tiled/files/9030427/tiles-1.zip)

**Specifications:**
 - OS: Windows 10
 - Tiled Version: 1.4.3

**Comment by eishiya** [comment]
In the issue you linked, bjorn mentioned that the plugin does not support compressed TGAs, but your file appears to be RLE-compressed (field 3 is `09`, which corresponds to "run-length encoded color-mapped image").

**Comment by bjorn** [comment]
I'll close this issue since adding support for compression to the Qt TGA loader is out of scope and I don't think it's worth introducing another dependency for. Please see if you can use another format use convert to non-compressed TGA.
