### ISSUE TITLE
Tile image rect is not loaded

### ISSUE THREAD

**Issue by devnewton** [mapeditor/tiled#3405]
The tile image rect is ignored at map loading

1. Open examples/forest/forest.tmx
2. See that all image rect in the examples/forest/forest.tsx tileset are ignored

![image](https://user-images.githubusercontent.com/103828758/177594450-4beb6974-7e61-420a-b260-b3177f8c8fdd.png)

Tiled Version: 1.9.0

**Comment by bjorn** [comment]
Oh boy, what a blunder. This broke in 916d7accdb70032fc1e6bc83401480cef8dca5c9, which fixed a regression when adding tiles to an image collection tileset, and which also makes the rectangle adjust when the image of a tile in an image collection is changed.

Maybe this function could just check `mImageRect.isNull() || mImageRect == mImage.rect()`, and then the similar check in `Tileset::setTileImage` can be removed.
