### ISSUE TITLE
Enum custom type have no type in xml

### ISSUE THREAD

**Issue by ironpowertga** [mapeditor/tiled#3410]
**Is your feature request related to a problem? Please describe.**
 Enum custom type have no type in xml so actualy enum look like in xml : 

```xml
<property name="capacity" propertytype="ECapacity" value="DoubleJump"/>
```
all others  types have a type and look like in xml : 

```xml
<property name="Test" type="bool" value="false"/>
<property name="a" type="class" propertytype="Class0"/>
```

**Describe the solution you'd like**
Add new type : enum in the xml file,

```xml
 <property name="capacity" type="enum" propertytype="ECapacity" value="DoubleJump"/>
```

**Comment by bjorn** [comment]
There is no `enum` type. The type for an enum value is actually `string` or `int`, depending on what you configured the enum to get saved as. Your enum is saved as a string, but the `type="string"` attribute isn't written out, since `string` is the default type for property values.
