### ISSUE TITLE
Change from "Type" to "Class" in properties has broken implementation in MonoGame.Extended.Tiled

### ISSUE THREAD

**Issue by differenceclouds** [mapeditor/tiled#3426]
I suppose this is more one for MonoGame Extended folks, but I thought I should let you know because it took me a while to figure out what was going on. Basically, there is a class in MonoGame.Extended.Tiled called TiledMapObject with a field called Type which corresponded with what has been renamed "Class." It only breaks when a .tx file is saved over in the new version of Tiled. I only noticed it when going into the diffs with git.
<img width="456" alt="Screen Shot 2022-07-25 at 7 44 55 PM" src="https://user-images.githubusercontent.com/8020773/180893100-da919157-8422-486a-b89c-3820e0595bc3.png">
<img width="834" alt="Screen Shot 2022-07-25 at 7 38 35 PM" src="https://user-images.githubusercontent.com/8020773/180893103-274198fc-f654-4012-85a6-3318afc74fdb.png">

**Comment by eishiya** [comment]
Indeed, this is for the MonoGame Extended folks and is not a Tiled issue.

There is a Tiled 1.8 compatibility mode in the Project Settings you can use, which will write TMX and TMJ with "type" instead of "class" for Objects and Tiles, you can use that until the parser catches up.

**Comment by differenceclouds** [comment]
The compatibility mode doesn't seem to change this particular thing, or I'm missing something.
