### ISSUE TITLE
Tileset drawing offset combined with tile scaling behaves oddly

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3430]
The drawing offset for tiles seems to behave in a somewhat odd way when using the new (in 1.9) tile render size and fill mode settings: the drawing offset is affected by the tile render size, but not the fill mode.

Here's an isometric map with 16x8 cell size. The tileset has 48x48 tiles and render size set to "map grid", and a render offset of 24,24, i.e. half the tile size. Here's what it looks like when the tileset has fill mode set to "stretch":
![image](https://user-images.githubusercontent.com/70545646/182853868-cccfa17e-b71f-4e66-aa77-3444cab230d3.png)
And here's when it's "preserve aspect ratio":
![image](https://user-images.githubusercontent.com/70545646/182853949-9c313129-4c52-432b-bac0-21738f7ef78f.png)

The tile itself is scaled exactly how I expect in both cases - to 16x8 (x zoom factor) in "stretch" mode, to 8x8(x zoom) in "preserve aspect ratio" mode. But the render offset seems to always be scaled as if it were in "stretch" mode, in both cases the tile is offset by 8,4. This may be what a user may want, so I'm only reluctantly calling this a bug. I don't use this feature, hopefully someone who does can chime in with what they consider intuitive in this scenario.

**Comment by bjorn** [comment]
> This may be what a user may want, so I'm only reluctantly calling this a bug. I don't use this feature, hopefully someone who does can chime in with what they consider intuitive in this scenario.

After looking into this, I think it may indeed not be a bug. What is happening is that "preserve aspect ratio" actually also centers the tile within the target rectangle, and the offset is applied on top of that centering. So the offset is actually applied as 4x4 as one would expect, but with the remaining 4 pixels in the X direction being due to the centering.

Let me know if you feel this could anyway be made more intuitive.

**Comment by eishiya** [comment]
Since I don't normally use this feature, I can't say how it can be made more intuitive, it seems like sensible behaviour already. I think the best thing would be a note about this in the documentation, so that there's no wondering about it. It would also be useful information for people implementing this behaviour in engines.

Perhaps something like:
> Tiles that are scaled due to their tile render size not being "Tile Size" also have their Drawing Offset scaled by the same factor. If the Fill Mode is "Preserve Aspect Ratio", the tile is *centered* in the space available, and its position is added to the scaled Drawing Offset, which can make such tiles appear offset more or less than intended.
