### ISSUE TITLE
Brushes get messed up on Staggered maps

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3431]
When copy+pasting tiles on a staggered maps, if the origin (top left corner) of the brush was on a staggered row, every other row of the brush is pushed in the opposite direction of what's required to account for the staggering. Here, the hexagon of tiles starts on row 1, a staggered row, and copy+pasting it results in a mess:
![image](https://user-images.githubusercontent.com/70545646/182856481-7fd6048e-88f0-48ef-ab6d-852d0aa1f9ea.png)
If the origin of the brush was on a non-staggered row, then stagger compensation works perfectly fine. Here, I redrew my hexagon of tiles starting on row 0, a non-staggered row, and copy+pasted it, it behaves correctly no matter where I try to paint it:
![image](https://user-images.githubusercontent.com/70545646/182857224-dae94183-e352-4142-b2fc-ffdb10b47a93.png)

I don't use staggered maps often so I don't know when this started. I noticed this in 1.9.0, Win64.

My guess is the stagger-compensating code always shifts certain rows in a particular direction based on their coordinates in the brush itself, disregarding where they came from in the source map, which would affect which rows are staggered and which are not.

**Comment by bjorn** [comment]
Problem appears related to there being an odd number of empty rows at the top of the captured area, like this:

![image](https://user-images.githubusercontent.com/531764/225967675-8af005fb-8584-46cc-8f8e-ae008cfeb0ee.png)

**Comment by eishiya** [comment]
> Problem appears related to there being an odd number of empty rows at the top of the captured area

On maps with stagger axis X, it may be related to empty columns instead, that's something to check too.

**Comment by bjorn** [comment]
After being stumped on this for way too long, I eventually located the issue. Should be fixed by #3628.
