### ISSUE TITLE
"Open containing folder" for Tile source images

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3448]
When working on tilesets, the image(s) often need to be edited after putting them in a tileset and seeing them in Tiled. Being able to right-click a tile and "Open containing folder" would speed this iteration process up, especially for Image Collections where there are many images, possibly in different subdirectories.

"Open in default editor" might also be an option (especially for source images that are actually Tiled maps!), but often the actual source file is separate from the flattened file used by the tileset (e.g. a PSD or KRA file), so being able to get to the directory would be useful. Perhaps both could be added?

**Comment by bjorn** [comment]
> Perhaps both could be added?

Good idea, done for next patch release. :-)

**Comment by eishiya** [comment]
Thanks! I noticed this is only added for Image Collections, but it would be nice to have for regular tilesets too, even though it'll just always go to the same place. Tilesheets need to be tweaked too sometimes xP

**Comment by bjorn** [comment]
> Thanks! I noticed this is only added for Image Collections, but it would be nice to have for regular tilesets too, even though it'll just always go to the same place. Tilesheets need to be tweaked too sometimes xP

Maybe it would be better to add it to the context menu of the Image property?

**Comment by eishiya** [comment]
I think it would be easiest to find on the Tile itself, so I think it should be available there at least for Image Collections. I don't see harm in having it there on tilesheets to, but if you don't want it there, then maybe have it on the tiles for Collections, *and* on the Image properties for both types of tileset?

**Comment by bjorn** [comment]
Alright, the action is now also available for tileset image based tilesets. :-)
