### ISSUE TITLE
Crash when deselecting string property in Custom Types Editor

### ISSUE THREAD

**Issue by Froyok** [mapeditor/tiled#3465]
**Describe the bug**
In the Custom Types Editor window, when deselecting a string property member value by clicking on another custom Type, Tiled always crash.

**To Reproduce**
1. Open the Custom Types Editor window (**View** > **Custom Types Editor**)
2. Click on **Add Enum** and name it **Enum1**
3. Click on **Add Class** and name it **Class1**
4. Click on **Add Member** (for **Class1**)
5. Choose **string** as type, name it as you want
6. Click on the empty field of the string member
7. Click on the **Enum1** in the **Custom Types** list
8. Crash

**Expected behavior**
No crash.

**Media**
Video of the crash repro steps in my project: [tiled_crash_custom_types.webm](https://user-images.githubusercontent.com/6290387/187053517-e4441b02-c9e4-46d7-90b6-1cb126527d42.webm)

**Specifications:**
 - OS: Linux Manjaro (AMD Radeon RX 5600 XT navi10, LLVM 14.0.6, DRM 3.44, 5.17.15-1-MANJARO)
 - Tiled Version: 1.9.0, 1.9.1 (from AUR: https://archlinux.org/packages/community/x86_64/tiled/)

**Notes:**

- Apologies if it's a duplicate, I did a quick search of open and closed issues but didn't see a mention of the Custom Types Editor.
- Seems to only happen when deselecting by clicking on an Enum, even if empty.

**Comment by bjorn** [comment]
Thanks for the detailed report! Apparently this bug has existed since Tiled 1.3 (introduced in a8b0255cf1adb975b9a8f6811ef222e6a51e87cd), but maybe it wasn't easy or possible to trigger it before. Should be fixed now for the upcoming Tiled 1.9.2.
