### ISSUE TITLE
Automapping: Output objects don't contribute to output region

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3473]
When determining what parts of a rule to output, Automapping only seems to look at tiles, and if objects are present, they are only output if they overlap an output *tile* as well. This is unintuitive and feels like a bug.

For example, these two rules that look for "NonEmpty" on the input layer and have just an object output layer will output *nothing*:
![image](https://user-images.githubusercontent.com/70545646/190914184-faf63d15-eb57-488e-b6e7-6097da8908fc.png)
My input, unmodified by this rule:
![image](https://user-images.githubusercontent.com/70545646/190914424-d7845a48-7d7c-444b-9cb9-73e32a11e8aa.png)
But this is what I **expect**:
![image](https://user-images.githubusercontent.com/70545646/190914526-3f585309-43f4-4c64-a180-cca3a8bd5913.png)

And this rule that outputs a tile in a location other than the object's location will output the tile, but not the object:
![image](https://user-images.githubusercontent.com/70545646/190914252-adc941d1-9476-4276-948f-290ecab756a2.png)
![image](https://user-images.githubusercontent.com/70545646/190914469-7ce1a45b-27ca-4ce9-961e-19a50c9ff05f.png)

However, this rule, which outputs both an object and a tile at the same location, will work correctly:
![image](https://user-images.githubusercontent.com/70545646/190914301-5c1c4ec9-32d0-4145-800c-a1ec6db4c08a.png)
![image](https://user-images.githubusercontent.com/70545646/190914386-2116a217-481a-4599-818b-e86361f32d43.png)

If I want to make a rule that outputs *only* an object at some location, I have to have a tile output layer with a tile on it that will be ignored:
![image](https://user-images.githubusercontent.com/70545646/190914484-564a54c5-7335-4854-bd2a-79336c43872d.png)
![image](https://user-images.githubusercontent.com/70545646/190914498-a600e3c7-b409-4ee5-b943-3190e72f5d33.png)

I think any tile touched by an output object should count as part of the output region. For example, this small object would add the selected tile to the output region:
![image](https://user-images.githubusercontent.com/70545646/190914658-ffefa35b-f692-4a69-8205-6fa51cc29f13.png)
Care would need to be taken with non-rectangular objects. For example, these are the total regions I expect these two rules to have:
![image](https://user-images.githubusercontent.com/70545646/190914902-9f71202a-62e3-46fd-b342-e4887e7e27d0.png)
But if the bounding box of the object is used instead of checking whether a tile actually overlaps the object, then the regions would be like this, and considered a single rule:
![image](https://user-images.githubusercontent.com/70545646/190914972-b1b813f3-d7e9-4ec5-b4ef-d824bdcb1436.png)

Alternatively, if it's intended that objects don't contribute to the output region (e.g. to avoid specifically this kind of weirdness with the shapes), then the fact that they don't contribute and may need output Tile Layers with Ignore tiles to output should be documented (I can add it to my rewrite draft).

**Comment by bjorn** [comment]
> Care would need to be taken with non-rectangular objects. For example, these are the total regions I expect these two rules to have:

The linked PR fixes the general issue, but does not make AutoMapping work correctly for polygon or polyline objects. I believe since it works only with the object's rectangle, it will handle these as if they were point objects.

**Comment by eishiya** [comment]
The PR fixes the issue as described, but misses the same thing for `DeleteTiles`: that still only deletes those Objects that overlap a tile in the match region. This rule will continue stacking Rectangles even with `DeleteTiles` enabled:
![image](https://user-images.githubusercontent.com/70545646/223128652-b7615234-e507-4858-bb81-5e39ffaba498.png)
But this one will not:
![image](https://user-images.githubusercontent.com/70545646/223128861-6be71e73-9304-4b4a-a40c-11304de94c76.png)

I checked the behaviour for Polygons, and it indeed looks like their bounds are handled like Points. If their position is exactly at the edge of the cell (e.g. because of Snapping), they're not considered part of the region, their origin point has to be *within* the cell. Using the bounding box would indeed be a big improvement over this, and I guess it's fair enough to use that rather than doing something more complex, given how rare this scenario is.

**Comment by bjorn** [comment]
@eishiya I haven't tested it yet, but isn't this behavior consistent with tile layers? As far as I know, `DeleteTiles` has always only worked for regions where any of the input layers have any tiles. This is to have it only delete tiles in regions which can be expected to be "refreshed" by Automapping rules.

**Comment by eishiya** [comment]
`DeleteTiles` is the only way to delete Objects from a map via AutoMapping, so preventing the stacking of Objects due to repeated Automapping is one of the uses I expected of it. I could be wrong, as I never found `DeleteTiles` intuitive even for just tile work xP
