### ISSUE TITLE
Scripting: Dialog radio buttons

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3478]
When building Dialogs, it's sometimes useful to have radio buttons. Their functionality can be achieved script-side with checkboxes, or they can be replaced with combo boxes (dropdowns), so this isn't an important feature, but it would be neat.

Qt Dialogs allow QRadioButtons and QButtonGroups, but this functionality is not currently exposed to the scripting API.
Relevant Qt docs: https://doc.qt.io/qt-5/qradiobutton.html

The challenge with radio buttons is that they derive their usefulness from belonging to a group with other radio buttons, and only one can be selected at a time. Qt considers all QRadioButtons that have the same parent to be part of the same group, but since the Dialog API doesn't give you direct control over the parent widgets and adds columns and rows automatically, this can get confusing. Perhaps rather than exposing QRadioButtons directly, the Dialog API could support only something like RadioButtonGroup that behaves a lot like a QComboBox (value changed signals, a single tooltip for the whole thing, a constructor that takes all the labels at once, etc), but which consists of a QButtonGroup and a bunch of QRadioButtons under the hood?

**Comment by bjorn** [comment]
I see Aseprite [supports radio buttons](https://aseprite.org/api/dialog#dialogradio), but how does it put them in groups?

Maybe it would make sense to simply automatically group any consecutively added radio buttons?

**Comment by solerante** [comment]
>When building Dialogs, it's sometimes useful to have radio buttons. Their functionality can be achieved script-side with checkboxes, or they can be replaced with combo boxes (dropdowns)

It's already possible to create a dropdown selection dialog by script?

**Comment by eishiya** [comment]
> It's already possible to create a dropdown selection dialog by script?

Yes, though they're called ComboBoxes: https://www.mapeditor.org/docs/scripting/classes/Dialog.html#addComboBox

**Comment by dogboydog** [comment]
I'll pick this up.  I'm thinking you'll just provide a list of all the radio button labels and I'll figure out how to respond to the selection change signals and provide an example

**Comment by eishiya** [comment]
I think handling it similarly to how ComboBoxes are handled would be good: treat each radio button group as a single widget, provide a method to add items to this group, and provide signals for the selected item changing. It'll probably be more complex under the hood since it's not just a wrapper for single Qt widget, but I think interacting with it just like with a combobox would be pretty simple for script authors.
