### ISSUE TITLE
Moving object order

### ISSUE THREAD

**Issue by gamedevsam** [mapeditor/tiled#351]
The new Objects Tab is awesome! One thing that seems to be missing is the ability to sort the order of the objects. This would ideally change the draw order of the objects in the editor, so we can layer objects (as well as layers) in an intuitive way.

I can then mirror the draw order of the map file during load-time, so we can chose the draw order of objects within layers.

![2013-02-08_1841](https://f.cloud.github.com/assets/420996/141438/cfad0b14-7249-11e2-84a6-ee8e4d159cf1.png)

**Comment by Yukitty** [comment]
I see you can set the Drawing Order on an object layer to Manual, but there's still no controls for actually changing the order of the objects anywhere in the GUI, nor any documentation I could find..? Am I missing something? How do you use this?

**Comment by bjorn** [comment]
@Yukitty The controls are a bit hidden. They are currently only available on the context menu of the object in the map view. There should of course also be controls to change the order in the Objects dock, which is partly covered by issue #888.

In addition it probably makes sense to have these context menu actions also available on the tool bar, but this needs a kind of context-sensitive tool bar which does not exist currently.

**Comment by Yukitty** [comment]
Ah. Silly me. Here I was clicking, dragging, mashing random keys, holding ctrl+arrows, everything I could on the objects layer tree window thing... Even looked up the keyboard shortcuts on the wiki page, nothing.

:S Figures you'd have to do something as obscure as right click on the object itself.
Thanks so much for the quick response!

**Comment by bjorn** [comment]
@Yukitty Ah, you made me remember there are also keyboard shortcuts for these actions. They are `PageUp`, `PageDown`, `Home` and `End`. I think you can guess their meaning in this context. And of course I forgot to update the keyboard shortcuts wiki page... The shortcuts may also change again in the next version, because some people are annoyed that changing selected layer now takes two keys.

**Comment by Yukitty** [comment]
I'm running into more trouble with that still, eesh. :( #889
