### ISSUE TITLE
Cannot export map as a specific file format on Fedora 36

### ISSUE THREAD

**Issue by Serif-7** [mapeditor/tiled#3516]
**Describe the bug**

I have no way of exporting a map as a lua file. adding `.lua` onto the end doesnt work, the file is just XML. Here is the output:

```
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.9" tiledversion="1.9.2" orientation="orthogonal" renderorder="right-down" width="30" height="20" tilewidth="16" tileheight="16" infinite="0" nextlayerid="4" nextobjectid="1">
 <tileset firstgid="1" source="tileset.tsx"/>
 <group id="2" name="Group 1">
  <objectgroup id="3" name="Object Layer 1"/>
  <layer id="1" name="Tile Layer 1" width="30" height="20">
   <data encoding="csv">
2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
2,3,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
2,3,3,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,2,2,2,2,2,
2,2,2,2,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,2,2,2,2,1,1,
2,2,2,2,2,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,2,2,2,2,2,1,1,
2,2,2,2,2,2,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,3,3,3,3,3,2,1,1,
2,2,2,2,2,2,2,2,2,4,4,4,4,4,4,4,4,4,4,4,4,3,3,3,3,3,2,2,1,1,
2,2,1,1,1,1,1,1,2,2,1,1,1,1,1,1,2,2,2,2,3,3,3,3,3,3,2,2,1,1,
2,2,1,1,1,1,1,1,2,2,1,1,1,1,1,1,2,2,2,2,3,3,3,3,3,3,2,2,1,1,
2,2,1,1,1,1,1,1,2,2,1,1,1,1,1,1,2,2,2,2,3,3,3,3,3,3,2,2,1,1,
2,2,1,1,1,1,1,1,2,2,1,1,1,1,1,1,2,2,2,2,3,3,3,3,3,3,2,2,1,1,
2,2,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,2,2,1,1,
2,2,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,3,3,2,2,2,2,2,2,1,1,
2,2,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,
2,2,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,
2,2,1,1,1,1,1,1,2,2,2,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,2,2,2,
2,2,1,1,1,1,1,1,2,2,2,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,2,2,2,
2,2,2,2,2,2,2,2,2,2,2,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,2,2,2,
2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
</data>
  </layer>
 </group>
</map>
```

I can't export as JSON or CSV either. When I try to export it opens up my file manager, Nautilus, but it doesnt have an option to export as a specific file type like windows file manager. Here's a screenshot.

![Screenshot from 2022-11-01 20-15-01](https://user-images.githubusercontent.com/29221564/199368939-20cfcdd2-2bac-4e98-bf83-fdeaf18603c4.png)

The only button just filters what files are shown, it doesnt affect the file itself. Adding a file extension doesnt do anything.

**To Reproduce**
0. Be on GNOME
1. Go to 'Export as'
2. Export file
3. Open file

**Expected behavior**
I want to be able to export my maps a .lua file.

**Specifications:**
 - OS: Fedora 36
 - Tiled Version: 1.9.2

**Comment by Serif-7** [comment]
So, I didn't realize I needed plugins to do this. I tried installing those, but for some reason they aren't available in the fedora repos, so I just installed from itch.io and all was well.

Don't install Tiled from the fedora repos.

**Comment by bjorn** [comment]
Actually, the Lua, CSV and JSON plugins are part of the [core plugins](https://src.fedoraproject.org/rpms/tiled/blob/rawhide/f/tiled.spec#_214) in the Tiled RPM.

But probably you need the following fix, for Tiled to find the plugins, which is likely not yet included in the current stable release since it was made just yesterday: https://src.fedoraproject.org/rpms/tiled/c/65de6e7d1267c2279abbe1fae8d87cef7c21896e?branch=rawhide
