### ISSUE TITLE
I have written a tool to make big object, it may be useful for Tiled. 

### ISSUE THREAD

**Issue by garfeng** [mapeditor/tiled#3518]
https://github.com/garfeng/tiled_big_tile_object

Group objects with same size to one image

![image-20221103225551089](https://user-images.githubusercontent.com/19792314/200107320-9e6e08fc-081a-4aa6-a4d2-25d7fbbdf494.png)

**Comment by eishiya** [comment]
It's called Tiled, not "TileD". The RPG Maker community keeps using this incorrect spelling for some reason xP Tiled has never had a capital D.

If you'd like to publicize this useful script for the community, this is the wrong place to do it. The [tiled-extensions](https://github.com/mapeditor/tiled-extensions) is a repository for Tiled scripts. You can either submit your script as a PR, or you can submit a PR to the README with a link to your script. You can also post about it on the Tiled forum.

**Comment by garfeng** [comment]
> It's called Tiled, not "TileD". The RPG Maker community keeps using this incorrect spelling for some reason xP Tiled has never had a capital D.
> 
> If you'd like to publicize this useful tool for the community, this is the wrong place to do it - the forum is a better place.
> 
> There is also the [tiled-extensions](https://github.com/mapeditor/tiled-extensions) repository for Tiled scripts. If this were a Tiled script, you could submit it there. Making it a Tiled script might actually be a better way to implement this, as you could generate the image(s) and tileset for the user, save them, and open them in Tiled for the user. You also could rely on the map to determine where there are tiles, so the script would not trip up on Objects that are transparent partway through.

Thank you for remind me about that. I have changed the title. I will go to the forum later.
