### ISSUE TITLE
Scripting: Provide a way to prompt user for a file or directory

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3537]
### Problem
Sometimes scripts need to prompt the user for a file. There are three main ways to do this in Tiled currently:
- `tiled.prompt()` lets the user enter the path as just a string. It's very inconvenient since there's no file selector, but has the advantage that the script will automatically wait until the user is done.
- Read a custom property from some relevant asset in Tiled. File custom properties let the user choose the file with a file picker and let the user save their preference in the asset., but they have to be set up before the script runs, which isn't always appropriate, and not all scripts deal with already-open assets.
- Create a Dialog and add a FilePicker widget to it. This is usually the best option (and can be combined with the previous one when appropriate), but has one major disadvantage: Tiled doesn't wait for Dialogs to finish, the function that creates and shows the Dialog will finish long before the Dialog does. This makes Dialogs inappropriate for functions that have to return something and need to wait for the input before they do, such as `MapFormat.read()` or some action that has to be complete before the user is allowed to do anything else.

There is currently no way to prompt the user for a file with a proper file picker that also allows the script to block until input is received. Blocking would be convenient for many kinds of scripts, and is necessary for the `read()` methods of custom formats.
Using a Dialog or any kind of user prompting is of course not ideal for `read()` in general since these methods may be called via CLI, but it would be convenient to have the option when the function is called in a context that allows it, so that opening files can be silent in CLI (and fail if additional configuration is required) and more interactive in the GUI.

### Solutions
I can think of two possible solutions to this:
- Provide something like `tiled.promptForFile()` that prompts specifically for a file or directory and blocks until the user is done, similar to how `tiled.prompt()` and `tiled.confirm()` work.
- Add the option to make Dialogs block after they're shown and until they're done. The actual handling of the Dialog would still be done via signals like at present, but after the signals for the dialog have been handled, control flow would return to just after `Dialog.show()` was called, allowing the script to use any values that were set in the signal handlers. Blocking Dialogs should not allow the user to interact with other Tiled UI until they are done, just like `tiled.prompt()` and its siblings.

I think allowing Dialogs to be blocking would be the better solution, as it would be useful for much more than just files. For example, a blocking Dialog can be used to configure the work of an Action without letting the user call any other actions until it's done. However, `tiled.promptForFile()` is a lot simpler compared to setting up a whole Dialog and signal callbacks, so it's possible that it's worth implementing both.

**Comment by bjorn** [comment]
> * Add the option to make Dialogs block after they're shown and until they're done.

This may be already possible. Can you try to call [`dialog.exec()`](https://doc.qt.io/qt-6/qdialog.html#exec)?

**Comment by eishiya** [comment]
> > * Add the option to make Dialogs block after they're shown and until they're done.
> 
> This may be already possible. Can you try to call [`dialog.exec()`](https://doc.qt.io/qt-6/qdialog.html#exec)?

Oh, interesting! Looks like that does work! In this example, "Returning!" doesn't get printed until after the Dialog is finished.
```js
dialog.exec();
tiled.log("Returning!");
```

I guess this is just a matter of documentation, then :]

**Comment by bjorn** [comment]
> Edit: Just to complete one of the use case examples though - if one were to use this in MapFormat.read(), is there a way to reliably know whether it's appropriate/possible to spawn a Dialog (i.e. not being called via CLI)?

Hmm, at the moment you could check if the script was run from CLI by checking a UI-specific property. `tiled.mapEditor` should be `null` in this case, for example.

> What even happens with Dialog scripts in a CLI environment?

I guess they should just work. The main difference with scripts run on CLI is that Tiled's main window isn't created, but that shouldn't prevent a script from spawning a dialog.

**Comment by eishiya** [comment]
Thanks for the info!

Should we close this issue, or do you think a dedicated file prompt is also worth adding?

**Comment by bjorn** [comment]
I think a dedicated file prompt is still worth adding. :-)

**Comment by dogboydog** [comment]
From bjorn:
>The problem with this task is mostly deciding on the API.

I don't know the best design for this method, `tiled.promptForFile`. 

The implementation would use either this or some other static methods available bjorn mentioned. 

https://doc.qt.io/qt-6/qfiledialog.html

There are a lot of parameters to expose here, including: 

* starting directory
* dialog mode - open or save
* some subset of [Options](https://doc.qt.io/qt-6/qfiledialog.html#Option-enum) - i think a lot of these like disabling native OS dialogs wouldn't really need to be exposed personally. I could see ShowDirsOnly being useful. 
* defaultSuffix 
* filter - only show certain extensions

I see a few different ways this could be implemented, but not sure what is best 

In Godot, when I open a file dialog in an editor plugin, it looks like this: 
```csharp 
            var dialog = new EditorFileDialog();
            dialog.AddFilter(filter);
            dialog.Mode = EditorFileDialog.ModeEnum.SaveFile;
            dialog.WindowTitle = windowTitle;
            dialog.Connect("file_selected", this, fileSelectedHandler);
            GetEditorInterface().GetViewport().AddChild(dialog);
            dialog.Popup_(new Rect2(50, 50, 700, 500));
```
            
But this model is similar in complexity to just creating a Dialog with a filepicker IMO 

Aseprite seems to just expect you to use their scripted Dialog system and add a file picker component to it: 
https://aseprite.org/api/dialog#dialogfile

Then you have the alternative of just combining all into one method which returns the filepath, or  null if the user cancels: 
            
```js
            var jsonFile = tiled.promptForFile('/my/dir/',  QFileDialog.AcceptSave, '.json', ,'.json;.tmj', QFileDialog::DontConfirmOverwrite)
            if (jsonFile == null){
              tiled.log("User canceled file selection");
              }
```
            
But there are so many options to consider here, many of which scripters might not always care about, so you might end up with a bunch of empty string arguments when you use this.

Wondering what other people's thoughts are.

**Comment by eishiya** [comment]
It might make sense to have several methods for the different types of things, just for readability, e.g. `promptOpenFile`, `promptSaveFile`, `promptForFolder` or something. This way, fewer parameters would be needed for each method:
- `promptOpenFile` would need filename filters and a bool whether multiple files are allowed, and a starting directory.
- `promptSaveFile` would need filename filters, and *maybe* the confirm overwrite option (I'd personally be fine if it always confirmed), and a starting directory.
- `promptForFolder` would need a bool whether multiple files are allowed, and the starting directory.

I think it's fine if only a subset of the options are exposed, similar to how tiled.prompt and tiled.confirm are very basic. FilePicker should be where the complexity goes IMO, and it's currently missing some options I think xP

**Comment by eishiya** [comment]
I actually wrote a bit about window titles initially but seems I removed it before posting. I don't think they're necessary, and tiled.prompt, etc don't have them IIRC. I think it would be fine to just have default titles for each of the three types of prompts, e.g. "Save File", "Open File", "Select Folder".

**Comment by dogboydog** [comment]
I suppose I was just thinking it might be important to show the context of why a save/open file dialog is popping up, unless it would be preceded in the script by something that explained the process to the user like another prompt. But for some scripts it would probably be obvious just from the action name.

**Comment by eishiya** [comment]
I think in most cases it should be obvious, and where it's not (e.g. something with multiple prompts), a Dialog is probably more appropriate.

**Comment by bjorn** [comment]
> I don't think they're necessary, and tiled.prompt, etc don't have them IIRC.

Well, [`tiled.prompt`](https://www.mapeditor.org/docs/scripting/modules/tiled.html#prompt) definitely has an optional `title` argument. I do think it can be helpful to set a title, so ideally it'd be an optional argument.

And I think we can have `tiled.promptOpenFiles` for the plural version instead of making that a bool argument.

I may prefer to just mimic the names of the static `QFileDialog` functions, as in:

* `tiled.getExistingDirectory`
* `tiled.getOpenFileName`
* `tiled.getOpenFileNames`
* `tiled.getSaveFileName`

**Comment by dogboydog** [comment]
I don't know about anyone else but I find those method names more confusing. I would read them thinking getOpenFileName means "get the filename of the open map/tileset in the editor" for example

**Comment by bjorn** [comment]
Hmm, maybe that's in particular because they're prefixed with `tiled.`? Alternatively we could introduce a `FileDialog` API, either with the static methods:

* `FileDialog.getExistingDirectory`
* `FileDialog.getOpenFileName`
* `FileDialog.getOpenFileNames`
* `FileDialog.getSaveFileName`

Or alternatively to use it as follows:

```js
let dialog = new FileDialog()
dialog.title = "..."
dialog.filter = "..."
if (dialog.exec()) {
    let fileNames = dialog.selectedFiles
}
```

**Comment by dogboydog** [comment]
I think the FileDialog.<staticMethod> approach might make it clearer than it being under `tiled.` if we want to keep the original names.  Creating an instance of the FileDialog sounds fine too but it seemed like maybe part of the reason to ask for this separately from Dialogs was brevity / simplicity of the scripting call. Wonder what eishiya thinks of those two options

**Comment by eishiya** [comment]
I'd rather keep them under `tiled` for brevity and consistency with `tiled.prompt`, and for that they will need names that don't match the Qt options.

A separate dialog for multiple files would be fine, but what about multiple directories? Or is that not possible? If it's possible, then I'd rather have bool parameters in the file and directory functions rather than two extra functions.

Having an optional title parameter is also fine by me :D

**Comment by dogboydog** [comment]
At least for the static methods I don't see a way to allow for one or more directories to be opened. Maybe I'm missing something 

https://doc.qt.io/qt-6/qfiledialog.html#getExistingDirectory

**Comment by eishiya** [comment]
Ah, well then xP In that case, a separate method for multiple files is fine, but I think the name will need to be more different than a single letter, e.g. `promptOpenMultipleFiles`, so that it's clearer what it does.

**Comment by dogboydog** [comment]
Proposed syntax 
```js
    tiled.promptForDirectory(string defaultDir, string dialogTitle = '')
    tiled.promptOpenMultipleFiles(string defaultDir,  string filters = '',  string dialogTitle = '')
    tiled.promptOpenFile(string defaultDir,  string filters = '', string dialogTitle = '')
    tiled.promptSaveFile(string, defaultDir, string filters = '',  string dialogTitle = '')
```

**Comment by eishiya** [comment]
`promptOpenMultipleFiles` should probably return an array of strings (even if only one file is selected) rather than a single string.

The parameter order looks good to me.
Should the "don't prompt for overwrite" option be provided for promptSaveFile, perhaps?

On a tangential note, the Projects API uses "Folder" while FileInfo and Process use "Directory" xP That doesn't seem ideal.

**Comment by dogboydog** [comment]
Whoops, yeah you're right the multiple files should return an array.  I'm not sure about the "don't prompt for overwrite".  I'm not sure that level of control is required or if there is a scenario where it's really that useful. 

I prefer the term directory I guess vs, folder, but I don't feel strongly about it

**Comment by bjorn** [comment]
> I prefer the term directory I guess vs, folder, but I don't feel strongly about it

Yeah, I think we should go with "directory". That the project folders are called folders is based on the more common terminology in UI...
