### ISSUE TITLE
Object selection/movement disregards object layer

### ISSUE THREAD

**Issue by nickgravelyn** [mapeditor/tiled#354]
I have two object layers in my maps, one for my "entities" (player, baddies, etc) and one for metadata regions. Objects on these two layers can overlap but this causes issues as Tiled doesn't properly filter objects by layer for selection and movement. So if I have my Entity layer selected I can still select and move objects on the Metadata layer. This makes it really hard for me to edit my maps since I frequently have metadata regions that overlap entity objects.

**Comment by JoeCreates** [comment]
Just noting that this seems to be implemented and can probably be closed? @bjorn

**Comment by bjorn** [comment]
@JoeCreates Yeah, at least layer locking has been implemented in the meantime. But there is no option to limit object interaction to those of the selected layer(s), which I guess would still make sense? Essentially I'd like to introduce a companion option to "highlight current layers", which would essentially automatically consider any non-selected layers as locked.

**Comment by JoeCreates** [comment]
Ah that would be good.
