### ISSUE TITLE
Inconsistency between (x,y) coordinates alignment for objects of the same layer

### ISSUE THREAD

**Issue by sromeroi** [mapeditor/tiled#3545]
**Describe the bug**
I'm doing some tests with Tiled and noticed that objects in the same object layer might have different "rendering coordinates" depending on the View > Snapping configuration. Adding 2 tiles from the same tileset (with "Object Alignment": "top-left"), it is possible to end with one referencing top-left coordinates and the other one having bottom-left coordinates without a way to determine where to render them.

**To Reproduce**
- Create an object layer.
- View > Snapping > No snapping
- Load a tileset with "Object Alignment" option set to "top-left".
- Place a tile somewhere in the intersection between 4 tiles.
- View > Snapping > Snap to grid
- Place a second tile somewhere (aligned to grid).
- The resulting json layer (when saved) has the first object coordinates relative to bottom-left position while the grid-aligned object has top-left coordinates and there's no property in the object to know where should I render them, so if I choose one of them (i.e. top-left), the other one is rendered in a wrong position. 
- Note that the tileset used is already using the "Object Alignment" property set to "top-left", but the object that is not aligned to grid is ignoring this setting and using bottom-left coordinates.
- When I iterate layers that are TileLayers / Collection of images I know that images that are bigger than the tile size are bottom-left aligned, but "tile objects" are all of the tile size...
- So, when I iterate the objects to render them and find the 2 tiles, I don't know if they are top-left or bottom-left aligned.

**Expected behavior**
I'm missing an  "alignment": "top-left" or "bottom-left" property in the object that is automatically set by Tiled to inform the developer whats the tile alignment.

This way, when I iterate objects, I can know if it's top-left or bottom-left aligned and render it (or use it) in the proper coordinates.

**Media:**

![01-Tiled](https://user-images.githubusercontent.com/4025149/207597848-51cbf0f7-5cb7-44dd-a009-7297d19a7b9b.png)

![02-test](https://user-images.githubusercontent.com/4025149/207597855-82f4bbe5-2453-40a4-8817-5348b6708206.png)

(In the test above, I'm rendering the objects as the last layer to see them propertly, in Tiled the order is BG -> OBJECTS -> TILES).

**Specifications:**
 - OS: Linux KUbuntu 22.04.1 LTS
 - Tiled Version: Tiled-1.9.2_Linux_x86_64.AppImage

**Comment by sromeroi** [comment]
To provide some context, I already search and found the following statements:



> All non-Tile Objects have top left alignment.
> 
> To get the alignment for a Tile Object, you'd check its tile's tileset, since that's where that data comes from. Duplicating it in the Tile Object would be redundant.

Hi. Thanks for your reply.

Yes, in the rendering code I check the tileset, and the tileset says top-left.

In my example above (screenshots attached to the issue) I have 2 tiles (from the same tileset, top-left aligned) I render them but tile 1 is bottom-left and tile 2 is top-left, so tile 1 appears in the wrong position.

**Comment by eishiya** [comment]
Look at what happens **in Tiled** when you change the object alignment for a Tileset after placing some Tile Objects. Tiled will draw the objects according to the *current* object alignment, so the visual positions of previously placed Tile Objects **will change** when you change the object alignment. You need to *pick an alignment*, and position your objects according to it. This may mean repositioning some previously placed objects.

This is because Tile Object alignment always comes from the tileset. This is intended.

If what you see in Tiled doesn't match what you see in your game, then your parsing or rendering code probably doesn't match what Tiled is doing, you're probably rotating around the wrong point.

**Comment by sromeroi** [comment]
> If what you see in Tiled doesn't match what you see in your game, then your parsing or rendering code probably doesn't match what Tiled is doing, you're probably rotating around the wrong point.

I think that's the answer: the rotation. My object has 90º rotation and pygame is rotation using the surface center as pivot point. Is it a different pivot point in Tiled?

**Comment by eishiya** [comment]
> > If what you see in Tiled doesn't match what you see in your game, then your parsing or rendering code probably doesn't match what Tiled is doing, you're probably rotating around the wrong point.
> 
> I think that's the answer: the rotation. My object has 90º rotation and pygame is rotation using the surface center as pivot point. Is it a different pivot point in Tiled?

Tiled rotates about the object alignment point.

**Comment by sromeroi** [comment]
> > I think that's the answer: the rotation. My object has 90º rotation and pygame is rotation using the surface center as pivot point. Is it a different pivot point in Tiled?
> 
> Tiled rotates about the object alignment point.

Closing the issue thanks to this comment.
