### ISSUE TITLE
Use Tiled without a display?

### ISSUE THREAD

**Issue by victorbnl** [mapeditor/tiled#3549]
**Is your feature request related to a problem? Please describe.**

I was not sure whether I'd make a bug report or feature request, but I'm putting it as a feature request as this is probably a minor bug which affects nobody except me.

So basically when Tiled is ran without a display server, it crashes with the following log:

```
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

zsh: IOT instruction (core dumped)  DISPLAY= tiled --help
```

However, in my game, I commit the level project .tmx file on the repo, and converting it to csv is part of the building process, via `tiled level.tmx --export-map level.csv`. Nevertheless it goes without saying a build process should not require a display server. For instance, I'm trying to use it in a CI/CD.

**Describe the solution you'd like**

I'd like Tiled to support being started without a display server for simple tasks such as exporting a level or a tileset.

**Describe alternatives you've considered**

Using a third-party tool for doing so. Maybe I could write some converter in Python using pytmx or something.

**Comment by eishiya** [comment]
This came up before: #1788. Tiled relies on Qt features that require X. That issue recommends using xvfb to run Tiled, e.g. `xvfb-run tiled --platform offscreen` (I haven't used it myself, but this command reportedly worked).

Related issue: #512

**Comment by victorbnl** [comment]
It's weird that I didn't come across these issues during my researches. Thanks for the workaround!

**Comment by bjorn** [comment]
There's a note about this at the bottom of https://doc.mapeditor.org/en/stable/manual/export/, but I understand it can be easily missed.
