### ISSUE TITLE
Enabling hardware acceleration in QT 6 builds makes images not render (win 10, 64 bit)

### ISSUE THREAD

**Issue by dogboydog** [mapeditor/tiled#3578]
**Describe the bug**
There's a rendering issue for me and eishiya under recent QT 6 windows builds. With hardware acceleration turned on many types of images don't seem to render in the map editor.  Interestingly, the tileset editor does render the tiles. 

**To Reproduce**
1. Open a map under windows 10
2. Ensure hardware acceleration is turned on 
3. Observe tiles and image collection  objects not rendering
4. Turn off hardware acceleration 
5. Observe the images now starting to render

**Expected behavior**
The images should render.

**Media**
Map editor
![image](https://user-images.githubusercontent.com/9920963/219762176-d398880e-c4f6-4eb8-8282-849c568be974.png)
Tileset editor 
![image](https://user-images.githubusercontent.com/9920963/219762741-aae10b83-0a7b-450a-b5c7-caba9d29e811.png)

Have not tested on any other OS yet.
  
**Specifications:**
 - OS: Windows 10
 - Tiled Version: confirmed in latest master and also the Feb 15 "version less than" scripting utility commit has the issue

**Comment by eishiya** [comment]
I was initially able to reproduce this, but after restarting Tiled, everything is working fine.

**Comment by dogboydog** [comment]
For me the issue persists after installing graphics drivers updates, rebooting,  and trying to restart Tiled a few times

**Comment by dogboydog** [comment]
Reproduced on a Debian Linux VM as well. 
![image](https://user-images.githubusercontent.com/9920963/219820641-773e32f0-fe3b-4599-ad7e-8b7345ef02d8.png)
![image](https://user-images.githubusercontent.com/9920963/219820664-e03aef50-0e68-4244-b4cd-e6534e1641fb.png)

**Comment by bjorn** [comment]
> Interestingly, the tileset editor does render the tiles.

Well, the tileset editor never uses hardware rendering. That option is limited to the map editor. :-)

Apart from being new in Qt 6, the issue appears to have something to do with the use of `QPainter::drawPixmapFragments`. When I disable that the rendering is fixed. So potentially something broke in case of multiple calls to this function.

**Comment by bjorn** [comment]
Hmm, this still worked fine in Qt 6.3.2, so it's a regression somewhere in Qt 6.4. :-(

**Comment by bjorn** [comment]
Reported as https://bugreports.qt.io/browse/QTBUG-111416.

**Comment by dogboydog** [comment]
Thanks, it's fixed for me in the newest build
