### ISSUE TITLE
Major Grid doesn't work for staggered maps

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3583]
On Staggered maps, it looks like every grid line is rendered as if it were a Major Grid line, making the major grid impossible to see.

Compare Isometric vs Isometric (Staggered), no other settings changed:
![image](https://user-images.githubusercontent.com/70545646/220209927-cc3535a6-7d34-472b-b54d-a454b60d9d31.png)![image](https://user-images.githubusercontent.com/70545646/220209944-da0242b7-003d-463c-8070-b0e1bcf037f0.png)
Note how the grid lines in the staggered map are all as thick as the major grid lines in the non-staggered map.

**Reproduce**
1. Set the major grid to something larger than 1x1, but small enough that you can clearly see the major grid lines, e.g. 10x10
2. Create an Orthogonal or Isometric map that's larger than the Major Grid, so you can see the grid lines
3. Observe the clear visual distinction between regular and major grid lines
4. Change the map orientation to Isometric (Staggered) or to Hexagonal (Staggered)
5. Observe how *every* grid line appears thick like a major grid line

This was reported via Discord on Tiled 1.9.2 on MacOS. I was able to reproduce it in Tiled 1.9.1 (Qt5) and 2023.02.17 (Qt6) on Win10 x64.

**Comment by bjorn** [comment]
It's not supported because I wasn't sure how that should be rendered. Which lines would you expect to be "major" for staggered (or hexagonal, since that's the same renderer) maps? Probably it would be a staggered line rather than a straight diagonal one?

**Comment by eishiya** [comment]
I would expect the line to be staggered, that would make it easiest to gauge distances along a particular row/column.

I'm curious why all the grid lines on staggered maps are currently rendered bolder than the plain grid lines on non-staggered maps xP

**Comment by bjorn** [comment]
> I'm curious why all the grid lines on staggered maps are currently rendered bolder than the plain grid lines on non-staggered maps xP

Before major grid was implemented, the grid had alpha 128. When the major grid feature was implemented, it was changed to 96 for non-major lines and 192 for major lines. Rather than using the old opacity for staggered, it currently just renders all lines as major, which is why the grid got a bit brighter since a1a9e180ef1bdf141986f5e24e98a7f6d84cec80.

I think the way I'm currently drawing the hex/staggered grid may not really make it easy to render the major lines differently, but I will have a look.
