### ISSUE TITLE
Tool previews laggy after hardware acceleration is turned on

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3584]
Tool previews, such as the stamp brush preview, become laggy after hardware acceleration is turned on, **even if it's turned back off**.
Restarting Tiled after turning hardware acceleration off and not turning it back on again "fixes" the issue, and the tool previews follow the mouse cursor without delay again.
The lag is slight, but it's enough to be quite annoying. It feels like it's perhaps a frame or so behind.

In this GIF, I first have a freshly started Tiled with no hardware acceleration, there's no lag. Then, I turn on hardware acceleration and the lag appears. Then, I turn it off and the lag persists.
![cursorlag](https://user-images.githubusercontent.com/70545646/220211320-ffaba37f-9979-4b56-9a5a-707301d4b794.gif)

Encountered on Tiled 1.9.1 and 2023.02.17 (Qt6) on Win10 x64.

**Comment by bjorn** [comment]
It's an issue I had known about for a while, and I was about to reply it was a Qt issue, but then I found out a way to restore the non-OpenGL state so it should be fixed by #3587. :-)

**Comment by eishiya** [comment]
So if I understand correctly, the lag with hardware acceleration is a Qt issue and can't be fixed?
Glad to hear that at least the part where the lag sticks around into software rendering can be fixed.

**Comment by bjorn** [comment]
> So if I understand correctly, the lag with hardware acceleration is a Qt issue and can't be fixed?

It might be worth looking into whether it can be reduced, even when hardware acceleration is kept on. But I think this lag is mostly due to the vsync.

**Comment by bjorn** [comment]
@eishiya You may want to test the builds of PR #3588 to test if it helps with the lag (it does in my case) and whether the additional stuttering when using arrow keys to scroll is too much (I think disabling vsync may have to be made optional...).

**Comment by bjorn** [comment]
> I don't see a difference with that build, the cursor is still laggy with hardware acceleration on.

Ok, since it apparently doesn't work reliably and when it works there may be some stuttering, I'm leaving out that change for now, and just merged the change that properly disables hardware acceleration again.
