### ISSUE TITLE
Scripting: `Dialog.SameWidgetRows` not working as expected

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3607]
When adding various widgets to a Dialog with row mode `Dialog.SameWidgetRows` (the default), new rows aren't always created when they should be.

It seems that the type of the previous widget is only checked (to potentially add a new row) for the 2nd widget onwards, the first widget in each row will not cause a break no matter what's added after it.

For example, if I make a Dialog like this:
```javascript
let dialog = new Dialog("Same Widget Rows Test");
dialog.newRowMode = Dialog.SameWidgetRows; //Just for clarity. This is the default newRowMode.

dialog.addTextInput("Text input");
dialog.addTextInput("Text input");
dialog.addButton("Button");
dialog.addTextInput("Text input");
dialog.addButton("Button");
dialog.addCheckBox("Checkbox");
dialog.addTextInput("Text input");
dialog.addCheckBox("Checkbox");
dialog.addCheckBox("Checkbox");
dialog.addButton("Button");
dialog.addButton("Button");
dialog.addCheckBox("Checkbox");
dialog.addCheckBox("Checkbox");
dialog.addButton("Button");
dialog.addButton("Button");
dialog.addCheckBox("Checkbox");
dialog.addComboBox("ComboBox", ["option"]);
dialog.addButton("Button");

dialog.show();
```
I **expect** a Dialog that looks like this:
![image](https://user-images.githubusercontent.com/70545646/224149918-4812ce9e-bbcf-4a5a-ba9a-1f3f84b7f46d.png)
But what I actually get is this:
![image](https://user-images.githubusercontent.com/70545646/224149691-43b6ea69-be2a-4f6e-95b1-a7018319e0eb.png)

I observed this behaviour in 1.9.1 (Qt5) and in a 2023.03.07 nightly (Qt6), on Windows 10.

**Comment by bjorn** [comment]
Thanks for the nice reproducible example script! Should be fixed now in linked PR. :-)

**Comment by eishiya** [comment]
Thanks! I had a go at the new build and removing manual addNewRow() calls from my various Dialogs, and now it looks like only Labels "break" the same widget row rule, just like they're supposed to.
