### ISSUE TITLE
Unable to build 1.10.0

### ISSUE THREAD

**Issue by jubalh** [mapeditor/tiled#3613]
I fail to build the latest 1.10.0 release with Qt6.

Note:
The [readme](https://github.com/mapeditor/tiled/blob/master/README.md) still lists Qt5 deps only. Are the build instructions up to date? The [release notes](https://www.mapeditor.org/2023/03/10/tiled-1-10-released.html) sound like Qt6 should be default now.

You can see my build recipe here: https://build.opensuse.org/package/view_file/games:tools/tiled/tiled.spec?expand=1
And the result here: https://build.opensuse.org/package/live_build_log/games:tools/tiled/openSUSE_Tumbleweed/x86_64

I get a various errors like:

```
[   74s] + qbs setup-toolchains --detect
[   74s] Trying to detect gcc...
[   74s] Profile 'x86_64-suse-linux-gcc-12' created for '/usr/bin/x86_64-suse-linux-gcc-12'.
[   74s] Trying to detect clang...
[   74s] No clang toolchains found.
[   74s] Trying to detect IAR toolchains...
[   74s] No IAR toolchains found.
[   74s] Trying to detect KEIL toolchains...
[   74s] No KEIL toolchains found.
[   74s] Trying to detect SDCC toolchains...
[   74s] No SDCC toolchains found.
[   74s] Trying to detect COSMIC toolchains...
[   74s] No COSMIC toolchains found.
[   74s] Trying to detect DMC toolchains...
[   74s] No DMC toolchains found.
[   74s] Trying to detect WATCOM toolchains...
[   74s] No WATCOM toolchains found.
[   74s] Making profile 'x86_64-suse-linux-gcc-12' the default.
[   74s] + qbs qbs.installPrefix:/usr projects.Tiled.useRPaths:false
[   74s] Build graph does not yet exist for configuration 'default'. Starting from scratch.
[   74s] Resolving project for configuration default
[   75s] Detecting Qt installations...
[   75s] WARNING: Could not find any qmake executables in PATH. Either make sure a qmake executable is present in PATH or set the moduleProviders.Qt.qmakeFilePaths property to point a qmake executable.
[   75s] ERROR: /home/abuild/rpmbuild/BUILD/tiled-1.10.0/dist/distribute.qbs:10:1 Error while handling product 'distribute':
[   75s] /home/abuild/rpmbuild/BUILD/tiled-1.10.0/dist/distribute.qbs:16:5 Dependency 'Qt.core' not found for product 'distribute'.
[   75s] /home/abuild/rpmbuild/BUILD/tiled-1.10.0/src/karchive/karchive.qbs:3:1 Error while handling product 'karchive':
[   75s] /home/abuild/rpmbuild/BUILD/tiled-1.10.0/src/karchive/karchive.qbs:7:5 Dependency 'Qt.core' not found for product 'karchive'.
```

Even though qt6-core-devel >= 6.4.2 is required in the spec file.
Any hints would be welcome.

**Comment by bjorn** [comment]
> The [readme](https://github.com/mapeditor/tiled/blob/master/README.md) still lists Qt5 deps only. Are the build instructions up to date? The [release notes](https://www.mapeditor.org/2023/03/10/tiled-1-10-released.html) sound like Qt6 should be default now.

There is no default Qt, it just picks whatever is in your path or Qbs profile. The release notes meant the binaries I'm releasing have been updated to Qt 6. But Tiled should still compile fine against Qt 5.12 or higher as well.

Regarding the error, it says "WARNING: Could not find any qmake executables in PATH". Could you check whether there is a qmake in the PATH? If there isn't, then either the package providing qmake needs to be installed, or you might try to use `qbs setup-qt <path to qmake> <profile name>` and then build Tiled with that profile.

**Comment by jubalh** [comment]
> WARNING: Could not find any qmake executables in PATH

Ah I did this locally already but forgot to push. But even with qmake present it still doesn't build due to the other errors.
I updated the build in the build system so you can see it at:
https://build.opensuse.org/package/live_build_log/games:tools/tiled/openSUSE_Tumbleweed/x86_64

It's those `[   19s] /home/abuild/rpmbuild/BUILD/tiled-1.10.0/src/libtiled/libtiled.qbs:194:9 Dependency 'Qt.gui' not found for product 'test_staggeredrenderer'.` etc things.

**Comment by jubalh** [comment]
> According to your list of dependencies, you're trying to compile Tiled against Qt 6, but in the PATH there is a Qt 5 qmake. Maybe it is because of the BuildRequires:  libqt5-qtbase-common-devel in the spec?

Yes, this is what I meant above with mixing. For some reason I can't find a `qmake` binary and neither a `qmake-qt6` binary in no package. I can only find the `qmake-qt5` binary in `libqt5-qtbase-common-devel`.

I wasn't yet able to find somebody who explain to me why we don't have a `qmake-qt6` in our repos. But I'm no Qt expert so I figured maybe `qmake-qt5` can handle both qt5 and qt6.

Seems like the best would be if I drop the Qt6 dependencies and go back to Qt5 and then can use the qmake-qt5.

**Comment by jubalh** [comment]
Aha, I have the right dependency already added `qt6-base-common-devel` but the binary name is now `qmake6` and it seems like it doesn't detect that automatically.

**Comment by jubalh** [comment]
```
[    5s] + cd tiled-1.10.0
[    5s] + qbs setup-toolchains --detect
[    5s] Trying to detect gcc...
[    5s] Profile 'x86_64-suse-linux-gcc-12' created for '/usr/bin/x86_64-suse-linux-gcc-12'.
[    5s] Trying to detect clang...
[    5s] No clang toolchains found.
[    5s] Trying to detect IAR toolchains...
[    5s] No IAR toolchains found.
[    5s] Trying to detect KEIL toolchains...
[    5s] No KEIL toolchains found.
[    5s] Trying to detect SDCC toolchains...
[    5s] No SDCC toolchains found.
[    5s] Trying to detect COSMIC toolchains...
[    5s] No COSMIC toolchains found.
[    5s] Trying to detect DMC toolchains...
[    5s] No DMC toolchains found.
[    5s] Trying to detect WATCOM toolchains...
[    5s] No WATCOM toolchains found.
[    5s] + qbs setup-qt /usr/bin/qmake6 defprof
[    5s] Creating profile 'defprof'.
[    5s] Setting profile 'x86_64-suse-linux-gcc-12' as the base profile for this profile.
[    5s] + qbs config defaultProfile defprof
[    5s] + qbs qbs.installPrefix:/usr projects.Tiled.useRPaths:false
[    5s] Build graph does not yet exist for configuration 'default'. Starting from scratch.
[    5s] Resolving project for configuration default
[    5s] Setting up Qt at '/usr/bin/qmake6'...
[    5s] Qt was set up successfully.
[    6s] ERROR: /home/abuild/rpmbuild/BUILD/tiled-1.10.0/dist/distribute.qbs:10:1 Error while handling product 'distribute':
[    6s] /usr/share/qbs/imports/qbs/Probes/GccProbe.qbs:56:16 Error: Error running '/usr/bin/x86_64-suse-linux-g++': execve: No such file or directory
[    6s] /home/abuild/rpmbuild/BUILD/tiled-1.10.0/src/karchive/karchive.qbs:3:1 Error while handling product 'karchive':
[    6s] /usr/share/qbs/imports/qbs/Probes/GccProbe.qbs:56:16 Error: Error running '/usr/bin/x86_64-suse-linux-g++': execve: No such file or directory
[    6s] /home/abuild/rpmbuild/BUILD/tiled-1.10.0/src/libtiled/libtiled.qbs:4:1 Error while handling product 'libtiled':
[    6s] /usr/share/qbs/imports/qbs/Probes/GccProbe.qbs:56:16 Error: Error running '/usr/bin/x86_64-suse-linux-g++': execve: No such file or directory
[    6s] /home/abuild/rpmbuild/BUILD/tiled-1.10.0/src/libtiledquick/libtiledquick.qbs:3:1 Error while handling product 'libtiledquick':
[    5s] + cd tiled-1.10.0
[    5s] + qbs setup-toolchains --detect
[    5s] Trying to detect gcc...
[    5s] Profile 'x86_64-suse-linux-gcc-12' created for '/usr/bin/x86_64-suse-linux-gcc-12'.
[    5s] Trying to detect clang...
[    5s] No clang toolchains found.
[    5s] Trying to detect IAR toolchains...
[    5s] No IAR toolchains found.
[    5s] Trying to detect KEIL toolchains...
[    5s] No KEIL toolchains found.
[    5s] Trying to detect SDCC toolchains...
[    5s] No SDCC toolchains found.
[    5s] Trying to detect COSMIC toolchains...
[    5s] No COSMIC toolchains found.
[    5s] Trying to detect DMC toolchains...
[    5s] No DMC toolchains found.
[    5s] Trying to detect WATCOM toolchains...
[    5s] No WATCOM toolchains found.
[    5s] + qbs setup-qt /usr/bin/qmake6 defprof
[    5s] Creating profile 'defprof'.
[    5s] Setting profile 'x86_64-suse-linux-gcc-12' as the base profile for this profile.
[    5s] + qbs config defaultProfile defprof
[    5s] + qbs qbs.installPrefix:/usr projects.Tiled.useRPaths:false
[    5s] Build graph does not yet exist for configuration 'default'. Starting from scratch.
[    5s] Resolving project for configuration default
[    5s] Setting up Qt at '/usr/bin/qmake6'...
[    5s] Qt was set up successfully.
[    6s] ERROR: /home/abuild/rpmbuild/BUILD/tiled-1.10.0/dist/distribute.qbs:10:1 Error while handling product 'distribute':
[    6s] /usr/share/qbs/imports/qbs/Probes/GccProbe.qbs:56:16 Error: Error running '/usr/bin/x86_64-suse-linux-g++': execve: No such file or directory
[    6s] /home/abuild/rpmbuild/BUILD/tiled-1.10.0/src/karchive/karchive.qbs:3:1 Error while handling product 'karchive':
[    6s] /usr/share/qbs/imports/qbs/Probes/GccProbe.qbs:56:16 Error: Error running '/usr/bin/x86_64-suse-linux-g++': execve: No such file or directory
[    6s] /home/abuild/rpmbuild/BUILD/tiled-1.10.0/src/libtiled/libtiled.qbs:4:1 Error while handling product 'libtiled':
[    6s] /usr/share/qbs/imports/qbs/Probes/GccProbe.qbs:56:16 Error: Error running '/usr/bin/x86_64-suse-linux-g++': execve: No such file or directory
[    6s] /home/abuild/rpmbuild/BUILD/tiled-1.10.0/src/libtiledquick/libtiledquick.qbs:3:1 Error while handling product 'libtiledquick':
````

at https://build.opensuse.org/package/live_build_log/games:tools/tiled/openSUSE_Tumbleweed/aarch64

**Comment by bjorn** [comment]
Could it be that you're somehow missing a C++ compiler? It seems it may only have found a C compiler.

**Comment by Vogtinator** [comment]
I guess for some reason qbs detects and tries to use `x86_64-suse-linux-gcc-12` instead of `gcc-12`. There is no `x86_64-suse-linux-g++-12`, but there is `g++-12`.

**Comment by bjorn** [comment]
Right, in that case running `qbs setup-toolchains g++-12 gcc`  instead of `qbs setup-toolchains --detect` should do the trick.

**Comment by jubalh** [comment]
Thanks guys, that was it.

**Comment by bjorn** [comment]
@jubalh That's great! And thank you for maintaining the openSUSE Tiled package! :-)

**Comment by jubalh** [comment]
@bjorn is there a specific thing I need to pass to qbs to install `libtiled.so` etc into a certain dir? It places them in `/usr/lib` but we need `/usr/lib64` or `/usr/libexec` (depending).

**Comment by bjorn** [comment]
@jubalh The install path for `libtiled` is set up here:

https://github.com/mapeditor/tiled/blob/06c0d8b7e61297174c3a4cb9843e83ba7cf86da4/src/libtiled/libtiled.qbs#L205-L213

So, at the moment there is unfortunately no option to have it install to `lib64`. I also could not find any way to override this property from the command-line (for example, I'd have expected `products.libtiled.qbs.installDir:lib64` to have worked, but in my tests that didn't work, possibly because this property is only set within a specific `Group`).

So for packaging Tiled 1.10, I think your only option is to patch up the relevant parts of the Qbs files. For future releases, I can add appropriate options to the top-level project for convenience. Just let me know exactly what options you need.

**Comment by jubalh** [comment]
I used:

```diff
Index: tiled-1.10.0/src/libtiled/libtiled.qbs
===================================================================
--- tiled-1.10.0.orig/src/libtiled/libtiled.qbs
+++ tiled-1.10.0/src/libtiled/libtiled.qbs
@@ -209,7 +209,7 @@ DynamicLibrary {
                 else
                     return "bin"
             else
-                return "lib"
+                return "lib64"
         }
         fileTagsFilter: "dynamiclibrary"
     }
```

Which placed the one lib into `/usr/lib64/libtiled.so`. The other still in `/usr/lib/libtilededitor.so` though. The plugin libs are in `/usr/lib/tiled`.

**Comment by bjorn** [comment]
> The other still in `/usr/lib/libtilededitor.so` though.

For the one you'd need to patch up this part:

https://github.com/mapeditor/tiled/blob/06c0d8b7e61297174c3a4cb9843e83ba7cf86da4/src/tiled/libtilededitor.qbs#L604-L612



> The plugin libs are in `/usr/lib/tiled`.

That would require patching up this part:

https://github.com/mapeditor/tiled/blob/06c0d8b7e61297174c3a4cb9843e83ba7cf86da4/qbs/imports/TiledPlugin.qbs#L39-L46

**Comment by jubalh** [comment]
Thanks!
Depending on architecture `libtiled.so` and `libtiled.so, are in /usr/lib or /usr/lib64 now. Plugins are in `/usr/lib/tiled/plugins/` or `/usr/lib64/tiled/plugins`.
Spec file and patch are at https://build.opensuse.org/package/show/games:tools/tiled

**Comment by bjorn** [comment]
I noticed the Fedora package is using the [following hack](https://src.fedoraproject.org/rpms/tiled/blob/f37/f/tiled.spec#_187), btw:

```sh
mkdir -p %{buildroot}%{_libdir}
[ "%{buildroot}%{_prefix}/lib" = "%{buildroot}%{_libdir}" ] || mv -v %{buildroot}%{_prefix}/lib/* %{buildroot}%{_libdir}
```

However, I have now also just finished adding an option which can be used like `projects.Tiled.libDir:lib64`, to change the lib dir without needing patches or hacks: https://github.com/mapeditor/tiled/commit/2aff750ef501705da2080aed218b4cc95826f8ba
