### ISSUE TITLE
Hexagonal grid with odd side lengths is not drawn correctly

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3623]
When drawing the grid on a "Hexagonal (Staggered)" map, if the side length is an odd number, the grid is drawn incorrectly. Here are screenshots of such a grid on a map with 16x16 tiles and hex side length 1:
Stagger axis Y:
![image](https://user-images.githubusercontent.com/70545646/225969540-42ce0e3a-9005-43ad-a373-f1f1784803d9.png)
Stagger axis X:
![image](https://user-images.githubusercontent.com/70545646/225969470-fbbaa0c0-82f6-4c4d-b6d2-07473d008fa2.png)

**Expected** appearance (faked by doubling all the sizes, i.e. 32x32 with side length 2, and zooming out):
Stagger axis Y:
![image](https://user-images.githubusercontent.com/70545646/225970097-ddfb5884-722f-4eea-a734-eccaa9e958ae.png)
Stagger axis X:
![image](https://user-images.githubusercontent.com/70545646/225970197-d07cc503-e4e9-4ca9-a4de-3c55d487917b.png)

Even side lengths look just fine, it's just odd ones that are weird.

**Comment by AtlaStar** [comment]
![image](https://user-images.githubusercontent.com/3477783/226012023-a7bcd547-1e3a-4846-adc4-ebbb88269df5.png)
It appears to do this for all odd lengths. Image is using stagger axis X with length of 5

**Comment by bjorn** [comment]
With the fix at #3625, the 16x16 with Stagger Axis Y and Hex Side Length of 1 now looks like:

![image](https://user-images.githubusercontent.com/531764/226341386-f7783eb0-c57a-436a-bef5-c8879446ab44.png)

And with Stagger Axis X:

![image](https://user-images.githubusercontent.com/531764/226341428-1165432f-2d31-4509-ab65-71e095a529d3.png)
