### ISSUE TITLE
Include custom tile properties in .tscn (Godot 4) export

### ISSUE THREAD

**Issue by keharriso** [mapeditor/tiled#3652]
**Is your feature request related to a problem? Please describe.**
When exporting a tilemap as a .tscn (Godot 4) file, the custom tile properties of the tileset aren't present in the output.

**Describe the solution you'd like**
I would like to see the tile properties be added to the .tscn file as a custom property layer of type Dictionary. Supported property types like strings, numbers, and booleans would automatically be added to the generated .tscn file under the `sub_resource type="TileSetAtlasSource"` tag.

*I am working on implementing this feature myself, but would also appreciate any insight from people with a better understanding of the project.*

**Comment by bjorn** [comment]
Implemented in #3653.
