### ISSUE TITLE
GameMaker Studio export docs use "Type" instead of "Class"

### ISSUE THREAD

**Issue by eishiya** [mapeditor/tiled#3660]
The GMS [1.4](https://doc.mapeditor.org/en/stable/manual/export-gmx/) and [2.3](https://doc.mapeditor.org/en/stable/manual/export-yy/) export documentation advises the user to set the "Type" field of objects and tiles, which is confusing since Tiled 1.9+ calls this field "Class".

This should be a simple change, but I'm reluctant to make the edits myself because I know nothing about GMS and what most of the text means.

Links to the documentation files for those willing to tackle this change:
1.4: https://github.com/mapeditor/tiled/blob/master/docs/manual/export-gmx.rst
2.3: https://github.com/mapeditor/tiled/blob/master/docs/manual/export-yy.rst

**Comment by bjorn** [comment]
This was addressed in 6b0d055cdf428328f51e6ccaffed25958d2c4451, thanks!
