### ISSUE TITLE
Godot 4 scene export - rotated and/or flipped tiles aren't properly exported

### ISSUE THREAD

**Issue by ZelCloud** [mapeditor/tiled#3662]
**Describe the bug**

The rotated and flipped tiles in an exported Godot 4 scene (tscn) seem to be improperly exported / corrupted. Everything looks fine in tiled itself.

**To Reproduce**
1. In Tiled create a tilemap with a few flipped and rotated tiles.
2. Export as "Godot 4 Scene files (*.tscn)".
3. Open scene in Godot.

**Expected behavior**

I'd expect the tiles and layout to look the same in Godot as it does in Tiled.

**Media**

How the tilemap looks like in Tiled, with the arrangement on the left and the base tile alone on the right.
![tiled_zhhErEoAMN](https://user-images.githubusercontent.com/9022106/232332089-9404ef9d-e9c1-4409-98c6-4276e667db25.png)

How the resulting scene looks like in Godot after its exported.
![Godot_v4 0 2-stable_win64_V9EsrI0Z2j](https://user-images.githubusercontent.com/9022106/232332145-52062db5-04a8-417e-920f-b5e9105ff1b0.png)

**Specifications:**
 - OS: Windows 10 64bit
 - Tiled Version: 1.10.1
 - Godot Version: 4.0.2

**Comment by eishiya** [comment]
It looks like you missed setting the `exportAlternates` property that allows you to export flipped tiles, see the docs here: https://doc.mapeditor.org/en/stable/manual/export-tscn/#tileset-properties

Godot 4 does not support flipping tiles, so flips/rotations must be exported as separate tilesets, which is what that property does.
