### ISSUE TITLE
How can i access my property via javascript code

### ISSUE THREAD

**Issue by leijinwei** [mapeditor/tiled#3663]
i added new property for tile in c++, how can i access this property via javascript code。

**Comment by bjorn** [comment]
Can you provide a bit more context? How did you add a new property in C++? Are you modifying Tiled itself and wondering how to expand the scripting API?

**Comment by leijinwei** [comment]
yes, i add some new property for Tile，and i want accees it via scripting API。

**Comment by leijinwei** [comment]
it must be some where to configure，but I haven't found it yet  ：）

**Comment by leijinwei** [comment]
Thanks a lot, this helped me
