### ISSUE TITLE
Automaping doesn't work. I need your help to explain my problem. I really hope you can help me, because your program looks amazing.

### ISSUE THREAD

**Issue by matrixxonek** [mapeditor/tiled#3684]
**Describe the bug**
I don't know why, but automaping doesn'a work in my project. I created rules and all stuff i need, but when i use ctrl + m nothink is happening.

**Specifications:**

 - OS: [Windows 10]
 - Tiled Version: [1.10.1]

**Comment by eishiya** [comment]
You've probably just messed up either your set-up (rules.txt, etc) or your rules. In the future, if you're asking a question or looking for help, please don't mark your post as a bug. Also, the forum or Discussions area is a better place for questions.

You will need to provide more information before anyone can help. Here are some trouble-shooting steps you can try:

1. Save your working map, then ctrl+m. Does the map get marked as modified with a `*` in the tab name? If it does not, then your set up is probably wrong - maybe you forgot to include your rules map in your rules.txt file? In other bad set-up scenarios, Tiled should report an error. If it does get marked as modified, then your rules are running, but aren't producing the results you expect.
2. Check your layer names. The target layer name portion of your input and output layer names must match your desired layers *exactly* - check the capitalisation and spelling carefully. Rules with `input_Ground` will not work if your working map has a layer called "ground" instead.
3. If you have `regions` layers, delete them. The presence of `regions` layers causes Tiled to use the old Automapping style, which has some quirky behaviours that make it hard to troubleshoot rules, and they are supported only for backwards compatibility, you should never need them for newly made rules.
4. Tiles must match *exactly*, this includes the orientation - make sure the tiles in both your rules and in your working map aren't flipped or something. You can check the flip flags on a tile in a tile layer by hovering over it and looking for the letters after the tile ID in the status bar.

If none of those are the cause, then you'll need to show your rules and working map, as the problems are probably with your actual rules.

**Comment by matrixxonek** [comment]
The reason of my problem was very easy. I got bad name of layer in my working map. To all people who have the same problem: remember that the layer name in working map should be exactly the same as in Rulemap but without "input_". So when u use name "input_a" in Rulemap u should name your layer "a" in your working map.
