### ISSUE TITLE
Tiled is overwriting file from third tab when file in second tab is saved.

### ISSUE THREAD

**Issue by seanmorris** [mapeditor/tiled#3687]
**Describe the bug**

Tiled is writing incorrect file.

**To Reproduce**

I have three files open. When I save the file in the second tab, the file in the third tab is overwritten and the undo history is destroyed. The files are **not** symlinked. 

I've been able to recover the file by scanning my disk raw, and its no longer happening after restarting tiled.

**Expected behavior**
I expect this not happen.

**Specifications:**
 - OS:  Debian Bookworm
 - Tiled Version: 1.7.1

**Comment by bjorn** [comment]
I'm sorry to hear this happened to you, but I'm afraid there's nothing I can do about this issue if there is no way to reproduce it. It is the first time I hear about such an issue as far as I remember.

You're also reporting this against a version of Tiled that is over 2 years old. I don't remember changing anything that might have been related to such an issue in this time, but I'd still recommend upgrading (it seems Debian Bookworm should provide 1.8.2, and more up-to-date versions could be installed through [Flatpak](https://flathub.org/apps/org.mapeditor.Tiled) for example).

Please feel free to reopen if you can provide any additional information.
