### ISSUE TITLE
request: rotate tile

### ISSUE THREAD

**Issue by pixelartgirl** [mapeditor/tiled#3702]
Rotate tile after selecting it on the tilemap

**Comment by bjorn** [comment]
You can rotate the current stamp using buttons on the toolbar or with shortcut (Z or Shift+Z). Workflow to rotate an already placed tile:

* Right-click to pick the tile from the map onto the current stamp
* Z to rotate stamp
* Click to place rotated stamp

**Comment by pixelartgirl** [comment]
The toolbar buttons don't work, only the keyboard keys

**Comment by bjorn** [comment]
Let's consider this a duplicate of https://github.com/mapeditor/tiled/issues/3703#issuecomment-1550002466.
