### ISSUE TITLE
request: mirror tile

### ISSUE THREAD

**Issue by pixelartgirl** [mapeditor/tiled#3703]
After tile select on tilemap, allow mirror tile operation: horizontal or vertical

**Comment by bjorn** [comment]
You can rotate the current stamp using buttons on the toolbar or with shortcut (X or Y). Workflow to rotate an already placed tile:

* Right-click to pick the tile from the map onto the current stamp
* X or Y to flip stamp
* Click to place flipped stamp

**Comment by pixelartgirl** [comment]
The toolbars button don't work

**Comment by bjorn** [comment]
> The toolbars button don't work

This button? Remember that it applies to the current stamp.

![image](https://github.com/mapeditor/tiled/assets/531764/d718bf54-3632-4c36-b517-adc2f0e62e54)

I just tried it in Tiled 1.10.1 and it worked for me at least.
