### ISSUE TITLE
request: search and replace

### ISSUE THREAD

**Issue by pixelartgirl** [mapeditor/tiled#3706]
i would like to request a feature to search for tiles in the tilemap (by selecting a tile from the tileset)

- all found tiles should be highlighted
- you could choose a tile from the tileset to replace the found tiles with (or from any other tileset added to the tilemap)

don't close this, it's a good feature request and it's NOT in there

**Comment by pixelartgirl** [comment]
Example of use: replace all grass by another, replace water by another, ...
very usefull feature

**Comment by bjorn** [comment]
I agree it's a good feature request, but this is a duplicate of #3335.

**Comment by bjorn** [comment]
Regarding rule-based search & replace, this feature already exists as [Automapping](https://doc.mapeditor.org/de/latest/manual/automapping/).
