### ISSUE TITLE
github problem

### ISSUE THREAD

**Issue by pixelartgirl** [mapeditor/tiled#3708]
Hi

Not sure where to say this, but for some reason I get "You can't perform this action at this time." for each issue opened by eishiya.
All other issues don't give this error (of all other github users).

Why is that?

Are special magical abilities required to answer eishiya's issues? :-D Or what magic potion I need to drink for this? :-D

**Comment by eishiya** [comment]
Sorry for the inconvenience. I pre-emptively blocked you because of your earlier behaviour on your other accounts, and apparently that prevents you from interacting with my issues as well.

**Comment by pixelartgirl** [comment]
> Sorry for the inconvenience. I pre-emptively blocked you because of your earlier behaviour on your other accounts, and apparently that prevents you from interacting with my issues as well.

What other accounts? I'm only some days on github...

**Comment by pixelartgirl** [comment]
So you block people by assuming things that are not true and therefore prevent me from answering here on certain issues?
This tells more about YOUR behavior then mine... I have no other accounts

**Comment by pixelartgirl** [comment]
I pre-emptively block you because of your behaviour on THIS account of you
