### ISSUE TITLE
request: add extensions

### ISSUE THREAD

**Issue by pixelartgirl** [mapeditor/tiled#3714]
I'm Pixel Art Girl and I come from Pixel Land, where all people have autism!
I was send to earth to make Tiled more user friendly

Can those extensions be added to Tiled?

https://github.com/stars/bjorn/lists/tiled-extensions

There is now the godot, gamemaker, ... so why not add them all?

Could there be made an option to enable/disable extensions here? So it reads the extension folder, and shows them all with a checkbox. So the same as the plugins.

![afbeelding](https://github.com/mapeditor/tiled/assets/133606037/36c908f5-bc6a-4951-9396-94edd08937a4)

**Comment by bjorn** [comment]
At the moment I have no plans to ship extensions with Tiled. The advantage of installing them separately is that they can be developed and updated independently of Tiled and could instead be shipped with any project that uses them, for example.

I do think the discoverability of extensions could be improved, but I think a website would be better for this. The topic of discoverability is also covered by #3336.
