### ISSUE TITLE
request: check for updates

### ISSUE THREAD

**Issue by ghost** [mapeditor/tiled#3715]
I'm Pixel Art Girl and I come from Pixel Land, where all people have autism!
I was send to earth to make Tiled more user friendly

**Is your feature request related to a problem? Please describe.**
We now have a news feature that tells the current version but there is no way to really check for updates yourself and also download automatically the new installer

**Describe the solution you'd like**
Check for updates feature (added in the "help" menu) + automatically  download the new installer.
See audacity: https://www.audacityteam.org/

Workflow:

- user checks for updates when he wants

![afbeelding](https://github.com/mapeditor/tiled/assets/133606037/7ef568b2-6c8d-4441-bdb5-7155ac2b4ab6)

- program tells if it's updated or if there is update ready

![afbeelding](https://github.com/mapeditor/tiled/assets/133606037/35582a97-7c63-46e5-b922-f75c7c51a908)

**Comment by bjorn** [comment]
In Tiled, you can check for updates by opening the About Tiled dialog. It will tell you "Up to date" when you're up to date, or show a button when there is a new version:

![image](https://github.com/mapeditor/tiled/assets/531764/38c2213a-b0a6-4475-9e91-640e6927df42)

By default, when there is a new version available there will also be a button in the status bar (in addition to the News menu).

**Comment by eishiya** [comment]
OP's also asks for automatic downloads:
> also download automatically the new installer

IIRC this feature actually was available in the past, but had to be removed at some point?

**Comment by bjorn** [comment]
> IIRC this feature actually was available in the past, but had to be removed at some point?

It was provided by Sparkle on macOS and WinSparkle on Windows, but I dropped these dependencies to simplify things while replacing it by a more universal update check. If there is demand I could look into automating the update process more, or enabling the itch.io app to do this again (which would mean switching from installer to plain zip file).
