### ISSUE TITLE
question: dockers to other screen

### ISSUE THREAD

**Issue by pixelartgirl** [mapeditor/tiled#3717]
Are the dockers made so we can move them out of the window, to another screen?
I can't do this on my Mac.

**Comment by pixelartgirl** [comment]
This only works on windows, is that normal?

**Comment by bjorn** [comment]
Yes, you should be able to move them out of the window and to another screen as well. Which part is not working for you on macOS?

**Comment by pixelartgirl** [comment]
I can't move nothing out of the window. 
In windows everything can be moved.

**Comment by pixelartgirl** [comment]
PUT THIS SHIT UP YOUR FUCKING ASS
