### ISSUE TITLE
discord not works

### ISSUE THREAD

**Issue by pixelartgirl** [mapeditor/tiled#3720]
If I want to go to discord. can you fix?

![afbeelding](https://github.com/mapeditor/tiled/assets/133606037/f1fa2d28-2a17-4760-8773-4b0669b9eb43)

**Comment by pixelartgirl** [comment]
email is verified!

**Comment by bjorn** [comment]
Sorry I can't help with this. It could be that you were banned, but I to check I'd need to know your Discord handle. For any other reason you'd have to contact Discord support.

**Comment by pixelartgirl** [comment]
I just made a discord account, so how can i be banned? :) I never used Discord

The account I made some hours ago is: pixelartgirl#8904

**Comment by pixelartgirl** [comment]
PUT THIS SHIT UP YOUR FUCKING ASS
