### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by SaltSouls** [mapeditor/tiled#3762]
**Describe the bug**
ASSERT: "layer->isObjectGroup() || layer->isGroupLayer()" in file /build/tiled/src/tiled-1.10.1/src/tiled/mapobjectmodel.cpp, line 313

**To Reproduce**
1. Launch tiled
2. Crash

**Expected behavior**
Should launch just fine

**Specifications:**
 - OS: Arch Linux
 - Kernel: 6.3.5-x64v1-xanmod1-1
 - DE: Plasma 5.27.5 wayland
 - Tiled Version: 1.10.1

**Comment by bjorn** [comment]
Hmm, on startup, this could happen in `ObjectsView::restoreExpandedLayers`, when somehow there is a layer ID stored that previously was an object or group layer, but isn't anymore:

https://github.com/mapeditor/tiled/blob/affd736b2489bc8d68f417f5433a4ae139934dd0/src/tiled/objectsview.cpp#L175-L176

I'll push a fix, thanks for the report!

**Comment by bjorn** [comment]
Btw, I tested this in a release build and it did not appear to be cause any problems. It seems you only ran into this since you're running a debug build, or at least one with assertions enabled. Are you compiling Tiled yourself or is this the standard Arch Linux package?
