### ISSUE TITLE
Crash when assigning file property in custom type editor

### ISSUE THREAD

**Issue by robertk92** [mapeditor/tiled#3783]
The program crashes 5/5 times I've tried this when I assign a value to a file property in the custom type editor. I have verified this in a blank project, same thing happens.

1. Go to View -> Custom Type Editor.
2. Create a new type.
3. Add a file property.
4. Assign a file to the property by browsing to any file on disk.
5. The program crashes.

 OS: Windows 11
 Tiled Version: 1.10.1

**Comment by bjorn** [comment]
Turned out that in addition to the above commit property being related, this was also only happening in Qt 6 builds, so it will not have affected official Tiled 1.9 releases.
