### ISSUE TITLE
tiled.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by RoddurPlayz** [mapeditor/tiled#3786]
The bug was:

The procedure entrypoint SystemParametersinfoForDpi could not be located in the dynamic link library "Directory"

This bug occurs while launching the app. How do I fix it?

**Comment by bjorn** [comment]
What is your OS?

Things to try:

* Uninstall and reinstall Tiled.
* If on old OS, install the version compatible with your OS version. See downloads provided on GitHub releases.

**Comment by bjorn** [comment]
Closing since no further information was provided.
