### ISSUE TITLE
JSON : all user-defined properties are exported as String

### ISSUE THREAD

**Issue by ghost** [mapeditor/tiled#379]
for example :

```
"properties":
{
   "image":"spinning_coin_gold",
   "spritewidth":"32"
},
```

this is not consistent with the regular XML export, where `spritewidth` (here in the example) would have directly the Integer value 32 and not "32".

**Comment by bjorn** [comment]
With Tiled 0.16, there is support for basic property types, and numbers and booleans will no longer be quoted as strings in JSON files.
