### ISSUE TITLE
exporting to game maker 1.4.999

### ISSUE THREAD

**Issue by JackConceprio1** [mapeditor/tiled#3794]
**Describe the bug**
when exporting to game maker 1.4.999 it is missing custom properties

**To Reproduce**
there are no error messages
all you have to do is export to game maker 1.4.999

**Expected behaviour**
this is what it exports: 
 instance objName="obj_enemy_2" x="32" y="224" name="inst_3" locked="0" code="" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/
this is what it should look like:
 instance objName="obj_enemy_2" x="32" y="128" name="inst_2" locked="0" code="hp=5&#xA;" scaleX="1" scaleY="1" colour="4294967295" rotation="0"/

**Specifications:**
 - OS: [e.g. Windows 10]
 - Tiled Version: [e.g. current. You can get this from Help -> About Tiled]

**Comment by bjorn** [comment]
Judging by what you expected, it is missing the value for the `code` attribute? I'm not sure what could cause this, I've just tested the "GameMaker room files" export after setting a custom "code" string property on an instance object (in Tiled, an object with a "Class" set) and it was exported as expected:
```xml
<instance objName="obj_testball" x="220" y="398" name="inst_103" locked="0" code="hp=5" scaleX="2" scaleY="-2" colour="4294967295" rotation="-40"/>
```
Note that the property name is case-sensitive, could that be the issue?

If you wrote the property name correctly, but it still doesn't export, please also provide the map file you're exporting.

**Comment by bjorn** [comment]
Closing this due to lack of further information.
