### ISSUE TITLE
Can't open app built for macos 10.14+ on macos 10.14

### ISSUE THREAD

**Issue by lincerely** [mapeditor/tiled#3809]
**Describe the bug**
The app stated for macOS 10.14+ is actually built for macOS 11.0.

**To Reproduce**
1. Download https://github.com/mapeditor/tiled/releases/download/v1.10.2/Tiled-1.10.2_macOS-10.14+.zip
2. Unzip and tried to open it.

**Expected behavior**
It should run. 

On the other hand, https://github.com/mapeditor/tiled/releases/download/v1.10.2/Tiled-1.10.2_macOS-10.12-10.13.zip runs successfully.

**Media**
Output when run the binary through commandline
```
$ ./Tiled.app/Contents/MacOS/Tiled 
dyld: Symbol not found: _OBJC_CLASS_$_NSConstantArray
  Referenced from: /Users/lincoln/Downloads/Tiled.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/A/QtGui (which was built for Mac OS X 11.0)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Users/lincoln/Downloads/Tiled.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/A/QtGui
Abort trap: 6
```

**Specifications:**
 - OS: macos 10.14.6 Mojave
 - Tiled Version: 1.10.2

**Comment by lincerely** [comment]
related #3707

**Comment by bjorn** [comment]
Hmm, correct, as of Tiled 1.10.2 I have upgraded Qt from 6.4.2 to 6.5.2, but I had not realized that they had dropped support for macOS 10.14 and 10.15 with Qt 6.5.

I'll relabel the files as follows:

* `Tiled-1.10.2_macOS-11+.zip` for the universal binary
* `Tiled-1.10.2_macOS-10.12-10.15.zip ` for the compatibility build

Thanks for bringing this up!
