### ISSUE TITLE
polygon vertices

### ISSUE THREAD

**Issue by n00bjenr399** [mapeditor/tiled#3836]
I am not a 100% sure if its not possible, but can you request the vertices from polygon objects made in the editor ?

**Comment by eishiya** [comment]
Made available how, exactly? They are already individually editable. Do you mean being able to view their locations in e.g. the status bar or properties panel?

Potentially related issue: #836

**Comment by n00bjenr399** [comment]
i have spoken with you in discord and have an answer :) thank you !

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eishiya** [comment]
If there's nothing else you need, please close this issue.
