### ISSUE TITLE
View tileset and tile properties at the same time.

### ISSUE THREAD

**Issue by Dalqin** [mapeditor/tiled#3840]
**Is your feature request related to a problem? Please describe.**
Hi,
I would like to view a tileset's individual Tile Properties while simultaneously viewing the same tileset's Tileset Properties.

My scenarios is... 
I am looking to use the custom Tileset Properties to describe animated sprites for my game.
One example Tileset Property I'm looking to create is called `WalkLeftAnimationTileIds` which will be a comma-separated string of the local tile ids which make up the animation.

I find myself switching to and from Tile Properties and Tileset Properties so that I can build my comma-separated ID list, then typing it into the Tileset Property, but doing so is slow. Maybe there is a faster way already, but I am not finding it. Currently, I use the header menu option `Tileset` -> `Tileset Properties`.

**Describe the solution you'd like**
I'd like to see a new icon within the Tileset view which opens a new, second properties editor in the position of the the other editors (Tile Animation Editor and Tile Collision Editor). The existing properties panel would stay, but default to showing tile zero's properties and only ever show tile properties.
![image](https://github.com/mapeditor/tiled/assets/42662231/e4cedd1e-6f75-482f-9d11-616df0775011)

**Describe alternatives you've considered**
Some other options I thought of:

1. Making it easier to switch between tile and tileset properties.
    * Introduce a hotkey for viewing Tileset properties.
    * Add `Alt` + `T` to the header menu shortcuts, so that I could `Alt` + `T`, then `P`. This one is my least favorite.
    * When clicking outside the boundaries of the tiles, or deselecting a tile, have the Properties panel change to show Tileset Properties.
    * When multiple tiles are selected, `Ctrl` + `c` to copy copies the tile IDs of the selected tiles into the clipboard. (this at least means I do not need to remember (or write into a notepad) the ID numbers before navigating to Tileset Properties).
    * Allow me to open the same .tsx file multiple times in Tiled. This way I could `Ctrl` + `Tab` between, where one which has Tile Properties selected and the other has Tileset Properties selected. (Actually, while writing this I thought to try opening two whole instances of Tiled to do this same idea, and that works for me. But since I wrote all this and would prefer to use one instance of Tiled instead of two I thought to keep the feature request :p)

**Comment by eishiya** [comment]
Duplicate of #3101

**Comment by Dalqin** [comment]
Thank you for the suggestions.

I discovered that you can set keybindings within Tiled's preferences, which solves my situation well enough. I can switch to Tileset properties fast with a hotkey and that allows me to work quickly.

Thanks for reading!
