### ISSUE TITLE
Define own tooltips for custom properties

### ISSUE THREAD

**Issue by Arcanorum** [mapeditor/tiled#3846]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to keep documentation of what a custom property does, what valid values for it are, examples, etc., within Tiled itself, and not have to rely on maintaining our own documentation wiki for our mapping process.

**Describe the solution you'd like**
A simple solution might be to allow adding a tooltip text field for each of the members listed within the custom types editor, where when set, it would replace the text shown when hovering over the custom property name.

![Screenshot from 2023-11-20 19-22-16](https://github.com/mapeditor/tiled/assets/9785268/cb4ff74e-6913-455b-ae47-a4f76ff87144)

**Describe alternatives you've considered**
Currently we hack around this with adding another custom property with a "- help: " prefix for each custom property we have, but it is a bit cumbersome.

![image](https://github.com/mapeditor/tiled/assets/9785268/8ebd3a4c-7b69-4160-95c3-c8b75ee7c9f3)

**Comment by bjorn** [comment]
It's a great idea, but there already was an issue open about this: #2133

Please vote it up and comment there. :-)
