### ISSUE TITLE
Incorrect behavior of brushes when zooming in/out with the mouse wheel.

### ISSUE THREAD

**Issue by faucolt** [mapeditor/tiled#3863]
> Probably a consequence of the cursor position being updated during the zoom. Tiled does a line-fill between the current and last position (this avoids skipping gaps when painting quickly), but when zooming, the cursor's apparent previous position isn't necessarily what Tiled thinks it is.

**Steps to reproduce**
1. Paint continuously while holding the left mouse button. (don't release the mouse button)
2. Zoom in or out on the map using the mouse wheel (Option _Mouse wheel zooms by default_ is checked on tab Interface in Tiled Properties)

**Result**
The brush draws triangles above and below the cursor depending on the direction of the mouse wheel.

**Expected**
The brush draws only to the position it is currently in.

**Videos**
![2024-01-02-03-11-19](https://github.com/mapeditor/tiled/assets/82687931/0bad37d3-909d-4d6a-888e-d401d885b218)
![2024-01-02-03-13-43](https://github.com/mapeditor/tiled/assets/82687931/0a66e12e-c2ce-4b1e-81d6-e0e9ea733073)
![2024-01-02-03-14-12](https://github.com/mapeditor/tiled/assets/82687931/b072d961-4079-42a3-bc57-0caedc8e604b)

**Specifications**
 - OS: Windows 10
 - Tiled Version: 1.10.2
 - Map set to Infinite

**Comment by bjorn** [comment]
Indeed the change of scale is followed up by moving the view such that the same position is still below the mouse, and apparently Qt fires mouse move events for each step (a triangle appears, since first scale changes and then each of the scroll bars are adjusted).

The easiest fix is probably to suppress the mouse move events while handling the wheel events.

**Comment by bjorn** [comment]
Alright, I've [submitted a patch to Qt](https://codereview.qt-project.org/c/qt/qtbase/+/529744) that would make this issue easier to fix, and then I've done a local workaround for Tiled to also fix this for current Qt versions (#3872).
