### ISSUE TITLE
Godot 4 Exporter tscn files not updating

### ISSUE THREAD

**Issue by gummycookie** [mapeditor/tiled#3875]
**Describe the bug**
`tscn` file changes aren't consistently reflected when exporting with the Godot exporter.

**To Reproduce**
1. Configure a Godot project and add a directory for the tiled project.
2. Create a tiled project and create a tileset and tilemap
3. Save the tile map and export as a `tscn` file
4. Attach the `tscn` to a Node2D in Godot
5. Modify the map in tiled , save and reexport.
6. Flaky but notice the `tscn` eventually will stop updating in Godot after modifying the map and reexporting.

**Expected behavior**
It should consistently update the `.tscn` correctly.

**Specifications:**
 - OS:  windows 10
 - Tiled Version: 1.10

**Comment by eishiya** [comment]
Is this a Tiled issue? It sounds like Godot is not watching the file for changes properly.

You could try disabling safe writing of files in Tiled to see if that helps. This setting is in Edit > Preferences > General.

**Comment by gummycookie** [comment]
I'm going to blame it on Godot, looking at the changes to the scene file, it seems like they are there
