### ISSUE TITLE
Custom File Property Not Allowing a Relative Path

### ISSUE THREAD

**Issue by baiguai** [mapeditor/tiled#3877]
In consulting the help system, the File type Custom Property allows for relative paths. However if I browse to a file (Located in a sub directory) it uses the full path in the property. If I manually change it to a relative path it indicates that it is an invalid path (See screenshots).

**To Reproduce**
1. Select an object on the map.
2. Go to its Properties tab.
3. Click the Add Property icon.
4. Choose File and name it.
5. Click the ... to browse for a file (I am using Tiled on Linux).
6. Observe the fully qualified path to the file, and it likes it (Will go to the directory, or launch the file).
7. Manually make that path relative to the Tiled map file.
8. Observe the text is now red, and it considers it an invalid path.

**Expected behavior**
According to the help documentation I should be able to use a relative path here. So if I rebuild my machine, or use it on another machine, this link would still work.

**Media**
If applicable, add screenshots or videos to help explain your problem.

**Specifications:**
 - OS: MX Linux
 - Tiled Version: 1.8.2
![help-docs-indicating-relative](https://github.com/mapeditor/tiled/assets/10997590/142e66a9-eb5a-4ea6-b3ec-1ced5a5389fd)
![path-it-likes](https://github.com/mapeditor/tiled/assets/10997590/6a5f1cb3-f535-4979-a5ac-d4ec144971d7)
![relative-path-it-doesnt-like_attempt-01](https://github.com/mapeditor/tiled/assets/10997590/c46b3aba-9345-4774-be65-5e2994162222)
![relative-path-it-doesnt-like_attempt-02](https://github.com/mapeditor/tiled/assets/10997590/0268e070-a294-493c-9649-ede0d10a7be1)

**Comment by eishiya** [comment]
Not a bug. The paths are *saved* as relative when possible, but at runtime, Tiled needs a full path to know *how* to make it a relative path - it has to be relative to something, after all. The path will be displayed as absolute in Tiled, but if you save the file, the path will be relative, provided a relative path is possible.

**Comment by baiguai** [comment]
Sorry for the delayed response. Thank you so much! Good to know.
