### ISSUE TITLE
tmxrasterizer's --hide-layer doesn't work with group layers

### ISSUE THREAD

**Issue by LakeIshikawa** [mapeditor/tiled#3899]
**Describe the bug**
If I specify a group layer to hide with hide-layer, all children of the group get rendered regardless, this is contrary to the normal behavior of manually hiding a group layer and then rendering the map with tmxrasterizer, in which case they are correctly hidden

**To Reproduce**
1. Make map with 2 group layers "bg" and "fg", each with some children
2. Run tmxrasterizer --hide-layer bg output.png
3. See that bg's children layer are rendered into output.png

**Expected behavior**
"bg"'s children layers shouldn't be rendered into output.png 

**Specifications:**
 - OS: MacOs 14
 - Tiled Version: 1.10.2

**Comment by bjorn** [comment]
You're right, thanks for opening an issue about that! It should be fixed #3903.
