### ISSUE TITLE
"Blob Tileset" points to a broken link

### ISSUE THREAD

**Issue by mward25** [mapeditor/tiled#3908]
**Describe the bug**
The page https://doc.mapeditor.org/en/stable/manual/terrain/ contains a broken link to http://www.cr31.co.uk/stagecast/wang/blob.html. 

**To Reproduce**
1. Go to https://doc.mapeditor.org/en/stable/manual/terrain/
2. Click on the "Blob tileset" link
3. See 404 Error

**Expected behavior**
The link should point to a valid page.

**Specifications:**
 - OS: Android, firefox
 - Tiled Version: None

NOTE:
Archive.org has an archive of the page: https://web.archive.org/web/20220217203126/http://www.cr31.co.uk/stagecast/wang/blob.html

**Comment by eishiya** [comment]
Already fixed by #3883, it's just not been updated on the site yet. The docs will probably be updated when 1.10.3 releases, which should be soon.

**Comment by mward25** [comment]
Oh, thanks for letting me know.
