### ISSUE TITLE
Unable to open a tmx file with a space in the filename using AppImage with the shell

### ISSUE THREAD

**Issue by Palbolsky** [mapeditor/tiled#3914]
**Describe the bug**
I'm having a problem using Tiled's AppImage. I can't open a tmx file from the command line if the filename contains a space. I've tried using ", ' or even trying to escape the space with \\.

**To Reproduce**
1. Download the Tiled's AppImage
2. Open a tmx file with a space in the name with the shell
3. See error

**Expected behavior**
Tiled should open and open the file.

**Media**
![image](https://github.com/mapeditor/tiled/assets/7809685/292b6071-0abb-4c7a-b678-ef853ed77abc)

**Specifications:**
 - OS:
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

 - Tiled Version: 1.10.2

**Comment by bjorn** [comment]
This appears to be due to the following line, where the first parameter isn't being quoted:

https://github.com/mapeditor/tiled/blob/45746fc3152fee34d4d217d315698711714a051f/dist/linux/AppRun#L30
