### ISSUE TITLE
Polygon objects X and Y location not consistent with editor coordinates

### ISSUE THREAD

**Issue by JohnRudy** [mapeditor/tiled#3944]
When creating a polygon shape, the bounding boxes location has a different X and Y coordinate in the object inspector window and the "pixel location" in the lower info bar shows different values.
 
Seems like the X and Y of the inspector is the first vertices position rather than the bounding box. 

Is this by design? 
if so then this bug report can be ignored and closed. 

To reproduce:
1. Create a new map
2. create a new object layer
3. add a polygon
4. check the coordinates of the map pixel location and object inspector X and Y

Screenshot to further elaborate what I mean. 
![bugreport](https://github.com/mapeditor/tiled/assets/44489460/4e40921f-d750-4e29-9554-de7c6d98eb8c)

 - OS: Pop!_OS 22.04 LTS x86_64
 - Tiled Version: 1.10.2

**Comment by eishiya** [comment]
The origin point of a polygon is its first point, this is by design. This behaviour is documented (in the file format docs, since it's not usually relevant otherwise).

**Comment by JohnRudy** [comment]
Thank you for clarifying.  Then it isn't a bug. I'll close this ticket.
