### ISSUE TITLE
Is 16x16 Grids Available Rather Than 32x32?

### ISSUE THREAD

**Issue by LWFlouisa** [mapeditor/tiled#4023]
Currently I seem to be unable to change the layout to support 16x16 tiles, which is the first size most pixel artists learn. I'm going for a SNES type of look.

Specifically I use a mix of both Orthogonal and Hexagonal maps for different purposes: Orthogonal is used for traveling towns, villages, and cities. Hexagonal is mainly used for tactical battle systems.

This is for a custom tileset, rather than one I found online, with a custom color palette.

One interesting thing: you can technically modify the XML to be 16 by 16, but it tries to fit a 16x16 tile inside a 32by32 context.

**Comment by eishiya** [comment]
Tiled supports any tile size. You will probably need to set both your tileset's tile size and your map's grid size to use your tiles correctly, it sounds like you may have set one but not the other.

You also don't need to modify the XML yourself, you can change the map's grid size in Map > Map Properties, and the tileset's tile size (assuming it's a "Based on Tileset Image" tileset) in Tileset > Tileset Properties (you'll need to click the "Image" property and the "Edit" button that appears; or you can make a new tileset with the correct size).
