### ISSUE TITLE
@mapeditor/tiled-api types are outdated

### ISSUE THREAD

**Issue by bendmorris** [mapeditor/tiled#4030]
It looks like the latest version of the TS types on npm is 1.10.1: https://www.npmjs.com/package/@mapeditor/tiled-api?activeTab=versions. I'm trying to use some features that are newer than this - do the types just need to be updated in npm, or is there somewhere else to find the latest version?

**Comment by bjorn** [comment]
Whoops, the types are updated in the repository, but indeed I forgot to publish a new release to npm.
