### ISSUE TITLE
Tiled/extensions/SelectLayerTiles.js:33: TypeError: Cannot call method 'disconnect' of undefined

### ISSUE THREAD

**Issue by ManPython** [mapeditor/tiled#4050]
**Describe the bug**
In some reason I have log:
`Tiled/extensions/SelectLayerTiles.js:33: TypeError: Cannot call method 'disconnect' of undefined`

**To Reproduce**
1. Don't know reason of this.

**Expected behavior** 

**Media** 

**Specifications:**
 - OS: W11
 - Tiled Version:  1.11.0

**Comment by eishiya** [comment]
This seems more appropriate to ask in the script's repo? And if you believe this to be a Tiled issue than a problem with the script, you should explain why.

That said, it sounds like you're running into a Tiled bug that was fixed in 1.11-ish (I'm guessing by Tiled version you meant 1.9.2, not 2.9.2?), so you should be able to run the script without this problem if you use the latest version.

**Comment by ManPython** [comment]
- Tiled Version:  1.9.2
 Just have this type log in Issues dock.

**Comment by ManPython** [comment]
1.11.0 not 1.9.2 ..I'm always checking ver on news.. - bad case..

**Comment by eishiya** [comment]
Another user reported the same issue on Discord. I haven't had it happen (1.11 x64, Win10). Seems intermittent, so perhaps there's still an ownership issue somewhere, causing the signal or the asset to get garbage collected somehow.

**Comment by ManPython** [comment]
It's start visible when I have more .tmx files with custom parameter, but even using more Tiled I see more unexpected behaviors.

**Comment by eishiya** [comment]
Bjorn, dogboydog, and I discussed this issue on Discord. The likely cause is that when an Tiled object (a TileMap in this case) owned by C++ is deleted, there's no reliable way to automatically clear any remaining JS-side references to it, they remain non-null.

I've modified the Select Layer Tiles script to check not only that the TileMap reference exists, but also that it isTileMap, which should be sufficient to also catch deleted TileMaps and avoid trying to disconnect from their signals. Please get the latest version of the script, or add the same check in your local copy: https://github.com/eishiya/tiled-scripts/blob/main/SelectLayerTiles.js#L32

**Comment by bjorn** [comment]
Issue fixed in script, so closing this.

> This seems more appropriate to ask in the script's repo?

Indeed this should have been reported at https://github.com/eishiya/tiled-scripts/issues, but no problem.
