### ISSUE TITLE
Snap object to grid like tile - not pixel cordinations

### ISSUE THREAD

**Issue by ManPython** [mapeditor/tiled#4052]
**Is your feature request related to a problem? Please describe.**
Snap object to grid like tile - not pixel cordinations

**Describe the solution you'd like**
Want precise position for objects if image type with tile from sprite.

**Describe alternatives you've considered**
Center all objects to grid, eg. by center or corners, and snap to corners by origing.

**Comment by eishiya** [comment]
You can already snap Objects to the tile grid using the Snap to Grid option in View > Snapping. To make sure the Tile Objects align exactly the same way as tiles in tile layers, set your Tilesets' Object Alignment to bottom right.

**Comment by ManPython** [comment]
Ok, thx. Closing. But corners can be interesting feature maybe.
