### ISSUE TITLE
Tiled does not support the external hard drive

### ISSUE THREAD

**Issue by Kolodieiev** [mapeditor/tiled#4085]
**Describe the bug**
I don't know is this a bug or a feature. When trying to use Tiled on Linux, I don't see my external usb-connected hard drive in the directory list. At first I thought the .AppImage didn't have access to external drives. Then I installed Tiled from snap. Run command: `snap connect tiled:removable-media`. But it didn't change anything. The hard drive does not appear in the list of available directories. So I can't open the projects written on it. There are no problems when working with projects on SSD. But it's a bit inconvenient to sync because I'd like my projects to be stored on the HDD. In other programs such as vs code or gitkraken, my external hard drive is supported without problems.

**Expected behavior**
Support for external disk drives.

**Specifications:**
 - OS: Linux Lite
 - Tiled Version: 1.11.0

**Comment by bjorn** [comment]
Hmm, I guess the file chooser may not show a shortcut for the external hard drive, but if your drive is mounted on your file system, you should be able to just browse to that location. Did you try that? That should at least work with the AppImage, not sure about the snap.

You could also try whether [the Flatpak](https://flathub.org/apps/org.mapeditor.Tiled) works better. That one should use the native file dialog which normally shows the shortcuts to the removal drives, at least it does for me.

**Comment by Zireael07** [comment]
@bjorn Flatpaks frequently are denied access to removable drives. (I do not know wjhy exactly, is it some config end users need to flip, or what) so it's unlikely to help

**Comment by bjorn** [comment]
@Zireael07 Hmm, the Flatpak is using `--filesystem=host` which I think gives access to the entire filesystem. It can't rely on portals like most other apps because of the need to open files (tilesets and images) referenced from the chosen file.

**Comment by Zireael07** [comment]
I meant flatpaks in general, not necessarily yours, just a fyi
