### ISSUE TITLE
Input Method Doesn't Work in File Search Box (Cannot Input Chinese/Japanese)

### ISSUE THREAD

**Issue by gzz100** [mapeditor/tiled#4119]
the search box control can not use input method to input text.

In Tiled Map Editor "Open File or Project..." and "Search Actions..." menu. The file search box does not support input from input methods such as Chinese or Japanese. While switching input methods works fine, characters typed in these languages do not appear in the search box.
However, if you paste text (e.g., Chinese or Japanese characters), it works fine. This suggests that the input method switch is recognized, but the typed characters are not displayed or processed correctly.

Only English characters can be typed. Chinese and Japanese input methods fail to display typed characters, though pasting text works.

**Comment by dogboydog** [comment]
I think this is the same as #3403

**Comment by bjorn** [comment]
Indeed that's the same issue. Might have something to do with the input being inside a popup...
