### ISSUE TITLE
32-bit OS X binaries

### ISSUE THREAD

**Issue by tba-apps** [mapeditor/tiled#45]
Would it be easy to include 32-bit binaries for OS X on your web site? I have an old laptop and am unable to run the 64-bit app. I've tried building from source but installing qt4 with Macports is an error-filled nightmare.

Thanks!

**Comment by bjorn** [comment]
32-bit macOS Tiled version [requested on the forum](https://discourse.mapeditor.org/t/application-not-supported-on-this-type-of-mac-mac10-6/3251).
