### ISSUE TITLE
Allow changing the properties of multiple tiles simultaneously

### ISSUE THREAD

**Issue by bjorn** [mapeditor/tiled#5]
When you're using tile properties intensively, it can get very annoying to edit the properties of many tiles, since at the moment you can only edit the properties of one tile at a time. It should really be possible to edit the properties of multiple tiles at the same time.

Problematic here is dealing with the inconsistent state that the multiple selected tiles might be in. They do not necessarily already all have the same properties or the same value for existing properties. The GUI should reflect this.

This issue was moved from the old issue tracker:
http://sourceforge.net/apps/mantisbt/tiled/view.php?id=48

**Comment by abelnation** [comment]
Does this fix support editing collision regions for multiple selected tiles?  When I do so, it doesn't visually report that any individual tile in the selection has it's region set.

**Comment by bjorn** [comment]
> Does this fix support editing collision regions for multiple selected tiles? When I do so, it doesn't visually report that any individual tile in the selection has it's region set.

No, that's not supported. I'm not quite sure how that would work, since these tiles could already have different collision shapes associated with them.

**Comment by abelnation** [comment]
@bjorn i guess the thought is that it's a convenient way to rapidly overwrite the collision value for all those tiles.  e.g.:

1) select 5 tiles
2) set region to a square
3) select 1 of those 5 tiles
4) it's collision region should now be set to a square

If a previous value was set for any of the 5 tiles, it would be overwritten.  Thoughts?

**Comment by bjorn** [comment]
@abelnation That could work, but I do think it would require some feedback to the user in case not all selected tiles already have the same collision shapes.

**Comment by abelnation** [comment]
I guess I'm a little confused on what setting a collision area when you have multiple tiles selected would otherwise do? Does it currently have some effect that I'm misunderstanding? 

Anyways, thanks for listening :) love the tool, and I appreciate the work you put into it!

**Comment by bjorn** [comment]
> I guess I'm a little confused on what setting a collision area when you have multiple tiles selected would otherwise do? Does it currently have some effect that I'm misunderstanding?

No, currently it simply only affects the last clicked tile, not the full selection. It is only displaying the last clicked tile and its collision shapes, so when upon editing those the changed shapes would be applied to all selected tiles, you could be changing the collision shapes of the other tiles unintentionally.

> Anyways, thanks for listening :) love the tool, and I appreciate the work you put into it!

Happy to hear that!

**Comment by adsilcott** [comment]
I second @abelnation , setting the collisions on multiple tiles would be wonderful, considering that a huge percentage of them tend to be exactly the same-- full collision platforms for example. Even with a "Are you sure?" dialog this would be a huge time saver. Should this be opened as a new issue?

**Comment by bjorn** [comment]
@adsilcott Sure, please open a new issue about this, thanks!
