### ISSUE TITLE
Two render bugs

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled#535]
Macbook Air 2011, Mac OSX Lion  , use Tiled 2013-09-27 ver. .

1) add image on object-layer , will appear some useless dots-rects in edit-area:
( it's the same on  opengl-on and opengl-off )
![2013-10-01 1 28 36](https://f.cloud.github.com/assets/288367/1243021/dd6dbc3e-2a5a-11e3-8440-777a4b2bc932.png)

2) on tilelayer ,select one tile , then scroll edit-area , will appear some  waste tiles (just render, not draw tile in the map)
( opengl-on no this issus, but I can't open opengl , because Issue #529 )
![2013-10-01 1 31 07](https://f.cloud.github.com/assets/288367/1243022/0fb046b2-2a5b-11e3-93f3-f28a88b1364e.png)

**Comment by bjorn** [comment]
The remaining issue is actually covered by #174 so I'll close this one.
