### ISSUE TITLE
Terrain Brush In-Depth Tutorial

### ISSUE THREAD

**Issue by ghost** [mapeditor/tiled#570]
I simply adore Tiled, but am wondering a bit about the terrain tool. I saw the tutorial on it, but it didn't go deep enough into the format for the corners. Can someone write an in-depth tutorial about how you _get_ the regions shown in the tutorial (i.e. what clicking about "tells" Tiled what the boundary between this and that is, rather than a plug-and-play example)?

**Comment by bjorn** [comment]
I've recently updated the Terrain Brush documentation to the latest version of Tiled, but the contents has stayed largely the same. What part were you missing exactly? Is it about being more specific at this section:

> select the Sand terrain and mark all corners in the tileset with this type of terrain.

Since it is unclear how the corner should be marked?

**Comment by bjorn** [comment]
I added a bit more explanation in 264278388d3c1c81a7d5b7472d8793aabca09da6. I think that closes this issue, but let me know if there's anything still unclear.
