### ISSUE TITLE
Tile Objects with Multiple Tiles

### ISSUE THREAD

**Issue by Bryan-Legend** [mapeditor/tiled#64]
I'd like to be able to have a tile object use multiple tiles in a tile set.  For instance, there could be a big tree that's 4 x 4 tiles that I'd like to drop on the map using a single tile object.

**Comment by Kayoscape** [comment]
I know this is a closed issue, but this feature would be incredibly useful for me.

I'm currently making a game that has to use 8x8 tiles for collision purposes, but the world is made up of repeating 16x16 arrangements of these tiles (trees, statues, etc.). It would make my work literally four times as fast if I could create objects out of tiles and then place them together as sets. I am trying to keep the game as lightweight as possible, so pre-arranging them into individual tilesets would cost too much space.

If this feature could be considered for future development I would be very grateful. Thanks!

**Comment by bjorn** [comment]
@Kayoscape To ease the selection of multi-tile objects like trees and statues, did you try the "Tile Stamps" view? It allows you to save tile stamps by name and shows a thumbnail, so you can quickly find them again later.

**Comment by bjorn** [comment]
@Kayoscape You can see me using the Tile Stamps view briefly as part of this video, though the multi-layer aspect of it is still in development (on the `wip/multi-layer` branch): https://www.youtube.com/watch?v=pu-yShBRCqM

**Comment by Kayoscape** [comment]
@bjorn That's exactly what I was looking for. Thanks!
