### ISSUE TITLE
Small Terrain Tiles

### ISSUE THREAD

**Issue by Tyyppi77** [mapeditor/tiled#678]
I was trying to create a Platformer map using the Terrain Editor, since that does mostly the job for me. I was wondering if there's a way to add 1 wide / 1 tall terrain tiles?

**Comment by bjorn** [comment]
These are supported by the Terrain Tool as "Edge Set": https://doc.mapeditor.org/en/latest/manual/terrain/, since [Tiled 1.5](https://www.mapeditor.org/2021/03/23/tiled-1-5-0-released.html) (and earlier as "Wang Sets", but they didn't really work like terrains).
