### ISSUE TITLE
object selection with multiple object layers are melting

### ISSUE THREAD

**Issue by alwex** [mapeditor/tiled#752]
while you have multiple object layer, fit you select one layer, you can drag the object from another layer, this is very anoying as you are forced to disable the overlapping layer to manipulate an object under another layer object.

I think it would be better if the selected object layer is active while editing.

**Comment by bjorn** [comment]
With change 44c02dc2a599abcaad1d3fcde138b63352989931 there are now two alternative options regarding the selection behavior: to either consider only objects from selected layers, or to prefer selecting objects from selected layers. The latter is automatically enabled, when "highlight current layer" is on.
