### ISSUE TITLE
Placing objects in a staggered map results in an offset object

### ISSUE THREAD

**Issue by karai17** [mapeditor/tiled#766]
When I select any object type and click the mouse to begin creating it, the origin of the object is -1 on the y-axis from where I click.

If I click on tile 3,3 then the object will begin creation on 3,2.

**Comment by Kherae** [comment]
surprised this has been open for almost 6 years now, without a fix. I was about to put a hole in my wall trying to figure out why objects were aligned wrong. does not help that image offsets also don't work on objects.

**Comment by bjorn** [comment]
This issue was fixed in Tiled 1.8.0, by changes 1b7f9f91da078caee97736923fbb55c5496b5286 and af24ff5305f90f41d3f387923cae1d52a497ee30.

I've made another change related to this for the next patch release, affecting the snapping of scalable objects during their creation (fd3443fe).
