### ISSUE TITLE
Tileset with gaps produces incorrect .json

### ISSUE THREAD

**Issue by Christian-Broomfield** [mapeditor/tiled#831]
Hello,

[I've recently encountered](http://www.html5gamedevs.com/topic/10192-tiledmap-loaded-with-incorrect-tiles/) a bug concerning the output .json for a tilemap I created. Every tile would be off by one per row. That means tiles in the first row displayed the tile to the left, in the second row they were off by two, and so forth. [Another user has now encountered the same error](http://www.html5gamedevs.com/topic/10673-phaser-and-tiled/). 

_The solution is to cut the tileset and make sure no gaps are present. Otherwise, it can sometimes- but not always- lead to an incorrect .json._ 

[See also this sample project I created which loads a Tiled .json into Phaser](https://github.com/SoulBeaver/broken-tiled-tilemap). I have included the tileset, .tmx and .json files so you can compare/contrast. 

Finally, this only happens with the .json. If I use LibGDX and load the .tmx instead of the .json file it renders the entire tilemap flawlessly. I sadly do not have an example of this at the moment, but I also don't believe that it's necessary. In case I am wrong I'd be happy to provide you with a LibGDX example showing the same tilemap rendering correctly.

**Comment by bjorn** [comment]
@SoulBeaver It's nice that you solved this issue and that the issue was also fixed in Phaser. Unfortunately, the topics you're linking to in your first post seem to have not been updated. This leaves especially the first one with a "best answer" stating "For some reason, Tiled doesn't handle Tilemaps with gaps very well". This is incorrect, so maybe you could edit that?

**Comment by englercj** [comment]
I updated those threads with a small post explaining it was a bug in Phaser, but unfortunately I am not a moderator in that forum so I can't edit/reassign answer.
